//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@interface _TtC16Pixel_Art_Camera17YPLibraryViewCell : UICollectionViewCell
{
    // Error parsing type: , name: representedAssetIdentifier
    // Error parsing type: , name: imageView
    // Error parsing type: , name: durationLabel
    // Error parsing type: , name: selectionOverlay
    // Error parsing type: , name: multipleSelectionIndicator
}

- (void).cxx_destruct;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

