//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface _TtC16Pixel_Art_Camera19YPAssetZoomableView : UIScrollView
{
    // Error parsing type: , name: myDelegate
    // Error parsing type: , name: cropAreaDidChange
    // Error parsing type: , name: squaredZoomScale
    // Error parsing type: , name: isVideoMode
    // Error parsing type: , name: photoImageView
    // Error parsing type: , name: videoView
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

