//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC16Pixel_Art_Camera8YPCropVC : UIViewController
{
    // Error parsing type: , name: didFinishCropping
    // Error parsing type: , name: originalImage
    // Error parsing type: , name: pinchGR
    // Error parsing type: , name: panGR
    // Error parsing type: , name: v
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)done;
- (void)cancel;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (void)loadView;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;

@end

