//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16Pixel_Art_Camera8YPCropVC.h"

@interface _TtC16Pixel_Art_Camera8YPCropVC (Pixel_Art_Camera)
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)pan:(id)arg1;
- (void)pinch:(id)arg1;
@end

