//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC16Pixel_Art_Camera12QuickTimeMov : _TtCs12_SwiftObject
{
    // Error parsing type: , name: kKeyContentIdentifier
    // Error parsing type: , name: kKeyStillImageTime
    // Error parsing type: , name: kKeySpaceQuickTimeMetadata
    // Error parsing type: , name: path
    // Error parsing type: , name: dummyTimeRange
    // Error parsing type: , name: asset.storage
}

@end

