//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC16Pixel_Art_Camera11YPVideoView : UIView
{
    // Error parsing type: , name: playImageView
    // Error parsing type: , name: playerView
    // Error parsing type: , name: playerLayer
    // Error parsing type: , name: previewImageView
}

- (void).cxx_destruct;
- (void)playerItemDidReachEnd:(id)arg1;
- (void)singleTap;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

