//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16Pixel_Art_Camera10YPPickerVC.h"

#import "_TtP16Pixel_Art_Camera21YPLibraryViewDelegate_-Protocol.h"

@interface _TtC16Pixel_Art_Camera10YPPickerVC (Pixel_Art_Camera) <_TtP16Pixel_Art_Camera21YPLibraryViewDelegate_>
- (void)albumViewCameraRollAuthorized;
- (void)albumViewCameraRollUnauthorized;
- (void)libraryViewDidToggleMultipleSelectionWithEnabled:(_Bool)arg1;
- (void)libraryViewFinishedLoading;
- (void)libraryViewStartedLoading;
@end

