//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC16Pixel_Art_Camera13YPBottomPager : UIViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: controllers
    // Error parsing type: , name: v
    // Error parsing type: , name: currentPage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)tabTapped:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)loadView;

@end

