//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC16Pixel_Art_Camera16PanGestureHelper : NSObject
{
    // Error parsing type: , name: v
    // Error parsing type: , name: assetViewContainerOriginalConstraintTop
    // Error parsing type: , name: dragDirection
    // Error parsing type: , name: imaginaryCollectionViewOffsetStartPosY
    // Error parsing type: , name: cropBottomY
    // Error parsing type: , name: dragStartPos
    // Error parsing type: , name: dragDiff
    // Error parsing type: , name: _isImageShown
}

- (void).cxx_destruct;
- (id)init;
- (void)panned:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;

@end

