//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC16Pixel_Art_Camera13YPVideoHelper : NSObject
{
    // Error parsing type: , name: didCaptureVideo
    // Error parsing type: , name: videoRecordingProgress
    // Error parsing type: , name: session
    // Error parsing type: , name: timer
    // Error parsing type: , name: dateVideoStarted
    // Error parsing type: , name: sessionQueue
    // Error parsing type: , name: videoInput
    // Error parsing type: , name: videoOutput
    // Error parsing type: , name: videoRecordingTimeLimit
}

- (void).cxx_destruct;
- (id)init;
- (void)tick;

@end

