//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC16Pixel_Art_Camera20YPAssetViewContainer : UIView
{
    // Error parsing type: , name: zoomableView
    // Error parsing type: , name: grid
    // Error parsing type: , name: curtain
    // Error parsing type: , name: spinnerView
    // Error parsing type: , name: squareCropButton
    // Error parsing type: , name: multipleSelectionButton
    // Error parsing type: , name: onlySquare
    // Error parsing type: , name: isShown
    // Error parsing type: , name: spinner
    // Error parsing type: , name: shouldCropToSquare
    // Error parsing type: , name: isMultipleSelection
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)squareCropButtonTapped;
- (void)awakeFromNib;

@end

