//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16Pixel_Art_Camera13YPBottomPager.h"

@interface _TtC16Pixel_Art_Camera10YPPickerVC : _TtC16Pixel_Art_Camera13YPBottomPager
{
    // Error parsing type: , name: albumsManager
    // Error parsing type: , name: shouldHideStatusBar
    // Error parsing type: , name: initialStatusBarHidden
    // Error parsing type: , name: PermissionGranted
    // Error parsing type: , name: navbar_font_size
    // Error parsing type: , name: NoPermissionView2
    // Error parsing type: , name: didClose
    // Error parsing type: , name: didSelectItems
    // Error parsing type: , name: libraryVC
    // Error parsing type: , name: cameraVC
    // Error parsing type: , name: videoVC
    // Error parsing type: , name: mode
    // Error parsing type: , name: capturedImage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)done;
- (void)close;
- (void)navBarTapped;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;

@end

