//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, UICollectionView, _TtC16Pixel_Art_Camera19YPAssetZoomableView, _TtC16Pixel_Art_Camera20YPAssetViewContainer;

@interface _TtC16Pixel_Art_Camera13YPLibraryView : UIView
{
    // Error parsing type: , name: assetZoomableViewMinimalVisibleHeight
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: assetZoomableView
    // Error parsing type: , name: assetViewContainer
    // Error parsing type: , name: assetViewContainerConstraintTop
    // Error parsing type: , name: maxNumberWarningView
    // Error parsing type: , name: maxNumberWarningLabel
    // Error parsing type: , name: progressView
    // Error parsing type: , name: line
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
@property(nonatomic) __weak NSLayoutConstraint *assetViewContainerConstraintTop; // @synthesize assetViewContainerConstraintTop;
@property(nonatomic) __weak _TtC16Pixel_Art_Camera20YPAssetViewContainer *assetViewContainer; // @synthesize assetViewContainer;
@property(nonatomic) __weak _TtC16Pixel_Art_Camera19YPAssetZoomableView *assetZoomableView; // @synthesize assetZoomableView;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

