//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16Pixel_Art_Camera13YPVideoHelper.h"

#import "AVCaptureFileOutputRecordingDelegate-Protocol.h"

@interface _TtC16Pixel_Art_Camera13YPVideoHelper (Pixel_Art_Camera) <AVCaptureFileOutputRecordingDelegate>
- (void)captureOutput:(id)arg1 didFinishRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3 error:(id)arg4;
- (void)captureOutput:(id)arg1 didStartRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3;
@end

