//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIImageView, UIView, _TtC16Pixel_Art_Camera10YPMenuItem, _TtC16Pixel_Art_Camera11YPVideoView;

@interface _TtC16Pixel_Art_Camera16YPVideoFiltersVC : UIViewController
{
    // Error parsing type: , name: trimBottomItem
    // Error parsing type: , name: coverBottomItem
    // Error parsing type: , name: videoView
    // Error parsing type: , name: trimmerView
    // Error parsing type: , name: coverImageView
    // Error parsing type: , name: coverThumbSelectorView
    // Error parsing type: , name: inputVideo
    // Error parsing type: , name: playbackTimeCheckerTimer
    // Error parsing type: , name: imageGenerator
    // Error parsing type: , name: isFromSelectionVC
    // Error parsing type: , name: didSave
    // Error parsing type: , name: didCancel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) __weak UIView *coverThumbSelectorView; // @synthesize coverThumbSelectorView;
@property(nonatomic) __weak UIImageView *coverImageView; // @synthesize coverImageView;
@property(nonatomic) __weak UIView *trimmerView; // @synthesize trimmerView;
@property(nonatomic) __weak _TtC16Pixel_Art_Camera11YPVideoView *videoView; // @synthesize videoView;
@property(nonatomic) __weak _TtC16Pixel_Art_Camera10YPMenuItem *coverBottomItem; // @synthesize coverBottomItem;
@property(nonatomic) __weak _TtC16Pixel_Art_Camera10YPMenuItem *trimBottomItem; // @synthesize trimBottomItem;

@end

