//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC16Pixel_Art_Camera19LibraryMediaManager : _TtCs12_SwiftObject
{
    // Error parsing type: , name: v
    // Error parsing type: , name: collection
    // Error parsing type: , name: fetchResult
    // Error parsing type: , name: previousPreheatRect
    // Error parsing type: , name: imageManager
    // Error parsing type: , name: selectedAsset
    // Error parsing type: , name: exportTimer
}

- (void)onTickExportTimerWithSender:(id)arg1;

@end

