//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIButton;

@interface AboutView : UIViewController
{
    UIButton *restore_button;
}

- (void).cxx_destruct;
- (void)CheckOutBtnClick:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)childViewControllerForStatusBarHidden;
- (_Bool)prefersStatusBarHidden;
- (void)CloseClick:(id)arg1;
- (void)InstaButtonClick:(id)arg1;
- (void)EmailButtonClick:(id)arg1;
- (void)SiteButtonClick:(id)arg1;
- (void)RestoreBtnClick:(id)arg1;
- (void)RateBtnClick2:(id)arg1;
- (void)AddTopBar;
- (void)viewDidLoad;

@end

