//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class ALAdSize, ALAdType, ALSdk, NSDictionary, NSString;

@interface ALAdZone : NSObject <NSCopying, NSCoding>
{
    NSString *_identifier;
    ALSdk *_sdk;
    NSDictionary *_zoneObject;
    NSString *_zoneIdentifier;
    ALAdSize *_size;
    ALAdType *_type;
}

+ (id)nativeZoneWithSDK:(id)arg1;
+ (id)zoneWithIdentifier:(id)arg1 size:(id)arg2 sdk:(id)arg3;
+ (id)incentivizedInterstitialZoneWithSDK:(id)arg1;
+ (id)regularInterstitialZoneWithSDK:(id)arg1;
+ (id)leaderZoneWithSDK:(id)arg1;
+ (id)MRecZoneWithSDK:(id)arg1;
+ (id)bannerZoneWithSDK:(id)arg1;
+ (id)allPrimaryZonesWithSDK:(id)arg1;
+ (id)zoneWithSize:(id)arg1 type:(id)arg2 zoneIdentifier:(id)arg3 sdk:(id)arg4;
+ (id)incentivizedZoneWithIdentifier:(id)arg1 sdk:(id)arg2;
+ (id)nativeZoneWithIdentifier:(id)arg1 sdk:(id)arg2;
+ (id)zoneWithSize:(id)arg1 type:(id)arg2 sdk:(id)arg3;
+ (id)zoneWithIdentifier:(id)arg1 zoneObject:(id)arg2 sdk:(id)arg3;
+ (id)zoneWithIdentifier:(id)arg1 sdk:(id)arg2;
+ (void)initialize;
@property(retain, nonatomic) ALAdType *type; // @synthesize type=_type;
@property(retain, nonatomic) ALAdSize *size; // @synthesize size=_size;
@property(copy, nonatomic) NSString *zoneIdentifier; // @synthesize zoneIdentifier=_zoneIdentifier;
@property(retain, nonatomic) NSDictionary *zoneObject; // @synthesize zoneObject=_zoneObject;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)settingWithPrefix:(id)arg1 defaultSetting:(id)arg2;
@property(readonly, nonatomic, getter=isPrimaryZone) _Bool primaryZone; // @dynamic primaryZone;
@property(readonly, nonatomic, getter=isDummyAdsEnabled) _Bool dummyAdsEnabled; // @dynamic dummyAdsEnabled;
- (_Bool)hasUserEnabledPreloadType:(id)arg1 adSize:(id)arg2;
- (_Bool)hasUserEnabledPreloadType;
@property(readonly, nonatomic, getter=shouldMergeInitialPreloads) _Bool mergeInitialPreloads; // @dynamic mergeInitialPreloads;
@property(readonly, nonatomic) unsigned long long preloadCount; // @dynamic preloadCount;
@property(readonly, nonatomic) unsigned long long extendedCapacity; // @dynamic extendedCapacity;
@property(readonly, nonatomic) unsigned long long capacity; // @dynamic capacity;
@property(readonly, nonatomic, getter=isNative) _Bool native; // @dynamic native;
- (id)initWithSize:(id)arg1 type:(id)arg2 zoneIdentifier:(id)arg3 sdk:(id)arg4;

@end

