//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAd, ALAdEventStatsManager, ALGlobalStatsManager, ALSdk;

@interface ALAdEventStatsManagerHelper : NSObject
{
    _Bool _didTrackInterstitialMuteInitially;
    ALAd *_currentAd;
    ALSdk *_sdk;
    long long _createdAtMillis;
    NSObject *_stateLock;
    long long _adShownAtMillis;
    long long _adClickAtMillis;
    long long _adPausedDurationMillis;
    long long _toggleMuteAtMillis;
}

+ (void)trackCacheStats:(id)arg1 forAd:(id)arg2 sdk:(id)arg3;
+ (void)trackRenderTime:(long long)arg1 forAd:(id)arg2 sdk:(id)arg3;
+ (void)trackFetchStatsForAd:(id)arg1 sdk:(id)arg2;
@property(nonatomic) _Bool didTrackInterstitialMuteInitially; // @synthesize didTrackInterstitialMuteInitially=_didTrackInterstitialMuteInitially;
@property(nonatomic) long long toggleMuteAtMillis; // @synthesize toggleMuteAtMillis=_toggleMuteAtMillis;
@property(nonatomic) long long adPausedDurationMillis; // @synthesize adPausedDurationMillis=_adPausedDurationMillis;
@property(nonatomic) long long adClickAtMillis; // @synthesize adClickAtMillis=_adClickAtMillis;
@property(nonatomic) long long adShownAtMillis; // @synthesize adShownAtMillis=_adShownAtMillis;
@property(retain, nonatomic) NSObject *stateLock; // @synthesize stateLock=_stateLock;
@property(nonatomic) long long createdAtMillis; // @synthesize createdAtMillis=_createdAtMillis;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(retain, nonatomic) ALAd *currentAd; // @synthesize currentAd=_currentAd;
- (void).cxx_destruct;
@property(readonly, nonatomic) ALGlobalStatsManager *globalStats; // @dynamic globalStats;
@property(readonly, nonatomic) ALAdEventStatsManager *adStats; // @dynamic adStats;
- (void)trackTimeSinceShowForStatKey:(id)arg1;
- (void)trackInterstitialVideoStreamStalled;
- (void)trackInterstitialPoststitialCodeExecuted;
- (void)trackInterstitialToggledMute;
- (void)trackInterstitialMutedInitially:(_Bool)arg1;
- (void)trackInterstitialPausedDuration:(long long)arg1;
- (void)trackInterstitialVideoPercentViewed:(id)arg1;
- (void)trackInterstitialUsedVideoStream:(_Bool)arg1;
- (void)trackUnableToPersistWebKitHTMLPlacementReplacedString;
- (void)trackUnableToRetrieveWebKitHTMLString;
- (void)trackIsStreamingWebKit;
- (void)trackAdShownWithWebKit;
- (void)trackAdUsedGraphicStream:(_Bool)arg1;
- (void)trackAdViewContracted;
- (void)trackAdViewExpanded;
- (void)trackInterstitialVideoSkipped;
- (void)trackInterstitialOptOutButtonClickThrough;
- (void)trackAdHidden;
- (void)trackAdClicked;
- (void)trackAdShown;
- (id)initWithAd:(id)arg1 sdk:(id)arg2;

@end

