//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALArrayDictionary.h"

@interface ALAdEventStatsMap : ALArrayDictionary
{
    unsigned long long _maxCapacity;
}

@property(nonatomic) unsigned long long maxCapacity; // @synthesize maxCapacity=_maxCapacity;
- (_Bool)shouldRemoveEldestKey:(id)arg1 object:(id)arg2;
- (id)initWithMaxCapacity:(unsigned long long)arg1;

@end

