//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALAdHiddenCallbackTimeoutManagerDelegate-Protocol.h"
#import "ALAdViewControllerObserverDelegate-Protocol.h"

@class ALAdHiddenCallbackTimeoutManager, ALAdViewControllerObserver, ALLogger, NSString;
@protocol MAAdDelegate;

@interface ALAdHiddenCallbackScheduler : NSObject <ALAdHiddenCallbackTimeoutManagerDelegate, ALAdViewControllerObserverDelegate>
{
    ALLogger *_logger;
    ALAdViewControllerObserver *_adViewControllerObserver;
    ALAdHiddenCallbackTimeoutManager *_callbackTimeoutManager;
    id <MAAdDelegate> _delegate;
}

@property(retain, nonatomic) id <MAAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ALAdHiddenCallbackTimeoutManager *callbackTimeoutManager; // @synthesize callbackTimeoutManager=_callbackTimeoutManager;
@property(retain, nonatomic) ALAdViewControllerObserver *adViewControllerObserver; // @synthesize adViewControllerObserver=_adViewControllerObserver;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
- (void)onLastAdViewControllerDismissedForAd:(id)arg1;
- (void)onAdHiddenTimedOutForAd:(id)arg1;
- (void)cancelScheduledAdHiddenTimeoutsForAd:(id)arg1;
- (void)scheduleForAd:(id)arg1;
- (id)initWithSdk:(id)arg1 andNotify:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

