//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, NSDictionary, NSString;

@interface ALAdToken : NSObject
{
    NSString *_identifier;
    ALSdk *_sdk;
}

@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)identifierHasPrefixForSetting:(id)arg1;
- (id)stringFromType:(long long)arg1;
@property(readonly, nonatomic) NSDictionary *fullAdResponse; // @dynamic fullAdResponse;
@property(readonly, copy, nonatomic) NSString *typePrefix; // @dynamic typePrefix;
@property(readonly, nonatomic) long long type; // @dynamic type;
- (id)initWithIdentifier:(id)arg1 sdk:(id)arg2;

@end

