//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALPostbackDelegate-Protocol.h"

@class ALAdServerAd, ALAdService, ALAtomicBoolean, ALBaseVideoViewController, ALVideoView, NSString, NSURL;

@interface ALAdServiceVideoPostbackProxy : NSObject <ALPostbackDelegate>
{
    ALAdService *_adService;
    ALAdServerAd *_ad;
    ALVideoView *_videoView;
    ALBaseVideoViewController *_viewController;
    NSURL *_clickDestinationURL;
    ALAtomicBoolean *_hasClickedThrough;
}

+ (id)postbackProxyWithAdService:(id)arg1 videoView:(id)arg2 ad:(id)arg3 viewController:(id)arg4 launchURL:(id)arg5;
@property(retain, nonatomic) ALAtomicBoolean *hasClickedThrough; // @synthesize hasClickedThrough=_hasClickedThrough;
@property(retain, nonatomic) NSURL *clickDestinationURL; // @synthesize clickDestinationURL=_clickDestinationURL;
@property(nonatomic) __weak ALBaseVideoViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) ALVideoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) ALAdServerAd *ad; // @synthesize ad=_ad;
@property(nonatomic) __weak ALAdService *adService; // @synthesize adService=_adService;
- (void).cxx_destruct;
- (void)clickThrough;
- (void)postbackService:(id)arg1 didFailToExecutePostback:(id)arg2 errorCode:(long long)arg3;
- (void)postbackService:(id)arg1 didExecutePostback:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

