//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, ALTimer;
@protocol ALAdExpirationManagerDelegate;

@interface ALAdExpirationManager : NSObject
{
    ALSdk *_sdk;
    id <ALAdExpirationManagerDelegate> _delegate;
    ALTimer *_timer;
    NSObject *_timerLock;
    long long _fireTime;
}

@property(nonatomic) long long fireTime; // @synthesize fireTime=_fireTime;
@property(retain, nonatomic) NSObject *timerLock; // @synthesize timerLock=_timerLock;
@property(retain, nonatomic) ALTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak id <ALAdExpirationManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)dealloc;
- (void)applicationResumed:(id)arg1;
- (void)applicationPaused:(id)arg1;
- (void)addNotificationCenterObservers;
- (void)cancelTimer;
- (void)cancel;
- (void)scheduleAdExpirationWithTime:(long long)arg1;
- (id)initWithSDK:(id)arg1 andNotifiy:(id)arg2;

@end

