//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ALAd, ALAdView;

@protocol ALAdViewEventDelegate <NSObject>

@optional
- (void)ad:(ALAd *)arg1 didFailToDisplayInAdView:(ALAdView *)arg2 withError:(long long)arg3;
- (void)ad:(ALAd *)arg1 didReturnToApplicationForAdView:(ALAdView *)arg2;
- (void)ad:(ALAd *)arg1 willLeaveApplicationForAdView:(ALAdView *)arg2;
- (void)ad:(ALAd *)arg1 didDismissFullscreenForAdView:(ALAdView *)arg2;
- (void)ad:(ALAd *)arg1 willDismissFullscreenForAdView:(ALAdView *)arg2;
- (void)ad:(ALAd *)arg1 didPresentFullscreenForAdView:(ALAdView *)arg2;
@end

