//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSNumber, NSString;

@interface ALAdEventStats : NSObject
{
    NSString *_primaryKey;
    NSString *_secondaryKey1;
    NSString *_secondaryKey2;
    NSNumber *_createdAtMilliseconds;
    NSMutableDictionary *_stats;
}

@property(retain, nonatomic) NSMutableDictionary *stats; // @synthesize stats=_stats;
@property(retain, nonatomic) NSNumber *createdAtMilliseconds; // @synthesize createdAtMilliseconds=_createdAtMilliseconds;
@property(copy, nonatomic) NSString *secondaryKey2; // @synthesize secondaryKey2=_secondaryKey2;
@property(copy, nonatomic) NSString *secondaryKey1; // @synthesize secondaryKey1=_secondaryKey1;
@property(copy, nonatomic) NSString *primaryKey; // @synthesize primaryKey=_primaryKey;
- (void).cxx_destruct;
- (id)description;
- (id)toJson;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)incrementKey:(id)arg1 byAmount:(id)arg2;
- (id)initWithPrimaryKey:(id)arg1 secondaryKey1:(id)arg2 secondaryKey2:(id)arg3;

@end

