//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ALAdEventStatKey : NSObject
{
    NSString *_name;
    NSString *_debugName;
}

+ (id)storeKitPreloadSkipped;
+ (id)storeKitLoadFailure;
+ (id)storeKitRedirected;
+ (id)videoStreamStalledCount;
+ (id)adCancelledHTMLCaching;
+ (id)timeToToggleVideoMute;
+ (id)interstitialVideoMutedInitially;
+ (id)HTMLResourceCacheFailureCount;
+ (id)HTMLResourceCacheSuccessCount;
+ (id)successfullyPersistedWebKitHTMLString;
+ (id)unableToPersistWebKitHTMLPlacementReplacedString;
+ (id)unableToRetrieveWebKitHTMLString;
+ (id)isStreamingWebKit;
+ (id)adShownWithWebKit;
+ (id)interstitialShowPoststitialCodeExecuted;
+ (id)interstitialPausedDuration;
+ (id)interstitialVideoPercentViewed;
+ (id)adUsedGraphicStream;
+ (id)interstitialUsedVideoStream;
+ (id)adShownWithActiveNetwork;
+ (id)timeToContractFromShow;
+ (id)timeToExpandFromShow;
+ (id)timeToClickFromShow;
+ (id)timeToSkipFromShow;
+ (id)optOutButtonClickThroughCount;
+ (id)timeToHiddenFromShow;
+ (id)adNumberTotal;
+ (id)adNumberInSession;
+ (id)timeToDisplayFromInit;
+ (id)timeToDisplayFromLoad;
+ (id)adCachedBytes;
+ (id)adDownloadedBytes;
+ (id)adFetchSize;
+ (id)adFetchTime;
+ (id)adRenderTime;
+ (id)adSource;
+ (id)newStatKey:(id)arg1 debugName:(id)arg2;
+ (void)initialize;
@property(copy, nonatomic) NSString *debugName; // @synthesize debugName=_debugName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 debugName:(id)arg2;

@end

