//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, ALTimer;
@protocol ALAdRefreshManagerDelegate;

@interface ALAdRefreshManager : NSObject
{
    ALSdk *_sdk;
    id <ALAdRefreshManagerDelegate> _delegate;
    long long _refreshTimeMillis;
    ALTimer *_timer;
    NSObject *_timerLock;
}

@property(retain, nonatomic) NSObject *timerLock; // @synthesize timerLock=_timerLock;
@property(retain, nonatomic) ALTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) long long refreshTimeMillis; // @synthesize refreshTimeMillis=_refreshTimeMillis;
@property(nonatomic) __weak id <ALAdRefreshManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)storeKitHidden:(id)arg1;
- (void)storeKitDisplayed:(id)arg1;
- (void)fullScreenAdHidden:(id)arg1;
- (void)fullScreenAdDisplayed:(id)arg1;
- (void)applicationResumed:(id)arg1;
- (void)applicationPaused:(id)arg1;
@property(readonly, nonatomic) double remainingTime; // @dynamic remainingTime;
@property(readonly, nonatomic, getter=isRefreshScheduled) _Bool refreshScheduled; // @dynamic refreshScheduled;
- (void)reset;
- (void)resumeTimer;
- (void)pauseTimer;
- (void)cancelAdRefresh;
- (void)scheduleAdRefreshWithTime:(long long)arg1;
- (void)dealloc;
- (id)initWithSDK:(id)arg1 andNotify:(id)arg2;

@end

