//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALLoadableObject-Protocol.h"
#import "NSCopying-Protocol.h"

@class ALAdSize, ALAdType, ALAdZone, ALDummyAd, ALSdk, NSMutableDictionary, NSNumber, NSString;

@interface ALAd : NSObject <ALLoadableObject, NSCopying>
{
    ALAdZone *_adZone;
    unsigned long long _responseHash;
    ALSdk *_sdk;
    NSObject *_adObjectLock;
    NSMutableDictionary *_adObject;
    NSObject *_fullResponseLock;
    NSMutableDictionary *_fullResponse;
    ALDummyAd *_dummyAd;
    unsigned long long _source;
    long long _createdAtMillis;
}

@property(nonatomic) long long createdAtMillis; // @synthesize createdAtMillis=_createdAtMillis;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(retain, nonatomic) ALDummyAd *dummyAd; // @synthesize dummyAd=_dummyAd;
@property(retain, nonatomic) NSMutableDictionary *fullResponse; // @synthesize fullResponse=_fullResponse;
@property(retain, nonatomic) NSObject *fullResponseLock; // @synthesize fullResponseLock=_fullResponseLock;
@property(retain, nonatomic) NSMutableDictionary *adObject; // @synthesize adObject=_adObject;
@property(retain, nonatomic) NSObject *adObjectLock; // @synthesize adObjectLock=_adObjectLock;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) unsigned long long responseHash; // @synthesize responseHash=_responseHash;
- (void).cxx_destruct;
@property(readonly) unsigned long long hash;
- (_Bool)isEqualToAd:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)objectFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)objectFromFullResponseForKey:(id)arg1;
- (id)dictionaryFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)dictionaryFromFullResponseForKey:(id)arg1;
- (id)arrayFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)arrayFromFullResponseForKey:(id)arg1;
- (id)stringFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)stringFromFullResponseForKey:(id)arg1;
- (id)numberFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)numberFromFullResponseForKey:(id)arg1;
- (long long)integerFromFullResponseForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)integerFromFullResponseForKey:(id)arg1;
- (_Bool)boolFromFullResponseForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)boolFromFullResponseForKey:(id)arg1;
- (_Bool)fullResponseContainsValueForKey:(id)arg1;
- (id)objectFromAdObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)objectFromAdObjectForKey:(id)arg1;
- (id)dictionaryFromAdObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)dictionaryFromAdObjectForKey:(id)arg1;
- (id)arrayFromAdObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)arrayFromAdObjectForKey:(id)arg1;
- (id)stringFromAdObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)stringFromAdObjectForKey:(id)arg1;
- (id)numberFromAdObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)numberFromAdObjectForKey:(id)arg1;
- (long long)integerFromAdObjectForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)integerFromAdObjectForKey:(id)arg1;
- (_Bool)boolFromAdObjectForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)boolFromAdObjectForKey:(id)arg1;
- (_Bool)adObjectContainsValueForKey:(id)arg1;
@property(nonatomic, getter=shouldCancelHTMLCachingIfShown) _Bool cancelHTMLCachingIfShown; // @dynamic cancelHTMLCachingIfShown;
@property(nonatomic, getter=hasShown) _Bool shown; // @dynamic shown;
@property(readonly, nonatomic) NSNumber *fetchResponseSize; // @dynamic fetchResponseSize;
@property(readonly, nonatomic) NSNumber *fetchLatencyMillis; // @dynamic fetchLatencyMillis;
@property(readonly, copy, nonatomic) NSString *secondaryKey2; // @dynamic secondaryKey2;
@property(readonly, copy, nonatomic) NSString *secondaryKey1; // @dynamic secondaryKey1;
@property(readonly, copy, nonatomic) NSString *primaryKey; // @dynamic primaryKey;
@property(readonly, copy, nonatomic) NSString *clcode; // @dynamic clcode;
@property(readonly, nonatomic) ALAdZone *adZone; // @synthesize adZone=_adZone;
- (id)adValueForKey:(id)arg1;
- (_Bool)hasVideoURL;
@property(readonly, getter=isVideoAd) _Bool videoAd; // @dynamic videoAd;
@property(readonly, copy, nonatomic) NSString *zoneIdentifier; // @dynamic zoneIdentifier;
@property(readonly, nonatomic) ALAdType *type; // @dynamic type;
@property(readonly, nonatomic) ALAdSize *size; // @dynamic size;
@property(readonly, nonatomic) NSNumber *adIdNumber; // @dynamic adIdNumber;
- (id)initWithAdObject:(id)arg1 fullResponse:(id)arg2 source:(unsigned long long)arg3 sdk:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

