//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALLogger, ALMediatedFullscreenAd, ALSdk, ALTimer, NSArray, UIViewController;
@protocol ALAdViewControllerObserverDelegate;

@interface ALAdViewControllerObserver : NSObject
{
    ALSdk *_sdk;
    ALLogger *_logger;
    id <ALAdViewControllerObserverDelegate> _delegate;
    ALMediatedFullscreenAd *_currentAd;
    NSArray *_classesToIgnore;
    ALTimer *_timer;
    UIViewController *_adViewController;
}

@property(nonatomic) __weak UIViewController *adViewController; // @synthesize adViewController=_adViewController;
@property(retain, nonatomic) ALTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSArray *classesToIgnore; // @synthesize classesToIgnore=_classesToIgnore;
@property(retain, nonatomic) ALMediatedFullscreenAd *currentAd; // @synthesize currentAd=_currentAd;
@property(nonatomic) __weak id <ALAdViewControllerObserverDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)stop;
- (void)startForAd:(id)arg1 andNotify:(id)arg2;
- (id)initWithSdk:(id)arg1;

@end

