//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALAdLoadDelegate-Protocol.h"

@class ALAdLoadState, ALLogger, ALSdk, NSString;

@interface ALAdServiceLoadProxy : NSObject <ALAdLoadDelegate>
{
    ALSdk *_sdk;
    ALLogger *_logger;
    ALAdLoadState *_loadState;
}

@property(retain, nonatomic) ALAdLoadState *loadState; // @synthesize loadState=_loadState;
@property(retain, nonatomic) ALLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)adService:(id)arg1 didLoadAd:(id)arg2;
- (id)initWithSdk:(id)arg1 loadState:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

