//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface ALAdSize : NSObject <NSCopying>
{
    NSString *_label;
    double _width;
    double _height;
}

+ (void)initialize;
+ (id)allSizes;
+ (id)sizeLeader;
+ (id)sizeMRec;
+ (id)sizeNative;
+ (id)sizeInterstitial;
+ (id)sizeBanner;
+ (id)sizeWithLabel:(id)arg1 orDefault:(id)arg2;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqualToSize:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2;
- (id)initWithLabel:(id)arg1;

@end

