//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface ALAdLoadState : NSObject
{
    _Bool _isWaitingForAd;
    NSObject *_adLoadLock;
    NSMutableSet *_pendingAdLoadDelegates;
}

@property(retain, nonatomic) NSMutableSet *pendingAdLoadDelegates; // @synthesize pendingAdLoadDelegates=_pendingAdLoadDelegates;
@property(nonatomic) _Bool isWaitingForAd; // @synthesize isWaitingForAd=_isWaitingForAd;
@property(retain, nonatomic) NSObject *adLoadLock; // @synthesize adLoadLock=_adLoadLock;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

