//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALDirectAd.h"

@class NSNumber, NSString, NSURL, UIColor;

@interface ALAdServerAd : ALDirectAd
{
    NSString *_rawHTMLSource;
}

@property(copy, nonatomic) NSString *rawHTMLSource; // @synthesize rawHTMLSource=_rawHTMLSource;
- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *cachedHTMLURL; // @dynamic cachedHTMLURL;
@property(readonly, nonatomic) UIColor *expandableBackgroundColor; // @dynamic expandableBackgroundColor;
@property(readonly, nonatomic) unsigned long long expandableAdCloseButtonStyle; // @dynamic expandableAdCloseButtonStyle;
@property(readonly, nonatomic) _Bool expandableAdCloseButtonHidden; // @dynamic expandableAdCloseButtonHidden;
@property(readonly, nonatomic) _Bool closeButtonHidden; // @dynamic closeButtonHidden;
@property(readonly, nonatomic) NSNumber *mraidCloseDelay; // @dynamic mraidCloseDelay;
@property(retain, nonatomic) NSString *htmlSource; // @dynamic htmlSource;
- (void)setVideoURL:(id)arg1;
- (id)videoURL;
- (id)initWithAdObject:(id)arg1 fullResponse:(id)arg2 source:(unsigned long long)arg3 sdk:(id)arg4;

@end

