//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MAAdDelegate-Protocol.h"
#import "MAAdViewAdDelegate-Protocol.h"
#import "MARewardedAdDelegate-Protocol.h"

@class ALSdk, NSString;
@protocol MAAdDelegate;

@interface ALAdDelegateProxy : NSObject <MAAdDelegate, MARewardedAdDelegate, MAAdViewAdDelegate>
{
    id <MAAdDelegate> _delegate;
    ALSdk *_sdk;
}

@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(retain, nonatomic) id <MAAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didCollapseAd:(id)arg1;
- (void)didExpandAd:(id)arg1;
- (void)didRewardUserForAd:(id)arg1 withReward:(id)arg2;
- (void)didCompleteRewardedVideoForAd:(id)arg1;
- (void)didStartRewardedVideoForAd:(id)arg1;
- (void)didFailToDisplayAd:(id)arg1 withErrorCode:(long long)arg2;
- (void)didClickAd:(id)arg1;
- (void)didHideAd:(id)arg1;
- (void)didDisplayAd:(id)arg1;
- (void)didFailToLoadAdForAdUnitIdentifier:(id)arg1 withErrorCode:(long long)arg2;
- (void)didLoadAd:(id)arg1;
- (id)initWithDelegate:(id)arg1 sdk:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

