//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALConnectionManagerDelegate-Protocol.h"
#import "NSObject-Protocol.h"

@class ALTask, NSDictionary, NSMutableDictionary, NSString;

@protocol ALAdFetching <NSObject, ALConnectionManagerDelegate>
@property(readonly, nonatomic) NSMutableDictionary *fetchTaskSpecificParameters;
@property(readonly, copy, nonatomic) NSString *adBackupEndpointDomain;
@property(readonly, copy, nonatomic) NSString *adEndpointDomain;
- (ALTask *)createRenderTaskWithResponse:(NSDictionary *)arg1;
- (void)notifyLoadDelegateOfFailureWithResponseCode:(long long)arg1;

@optional
@property(readonly, nonatomic) unsigned long long source;
@end

