//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALAdLoadDelegate-Protocol.h"
#import "ALAdRewardDelegate-Protocol.h"
#import "ALAdVideoPlaybackDelegate-Protocol.h"
#import "ALInternalAdDisplayDelegate-Protocol.h"

@class ALAppLovinMediationAdapter, MAReward, NSString;
@protocol MARewardedAdapterDelegate;

@interface ALAppLovinMediationAdapterRewardedDelegate : NSObject <ALAdLoadDelegate, ALInternalAdDisplayDelegate, ALAdRewardDelegate, ALAdVideoPlaybackDelegate>
{
    _Bool _fullyWatched;
    ALAppLovinMediationAdapter *_parentAdapter;
    MAReward *_pendingReward;
    id <MARewardedAdapterDelegate> _delegate;
}

@property(retain, nonatomic) id <MARewardedAdapterDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isFullyWatched) _Bool fullyWatched; // @synthesize fullyWatched=_fullyWatched;
@property(retain, nonatomic) MAReward *pendingReward; // @synthesize pendingReward=_pendingReward;
@property(nonatomic) __weak ALAppLovinMediationAdapter *parentAdapter; // @synthesize parentAdapter=_parentAdapter;
- (void).cxx_destruct;
- (void)videoPlaybackEndedInAd:(id)arg1 atPlaybackPercent:(id)arg2 fullyWatched:(_Bool)arg3;
- (void)videoPlaybackBeganInAd:(id)arg1;
- (void)userDeclinedToViewAd:(id)arg1;
- (void)rewardValidationRequestForAd:(id)arg1 didFailWithError:(long long)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 wasRejectedWithResponse:(id)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 didExceedQuotaWithResponse:(id)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 didSucceedWithResponse:(id)arg2;
- (void)ad:(id)arg1 wasClickedIn:(id)arg2;
- (void)ad:(id)arg1 wasHiddenIn:(id)arg2;
- (void)didFailToDisplayAdWithErrorMessage:(id)arg1;
- (void)ad:(id)arg1 wasDisplayedIn:(id)arg2;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)adService:(id)arg1 didLoadAd:(id)arg2;
- (id)initWithParentAdapter:(id)arg1 andNotify:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

