//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALAdLoadDelegate-Protocol.h"
#import "ALInternalAdDisplayDelegate-Protocol.h"

@class ALAppLovinMediationAdapter, NSString;
@protocol MAInterstitialAdapterDelegate;

@interface ALAppLovinMediationAdapterInterstitialDelegate : NSObject <ALAdLoadDelegate, ALInternalAdDisplayDelegate>
{
    ALAppLovinMediationAdapter *_parentAdapter;
    id <MAInterstitialAdapterDelegate> _delegate;
}

@property(retain, nonatomic) id <MAInterstitialAdapterDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak ALAppLovinMediationAdapter *parentAdapter; // @synthesize parentAdapter=_parentAdapter;
- (void).cxx_destruct;
- (void)ad:(id)arg1 wasClickedIn:(id)arg2;
- (void)ad:(id)arg1 wasHiddenIn:(id)arg2;
- (void)didFailToDisplayAdWithErrorMessage:(id)arg1;
- (void)ad:(id)arg1 wasDisplayedIn:(id)arg2;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)adService:(id)arg1 didLoadAd:(id)arg2;
- (id)initWithParentAdapter:(id)arg1 andNotify:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

