//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALMediationAdapter.h"

#import "MAAdViewAdapter-Protocol.h"
#import "MAAdapter-Protocol.h"
#import "MAInterstitialAdapter-Protocol.h"
#import "MARewardedAdapter-Protocol.h"
#import "MASignalProvider-Protocol.h"

@class ALAd, ALAdView, ALIncentivizedInterstitialAd, ALInterstitialAd, NSString;

@interface ALAppLovinMediationAdapter : ALMediationAdapter <MAAdapter, MAAdViewAdapter, MAInterstitialAdapter, MARewardedAdapter, MASignalProvider>
{
    ALAd *_loadedInterstitialAd;
    ALAd *_loadedRewardedAd;
    ALInterstitialAd *_interstitialAd;
    ALIncentivizedInterstitialAd *_rewardedAd;
    ALAdView *_loadedAdView;
}

+ (id)adapterDisplayErrorCodeFromAppLovinErrorCode:(long long)arg1;
+ (id)adapterLoadErrorCodeFromAppLovinErrorCode:(long long)arg1;
@property(retain, nonatomic) ALAdView *loadedAdView; // @synthesize loadedAdView=_loadedAdView;
@property(retain, nonatomic) ALIncentivizedInterstitialAd *rewardedAd; // @synthesize rewardedAd=_rewardedAd;
@property(retain, nonatomic) ALInterstitialAd *interstitialAd; // @synthesize interstitialAd=_interstitialAd;
@property(retain, nonatomic) ALAd *loadedRewardedAd; // @synthesize loadedRewardedAd=_loadedRewardedAd;
@property(retain, nonatomic) ALAd *loadedInterstitialAd; // @synthesize loadedInterstitialAd=_loadedInterstitialAd;
- (void).cxx_destruct;
- (void)collectSignalWithParameters:(id)arg1 andNotify:(id)arg2;
- (void)showRewardedAdForParameters:(id)arg1 andNotify:(id)arg2;
- (void)loadRewardedAdForParameters:(id)arg1 andNotify:(id)arg2;
- (void)showInterstitialAdForParameters:(id)arg1 andNotify:(id)arg2;
- (void)loadInterstitialAdForParameters:(id)arg1 andNotify:(id)arg2;
- (void)loadAdViewAdForParameters:(id)arg1 adFormat:(id)arg2 andNotify:(id)arg3;
- (void)destroy;
- (void)initializeWithParameters:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)initializeWithParameters:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
@property(readonly, copy, nonatomic) NSString *adapterVersion;
@property(readonly, copy, nonatomic) NSString *SDKVersion;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

