//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALBaseVideoViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class ALAdServerAd, NSArray, NSString, UITapGestureRecognizer;

@interface ALAppLovinVideoViewController : ALBaseVideoViewController <UIGestureRecognizerDelegate>
{
    UITapGestureRecognizer *_closeRecognizer;
    NSArray *_currentSkipAndCloseButtonConstraints;
    NSArray *_currentOptOutButtonConstraints;
}

@property(retain, nonatomic) NSArray *currentOptOutButtonConstraints; // @synthesize currentOptOutButtonConstraints=_currentOptOutButtonConstraints;
@property(retain, nonatomic) NSArray *currentSkipAndCloseButtonConstraints; // @synthesize currentSkipAndCloseButtonConstraints=_currentSkipAndCloseButtonConstraints;
@property(retain, nonatomic) UITapGestureRecognizer *closeRecognizer; // @synthesize closeRecognizer=_closeRecognizer;
- (void).cxx_destruct;
@property(readonly, nonatomic) ALAdServerAd *currentAd;
@property(readonly, nonatomic, getter=isIncentivizedNonVideoAdFullyEngaged) _Bool incentivizedNonVideoAdFullyEngaged; // @dynamic incentivizedNonVideoAdFullyEngaged;
@property(readonly, nonatomic) unsigned long long incentivizedNonVideoAdPercentEngaged; // @dynamic incentivizedNonVideoAdPercentEngaged;
@property(readonly, nonatomic, getter=shouldWarnIncentivizedNonVideoAdClose) _Bool warnIncentivizedNonVideoAdClose; // @dynamic warnIncentivizedNonVideoAdClose;
- (_Bool)closeButtonHidden;
- (void)showPoststitial;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleExtendedCloseAreaTouch:(id)arg1;
- (void)prepareAdditionalTouchAreaIfNeeded;
- (void)prepareBufferIndicatorIfNeeded;
- (void)prepareVideoButtonIfNeeded;
- (void)prepareVideoProgressBar;
- (void)prepareCountdownClock;
- (void)updateConstraintsForSkipAndCloseButtons;
- (void)updateConstraintsForOptOutButton;
- (void)prepareInterface;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)dismiss;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithSdk:(id)arg1 currentAd:(id)arg2 wrapper:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

