//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface ALArrayDictionary : NSObject <NSCoding>
{
    NSMutableDictionary *_dict;
    NSMutableArray *_keys;
    NSObject *_lock;
}

+ (id)orderedDictionaryWithCapacity:(unsigned long long)arg1;
+ (id)orderedDictionary;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableArray *keys; // @synthesize keys=_keys;
@property(retain, nonatomic) NSMutableDictionary *dict; // @synthesize dict=_dict;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *allValues; // @dynamic allValues;
@property(readonly, copy, nonatomic) NSArray *allKeys; // @dynamic allKeys;
@property(readonly, nonatomic) unsigned long long count; // @dynamic count;
- (_Bool)shouldRemoveEldestKey:(id)arg1 object:(id)arg2;
- (void)removeAllObjects;
- (void)removeObjectsForKeys:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)addEntriesFromDictionary:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)init;

@end

