//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALLogger, ALSdk, NSMutableDictionary, NSSet;

@interface ALBasePreloadManager : NSObject
{
    ALSdk *_sdk;
    NSObject *_preloadedAdsLock;
    NSMutableDictionary *_preloadedAds;
    NSMutableDictionary *_extendedPreloadedAds;
    NSMutableDictionary *_additionalDelegates;
    NSSet *_completedInitialPreloads;
}

@property(retain, nonatomic) NSSet *completedInitialPreloads; // @synthesize completedInitialPreloads=_completedInitialPreloads;
@property(retain, nonatomic) NSMutableDictionary *additionalDelegates; // @synthesize additionalDelegates=_additionalDelegates;
@property(retain, nonatomic) NSMutableDictionary *extendedPreloadedAds; // @synthesize extendedPreloadedAds=_extendedPreloadedAds;
@property(retain, nonatomic) NSMutableDictionary *preloadedAds; // @synthesize preloadedAds=_preloadedAds;
@property(retain, nonatomic) NSObject *preloadedAdsLock; // @synthesize preloadedAdsLock=_preloadedAdsLock;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (id)initWithSdk:(id)arg1;
@property(readonly, nonatomic) ALLogger *logger; // @dynamic logger;
- (id)extendedAdQueueForZone:(id)arg1;
- (id)adQueueForZone:(id)arg1;
- (_Bool)registerForInitialPreloadCallback:(id)arg1 forZone:(id)arg2;
- (void)registerForPreloadCallback:(id)arg1 forZone:(id)arg2;
- (_Bool)isInitialPreloadCompletedForZone:(id)arg1;
- (void)didFailToReceiveLoadableWithZone:(id)arg1 error:(long long)arg2;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)didReceiveLoadable:(id)arg1;
- (void)removeInvalidMergedDelegatesFromLoadedZones:(id)arg1;
- (_Bool)hasMergedDelegateForZone:(id)arg1;
- (id)loadedQueueForZone:(id)arg1;
- (id)peekNextPreloadedAdOfZone:(id)arg1;
- (id)dequeuePreloadedAdOfZone:(id)arg1;
- (id)preloadedAdOfZone:(id)arg1;
- (void)createOrUpdatePreloadQueuesIfNeededForZone:(id)arg1;
- (void)fillPreloadQueueForZone:(id)arg1 count:(unsigned long long)arg2;
- (void)fillPreloadQueueForZone:(id)arg1;
- (void)preloadNextAdOfZoneIfNeeded:(id)arg1;
- (_Bool)hasFullPreloadQueueForZone:(id)arg1;
- (_Bool)hasPreloadedAdOfZone:(id)arg1;

@end

