//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface ALBaseOptOutButtonConfiguration : NSObject
{
    NSDictionary *_configObject;
}

@property(retain, nonatomic) NSDictionary *configObject; // @synthesize configObject=_configObject;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *defaultVerticalConstraint; // @dynamic defaultVerticalConstraint;
@property(readonly, copy, nonatomic) NSString *defaultHorizontalConstraint; // @dynamic defaultHorizontalConstraint;
@property(readonly, copy, nonatomic) NSString *landscapeVerticalConstraint; // @dynamic landscapeVerticalConstraint;
@property(readonly, copy, nonatomic) NSString *landscapeHorizontalConstraint; // @dynamic landscapeHorizontalConstraint;
@property(readonly, copy, nonatomic) NSString *portraitVerticalConstraint; // @dynamic portraitVerticalConstraint;
@property(readonly, copy, nonatomic) NSString *portraitHorizontalConstraint; // @dynamic portraitHorizontalConstraint;
- (id)constraintsForIsPortraitOrientation:(_Bool)arg1;
- (id)initWithConfigurationObject:(id)arg1;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *defaultHorizontalConstraintValue; // @dynamic defaultHorizontalConstraintValue;
@property(readonly, copy, nonatomic) NSString *defaultVerticalConstraintValue; // @dynamic defaultVerticalConstraintValue;

@end

