//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@interface ALBlockTask : ALTask
{
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (id)key;
- (void)run;
- (id)initWithSdk:(id)arg1 runWhileInitializing:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
- (id)initWithSdk:(id)arg1 block:(CDUnknownBlockType)arg2;

@end

