//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALCacheStatsTracker : NSObject
{
    _Bool _HTMLCachingCancelled;
    _Bool _successfullyPersistedWebKitHTMLString;
    long long _totalDownloadedBytes;
    long long _totalCachedBytes;
    long long _HTMLResourceCacheSuccessCount;
    long long _HTMLResourceCacheFailureCount;
}

@property(nonatomic) _Bool successfullyPersistedWebKitHTMLString; // @synthesize successfullyPersistedWebKitHTMLString=_successfullyPersistedWebKitHTMLString;
@property(nonatomic) long long HTMLResourceCacheFailureCount; // @synthesize HTMLResourceCacheFailureCount=_HTMLResourceCacheFailureCount;
@property(nonatomic) long long HTMLResourceCacheSuccessCount; // @synthesize HTMLResourceCacheSuccessCount=_HTMLResourceCacheSuccessCount;
@property(nonatomic, getter=isHTMLCachingCancelled) _Bool HTMLCachingCancelled; // @synthesize HTMLCachingCancelled=_HTMLCachingCancelled;
@property(nonatomic) long long totalCachedBytes; // @synthesize totalCachedBytes=_totalCachedBytes;
@property(nonatomic) long long totalDownloadedBytes; // @synthesize totalDownloadedBytes=_totalDownloadedBytes;
- (id)description;
- (void)trackWebKitSuccessfullyCachedHTMLResources:(_Bool)arg1;
- (void)incrementHTMLResourceCacheFailureCount;
- (void)incrementHTMLResourceCacheSuccessCount;
- (void)trackHTMLCachingCancelled;
- (void)trackCachedBytes:(long long)arg1;
- (void)trackDownloadedBytes:(long long)arg1;

@end

