//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALConsentDialogManager, ALSdk, ALTimer;
@protocol ALConsentAlertManagerDelegate;

@interface ALConsentAlertManager : NSObject
{
    ALSdk *_sdk;
    ALConsentDialogManager *_parentConsentDialogManager;
    id <ALConsentAlertManagerDelegate> _delegate;
    ALTimer *_timer;
}

+ (void)initialize;
@property(retain, nonatomic) ALTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak id <ALConsentAlertManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak ALConsentDialogManager *parentConsentDialogManager; // @synthesize parentConsentDialogManager=_parentConsentDialogManager;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)applicationResumed:(id)arg1;
- (void)applicationPaused:(id)arg1;
- (void)scheduleShowWithTimeIntervalMillis:(long long)arg1 sdk:(id)arg2 andNotify:(id)arg3;
- (void)dealloc;
- (id)initWithParentConsentDialogManager:(id)arg1;

@end

