//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALConsentAlertManagerDelegate-Protocol.h"
#import "ALWebViewViewControllerDelegate-Protocol.h"

@class ALConsentAlertManager, ALLogger, ALSdk, ALWebViewViewController, NSString;

@interface ALConsentDialogManager : NSObject <ALWebViewViewControllerDelegate, ALConsentAlertManagerDelegate>
{
    ALSdk *_sdk;
    ALLogger *_logger;
    CDUnknownBlockType _completionHandler;
    ALWebViewViewController *_webViewViewController;
    ALConsentAlertManager *_consentAlertManager;
}

@property(retain, nonatomic) ALConsentAlertManager *consentAlertManager; // @synthesize consentAlertManager=_consentAlertManager;
@property(retain, nonatomic) ALWebViewViewController *webViewViewController; // @synthesize webViewViewController=_webViewViewController;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)dismissAndCleanup;
- (_Bool)canDisplayConsentDialogForSdk:(id)arg1;
@property(readonly, nonatomic, getter=isConsentDialogShowing) _Bool consentDialogShowing; // @dynamic consentDialogShowing;
- (void)userDidReject;
- (void)userDidAccept;
- (void)webViewViewController:(id)arg1 didReceiveEvent:(id)arg2;
- (void)scheduleConsentAlertWithTimeIntervalMillis:(long long)arg1;
- (void)showConsentDialogIfNeededWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithSdk:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

