//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALLogger, ALRequestMeasurement, ALSdk;

@interface ALConnectionManager : NSObject
{
    ALRequestMeasurement *_lastRequestMeasurement;
    ALSdk *_sdk;
}

@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(retain, nonatomic) ALRequestMeasurement *lastRequestMeasurement; // @synthesize lastRequestMeasurement=_lastRequestMeasurement;
- (void).cxx_destruct;
@property(readonly, nonatomic) ALLogger *logger; // @dynamic logger;
- (id)responseObjectFromData:(id)arg1 withEmptyResponse:(id)arg2 error:(id *)arg3;
- (void)sendURLRequest:(id)arg1 withEmptyResponse:(id)arg2 statsTracker:(id)arg3 decodeResponse:(_Bool)arg4 trackConnectionSpeed:(_Bool)arg5 andNotify:(id)arg6;
- (void)sendRequest:(id)arg1 statsTracker:(id)arg2 andNotify:(id)arg3;
- (id)initWithSdk:(id)arg1;

@end

