//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALConnectionStatsTracker : NSObject
{
    long long _latencyMillis;
    long long _responseSize;
}

@property(nonatomic) long long responseSize; // @synthesize responseSize=_responseSize;
@property(nonatomic) long long latencyMillis; // @synthesize latencyMillis=_latencyMillis;
- (id)init;

@end

