//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALConnectionUtils : NSObject
{
}

+ (_Bool)isCleartextTrafficPermitted;
+ (id)enforceSSLIfNeededForURLString:(id)arg1 usingSDK:(id)arg2;
+ (id)networkType;
+ (void)handleApiError:(long long)arg1 fromSdk:(id)arg2;
+ (void)updateVariablesFromResponse:(id)arg1 forSDK:(id)arg2;
+ (void)updateZonesFromResponse:(id)arg1 forSDK:(id)arg2;
+ (void)updateSettingsForResponse:(id)arg1 forSDK:(id)arg2;
+ (void)updatePersistedDataFromFullResponse:(id)arg1 usingSdk:(id)arg2;
+ (id)apiResultFrom:(id)arg1;
+ (id)secureEndpointForUrl:(id)arg1;
+ (id)urlForDomain:(id)arg1 endpoint:(id)arg2 with:(id)arg3;
+ (id)backupAdServerUrl:(id)arg1 with:(id)arg2;
+ (id)backupAPIUrl:(id)arg1 with:(id)arg2;
+ (id)adServerUrl:(id)arg1 with:(id)arg2;
+ (id)APIParametersForSdk:(id)arg1;
+ (id)APIUrl:(id)arg1 with:(id)arg2;

@end

