//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ALDAppTransportSecuritySettings : NSObject
{
    _Bool _cleartextTraffic;
    _Bool _cleartextTrafficPermitted;
    NSString *_info;
}

@property(copy, nonatomic) NSString *info; // @synthesize info=_info;
@property(nonatomic, getter=isCleartextTrafficPermitted) _Bool cleartextTrafficPermitted; // @synthesize cleartextTrafficPermitted=_cleartextTrafficPermitted;
@property(nonatomic, getter=hasCleartextTraffic) _Bool cleartextTraffic; // @synthesize cleartextTraffic=_cleartextTraffic;
- (void).cxx_destruct;
- (id)initWithConfigurationObject:(id)arg1;

@end

