//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MAAdViewAdapterDelegate-Protocol.h"
#import "MAInterstitialAdapterDelegate-Protocol.h"
#import "MARewardedAdapterDelegate-Protocol.h"

@class ALLogger, ALMediationAdapterWrapper, NSString;
@protocol MAInternalAdDelegate><MARewardedAdDelegate><MAAdViewAdDelegate;

@interface ALDelegateWrapper : NSObject <MAInterstitialAdapterDelegate, MARewardedAdapterDelegate, MAAdViewAdapterDelegate>
{
    ALMediationAdapterWrapper *_parentAdapterWrapper;
    ALLogger *_logger;
    id <MAInternalAdDelegate><MARewardedAdDelegate><MAAdViewAdDelegate> _delegate;
}

@property(retain, nonatomic) id <MAInternalAdDelegate><MARewardedAdDelegate><MAAdViewAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALMediationAdapterWrapper *parentAdapterWrapper; // @synthesize parentAdapterWrapper=_parentAdapterWrapper;
- (void).cxx_destruct;
- (id)toErrorString:(id)arg1;
- (void)callSafeWithTag:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)didFailToDisplayAdViewAdWithError:(id)arg1;
- (void)didCollapseAdViewAd;
- (void)didExpandAdViewAd;
- (void)didHideAdViewAd;
- (void)didClickAdViewAd;
- (void)didDisplayAdViewAd;
- (void)didFailToLoadAdViewAdWithError:(id)arg1;
- (void)didLoadAdForAdView:(id)arg1;
- (void)didFailToDisplayRewardedAdWithError:(id)arg1;
- (void)didCompleteRewardedAdVideo;
- (void)didStartRewardedAdVideo;
- (void)didRewardUserWithReward:(id)arg1;
- (void)didHideRewardedAd;
- (void)didClickRewardedAd;
- (void)didDisplayRewardedAd;
- (void)didFailToLoadRewardedAdWithError:(id)arg1;
- (void)didLoadRewardedAd;
- (void)didFailToDisplayInterstitialAdWithError:(id)arg1;
- (void)didHideInterstitialAd;
- (void)didClickInterstitialAd;
- (void)didDisplayInterstitialAd;
- (void)didFailToLoadInterstitialAdWithError:(id)arg1;
- (void)didLoadInterstitialAd;
- (void)processAdDisplayFailedWithTag:(id)arg1 code:(long long)arg2 errorString:(id)arg3;
- (void)processAdDisplayFailedWithTag:(id)arg1 error:(id)arg2;
- (void)processAdDisplayFailedWithTag:(id)arg1 code:(long long)arg2;
- (void)processAdDisplayedWithTag:(id)arg1;
- (void)processAdLoadFailedWithTag:(id)arg1 error:(id)arg2;
- (void)processAdLoadFailedWithTag:(id)arg1 code:(long long)arg2;
- (void)processAdLoadFailedWithTag:(id)arg1 code:(long long)arg2 errorString:(id)arg3;
- (void)processAdLoadSuccessWithTag:(id)arg1;
- (id)initWithParentAdapterWrapper:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

