//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALPostbackDelegate-Protocol.h"

@class NSString;
@protocol ALPostbackDelegate;

@interface ALDispatchPostbackDelegate : NSObject <ALPostbackDelegate>
{
    CDUnknownBlockType _completionBlock;
    id <ALPostbackDelegate> _originalDelegate;
}

@property(retain, nonatomic) id <ALPostbackDelegate> originalDelegate; // @synthesize originalDelegate=_originalDelegate;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)postbackService:(id)arg1 didFailToExecutePostback:(id)arg2 errorCode:(long long)arg3;
- (void)postbackService:(id)arg1 didExecutePostback:(id)arg2;
- (id)initWithOriginalDelegate:(id)arg1 andCompletionBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

