//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALDMediatedNetwork, NSAttributedString;

@interface ALDMediationDebuggerCellViewModel : NSObject
{
    ALDMediatedNetwork *_network;
    NSAttributedString *_text;
    NSAttributedString *_detailText;
}

+ (id)viewModelFromMediatedNetwork:(id)arg1;
@property(copy, nonatomic) NSAttributedString *detailText; // @synthesize detailText=_detailText;
@property(copy, nonatomic) NSAttributedString *text; // @synthesize text=_text;
@property(retain, nonatomic) ALDMediatedNetwork *network; // @synthesize network=_network;
- (void).cxx_destruct;
- (id)description;
- (id)attributesDictForColor:(id)arg1 fontSize:(double)arg2;
- (id)attributesDictForColor:(id)arg1;
- (id)configurationString;
- (id)adapterString;
- (id)sdkString;
@property(readonly, nonatomic) long long accessoryType;
@property(readonly, nonatomic) long long detailTextNumberOfLines;
- (id)initWithMediatedNetwork:(id)arg1;

@end

