//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALDAppTransportSecuritySettings, NSArray, NSString;

@interface ALDMediatedNetwork : NSObject
{
    _Bool _SDKAvailable;
    _Bool _adapterAvailable;
    long long _status;
    NSString *_name;
    NSString *_SDKVersion;
    NSString *_adapterVersion;
    NSString *_forceAdNetworkCode;
    NSArray *_supportedAdFormats;
    NSArray *_permissions;
    ALDAppTransportSecuritySettings *_appTransportSecuritySettings;
}

@property(retain, nonatomic) ALDAppTransportSecuritySettings *appTransportSecuritySettings; // @synthesize appTransportSecuritySettings=_appTransportSecuritySettings;
@property(retain, nonatomic) NSArray *permissions; // @synthesize permissions=_permissions;
@property(retain, nonatomic) NSArray *supportedAdFormats; // @synthesize supportedAdFormats=_supportedAdFormats;
@property(copy, nonatomic) NSString *forceAdNetworkCode; // @synthesize forceAdNetworkCode=_forceAdNetworkCode;
@property(copy, nonatomic) NSString *adapterVersion; // @synthesize adapterVersion=_adapterVersion;
@property(copy, nonatomic) NSString *SDKVersion; // @synthesize SDKVersion=_SDKVersion;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic, getter=isAdapterAvailable) _Bool adapterAvailable; // @synthesize adapterAvailable=_adapterAvailable;
@property(nonatomic, getter=isSDKAvailable) _Bool SDKAvailable; // @synthesize SDKAvailable=_SDKAvailable;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)description;
- (id)permissionsFromConfigurationObject:(id)arg1;
- (id)supportedAdFormatsForAdapter:(id)arg1;
- (long long)determineStatus;
- (id)initWithNetworkObject:(id)arg1 sdk:(id)arg2;

@end

