//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class ALDNetworkDetailCellViewModel, UIImageView, UILabel;

@interface ALDNetworkDetailTableViewCell : UITableViewCell
{
    UILabel *textLabel;
    UILabel *detailTextLabel;
    ALDNetworkDetailCellViewModel *_viewModel;
    UIImageView *_iconView;
}

@property(nonatomic) __weak UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) ALDNetworkDetailCellViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak UILabel *detailTextLabel; // @synthesize detailTextLabel;
@property(nonatomic) __weak UILabel *textLabel; // @synthesize textLabel;
- (void).cxx_destruct;

@end

