//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ALDNetworkPermission : NSObject
{
    _Bool _available;
    NSString *_name;
    NSString *_info;
}

@property(nonatomic, getter=isAvailable) _Bool available; // @synthesize available=_available;
@property(copy, nonatomic) NSString *info; // @synthesize info=_info;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 info:(id)arg2;

@end

