//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALAd.h"

#import "NSCopying-Protocol.h"

@class ALAdZone;

@interface ALDummyAd : ALAd <NSCopying>
{
    ALAd *_renderedAd;
    ALAdZone *_initialZone;
    ALAd *_returnedNextPreloadedAd;
}

+ (id)adWithZone:(id)arg1 sdk:(id)arg2;
@property(retain, nonatomic) ALAd *returnedNextPreloadedAd; // @synthesize returnedNextPreloadedAd=_returnedNextPreloadedAd;
@property(retain, nonatomic) ALAdZone *initialZone; // @synthesize initialZone=_initialZone;
@property(nonatomic) __weak ALAd *renderedAd; // @synthesize renderedAd=_renderedAd;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)publisherZoneIdentifier;
- (id)debugDescription;
@property(readonly, nonatomic) ALAd *effectiveAd; // @dynamic effectiveAd;
@property(readonly, nonatomic) ALAd *nextPreloadedAd; // @dynamic nextPreloadedAd;
- (_Bool)isVideoAd;
- (id)zoneIdentifier;
- (id)type;
- (id)size;
- (id)adIdNumber;
- (unsigned long long)source;
- (id)adZone;

@end

