//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, NSArray, NSMutableArray;

@interface ALErrorManager : NSObject
{
    ALSdk *_sdk;
    NSMutableArray *_errorLogs;
    NSObject *_errorsLock;
}

@property(retain, nonatomic) NSObject *errorsLock; // @synthesize errorsLock=_errorsLock;
@property(retain, nonatomic) NSMutableArray *errorLogs; // @synthesize errorLogs=_errorLogs;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *errors; // @dynamic errors;
- (void)persistAll;
- (void)clearAll;
- (void)loadAll;
- (void)reportErrorMessage:(id)arg1 exception:(id)arg2;
- (id)initWithSdk:(id)arg1;

@end

