//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface ALErrorLog : NSObject <NSCoding>
{
    long long _timestampMillis;
    NSString *_message;
    NSString *_exceptionName;
    NSString *_exceptionReason;
}

@property(copy, nonatomic) NSString *exceptionReason; // @synthesize exceptionReason=_exceptionReason;
@property(copy, nonatomic) NSString *exceptionName; // @synthesize exceptionName=_exceptionName;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) long long timestampMillis; // @synthesize timestampMillis=_timestampMillis;
- (void).cxx_destruct;
- (id)description;
- (id)toJSON;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMessage:(id)arg1 exception:(id)arg2;

@end

