//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALSdk, NSDictionary, NSMutableDictionary, NSString;

@interface ALEventService : NSObject
{
    ALSdk *_sdk;
    NSMutableDictionary *_backingSuperProperties;
    ALAtomicBoolean *_appOpenEventTracked;
}

@property(retain, nonatomic) ALAtomicBoolean *appOpenEventTracked; // @synthesize appOpenEventTracked=_appOpenEventTracked;
@property(retain, nonatomic) NSMutableDictionary *backingSuperProperties; // @synthesize backingSuperProperties=_backingSuperProperties;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (id)description;
@property(readonly, copy, nonatomic) NSString *eventTrackingBackupEndpoint; // @dynamic eventTrackingBackupEndpoint;
@property(readonly, copy, nonatomic) NSString *eventTrackingEndpoint; // @dynamic eventTrackingEndpoint;
@property(readonly, copy, nonatomic) NSDictionary *superProperties; // @dynamic superProperties;
- (void)persistSuperPropertiesIfNeeded;
- (id)queryParametersForEvent:(id)arg1;
- (void)trackEvent:(id)arg1 parameters:(id)arg2 HTTPHeaders:(id)arg3 persistent:(_Bool)arg4;
- (void)trackEvent:(id)arg1 persistent:(_Bool)arg2;
- (void)trackEvent:(id)arg1 parameters:(id)arg2;
- (void)trackEvent:(id)arg1;
- (void)trackCheckoutWithTransactionIdentifier:(id)arg1 parameters:(id)arg2;
- (void)trackInAppPurchaseWithTransactionIdentifier:(id)arg1 parameters:(id)arg2;
- (void)setSuperProperty:(id)arg1 forKey:(id)arg2;
- (void)trackAppOpenEventIfNeeded;
- (id)initWithSdk:(id)arg1;

@end

