//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIWebViewDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"

@class ALAdEventStatsManagerHelper, ALAdServerAd, ALAdView, ALExitButton, ALLogger, ALSdk, NSArray, NSString, UIWindow;
@protocol ALWebView;

@interface ALExpandedAdView : UIView <UIWebViewDelegate, WKNavigationDelegate>
{
    _Bool _attachedToWindow;
    _Bool _statusBarOriginallyHidden;
    ALSdk *_sdk;
    ALLogger *_logger;
    UIWindow *_window;
    ALAdServerAd *_ad;
    ALAdView *_container;
    ALAdEventStatsManagerHelper *_statsManagerHelper;
    NSArray *_windowConstraints;
    UIView<ALWebView> *_expandedWebView;
    ALExitButton *_closeButton;
}

@property(retain, nonatomic) ALExitButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak UIView<ALWebView> *expandedWebView; // @synthesize expandedWebView=_expandedWebView;
@property(nonatomic) _Bool statusBarOriginallyHidden; // @synthesize statusBarOriginallyHidden=_statusBarOriginallyHidden;
@property(retain, nonatomic) NSArray *windowConstraints; // @synthesize windowConstraints=_windowConstraints;
@property(nonatomic) _Bool attachedToWindow; // @synthesize attachedToWindow=_attachedToWindow;
@property(retain, nonatomic) ALAdEventStatsManagerHelper *statsManagerHelper; // @synthesize statsManagerHelper=_statsManagerHelper;
@property(retain, nonatomic) ALAdView *container; // @synthesize container=_container;
@property(retain, nonatomic) ALAdServerAd *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) ALLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
@property(readonly, nonatomic) struct CGRect closeButtonFrame; // @dynamic closeButtonFrame;
- (void)createCloseButton:(unsigned long long)arg1;
- (void)showCloseButton;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)detach;
- (void)dismiss;
- (void)dismissFromCloseButton;
- (void)attachToWindow;
- (void)layoutSubviews;
- (void)addFullScreenSubview:(id)arg1;
- (void)expand;
- (id)initWithAd:(id)arg1 container:(id)arg2 window:(id)arg3 statsHelper:(id)arg4 sdk:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

