//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALLogger, ALSdk, NSArray;

@interface ALFileManager : NSObject
{
    ALSdk *_sdk;
    NSObject *_fileSystemLock;
}

@property(retain) NSObject *fileSystemLock; // @synthesize fileSystemLock=_fileSystemLock;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
@property(readonly) __weak NSArray *allCachedFilePaths; // @dynamic allCachedFilePaths;
@property(readonly) __weak ALLogger *logger; // @dynamic logger;
- (id)initWithSdk:(id)arg1;
- (id)allCachedFileNames;
- (_Bool)hasCachedResourceNamed:(id)arg1 inTemporaryDirectory:(_Bool)arg2;
- (id)resourceAtPath:(id)arg1;
- (_Bool)resourceExistAtPath:(id)arg1;
- (id)fileSizeForResourceNamed:(id)arg1 useTemporaryDirectory:(_Bool)arg2;
- (id)urlForResourceNamed:(id)arg1;
- (id)urlStringForResourceNamed:(id)arg1 useTemporaryDirectory:(_Bool)arg2;
- (id)urlStringForResourceNamed:(id)arg1;
- (id)filePathForResourceNamed:(id)arg1 useTemporaryDirectory:(_Bool)arg2;
- (id)filePathForResourceNamed:(id)arg1;
- (_Bool)removeExistingFileAtPath:(id)arg1;
- (_Bool)removeExistingFileNamed:(id)arg1;
- (_Bool)cacheResourceWithData:(id)arg1 atURL:(id)arg2;
- (_Bool)cacheResourceWithData:(id)arg1 named:(id)arg2 useTemporaryDirectory:(_Bool)arg3;
- (id)cacheHTMLString:(id)arg1 useTemporaryDirectory:(_Bool)arg2;
- (unsigned long long)bytesToMegabytes:(unsigned long long)arg1;
- (void)dropCache;
- (void)dropCacheIfRequired:(unsigned long long)arg1;
- (unsigned long long)cacheSizeAfterDroppingExpiredFiles;
- (void)compactCache;
@property(readonly) unsigned long long maximumCacheSize; // @dynamic maximumCacheSize;
@property(readonly) unsigned long long fileTTL; // @dynamic fileTTL;

@end

