//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALSdk;

@interface ALFullScreenAdTracker : NSObject
{
    _Bool _fullscreenAdPendingDisplay;
    ALSdk *_sdk;
    ALAtomicBoolean *_adShowing;
    double _fullscreenAdDisplayedTimestamp;
    NSObject *_fullscreenAdPendingDisplayLock;
    double _fullscreenAdPendingDisplayTimestamp;
}

@property(nonatomic) double fullscreenAdPendingDisplayTimestamp; // @synthesize fullscreenAdPendingDisplayTimestamp=_fullscreenAdPendingDisplayTimestamp;
@property(retain, nonatomic) NSObject *fullscreenAdPendingDisplayLock; // @synthesize fullscreenAdPendingDisplayLock=_fullscreenAdPendingDisplayLock;
@property(nonatomic) double fullscreenAdDisplayedTimestamp; // @synthesize fullscreenAdDisplayedTimestamp=_fullscreenAdDisplayedTimestamp;
@property(retain, nonatomic) ALAtomicBoolean *adShowing; // @synthesize adShowing=_adShowing;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic, getter=isFullscreenAdPendingDisplay) _Bool fullscreenAdPendingDisplay; // @synthesize fullscreenAdPendingDisplay=_fullscreenAdPendingDisplay;
- (void).cxx_destruct;
- (void)setFullScreenAdHidden;
- (void)setFullScreenAdDisplayed;
@property(readonly, nonatomic, getter=isFullScreenAdShowing) _Bool fullScreenAdShowing; // @dynamic fullScreenAdShowing;
- (id)initWithSdk:(id)arg1;

@end

