//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, NSMutableDictionary, NSString;

@interface ALGlobalStatsManager : NSObject
{
    NSMutableDictionary *_stats;
    ALSdk *_sdk;
    NSString *_statsKey;
}

@property(copy, nonatomic) NSString *statsKey; // @synthesize statsKey=_statsKey;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(retain) NSMutableDictionary *stats; // @synthesize stats=_stats;
- (void).cxx_destruct;
- (void)persistAll;
- (id)valueOfKey:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)incrementKey:(id)arg1;
- (void)clearStatsAfterSuccessfulSubmission;
- (void)clearAll;
- (void)clearKey:(id)arg1;
- (void)loadAll;
- (id)initWithSdk:(id)arg1;

@end

