//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ALGlobalStatKey : NSObject
{
    NSString *_name;
}

+ (id)mediationWaterfallAdInvalidResponse;
+ (id)mediationWaterfallAdAdapterLoadFailed;
+ (id)mediationWaterfallAdNoFill;
+ (id)mediationAdResponseProcessFailures;
+ (id)mediatedAdRequested;
+ (id)adRenderedWithMismatchedSdkKey;
+ (id)fullscreenAdFailedToRetrieveViewControllerFromWindowCount;
+ (id)timesPausedAndResumedApp;
+ (id)incentAdFailedToDisplayCount;
+ (id)responseProcessFailures;
+ (id)adResponseProcessFailures;
+ (id)sdkResetStateCount;
+ (id)cacheDropped;
+ (id)filesExpired;
+ (id)sessionAdDisplayed;
+ (id)sessionStart;
+ (id)adDisplayed;
+ (id)adRequested;
+ (id)keysToClearOnSuccessfulSubmission;
+ (id)newStatKey:(id)arg1 clearOnSuccessfulSubmission:(_Bool)arg2;
+ (id)newStatKey:(id)arg1;
+ (void)initialize;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1;

@end

