//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface ALHTTPRequest : NSObject <NSCoding, NSCopying>
{
    _Bool _requiresResponse;
    _Bool _encodingEnabled;
    _Bool _trackConnectionSpeed;
    NSString *_endpoint;
    NSString *_HTTPMethod;
    NSDictionary *_parameters;
    NSDictionary *_HTTPHeaders;
    NSDictionary *_body;
    NSString *_backupEndpoint;
    id _emptyResponse;
    unsigned long long _retryAttemptsLeft;
    double _timeoutSec;
    double _retryDelaySec;
    NSString *_tag;
    unsigned long long _initialRetryAttempts;
}

+ (id)requestWithBuilderBlock:(CDUnknownBlockType)arg1 sdk:(id)arg2;
@property(nonatomic) unsigned long long initialRetryAttempts; // @synthesize initialRetryAttempts=_initialRetryAttempts;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(nonatomic, getter=shouldTrackConnectionSpeed) _Bool trackConnectionSpeed; // @synthesize trackConnectionSpeed=_trackConnectionSpeed;
@property(nonatomic, getter=isEncodingEnabled) _Bool encodingEnabled; // @synthesize encodingEnabled=_encodingEnabled;
@property(nonatomic) double retryDelaySec; // @synthesize retryDelaySec=_retryDelaySec;
@property(nonatomic) double timeoutSec; // @synthesize timeoutSec=_timeoutSec;
@property unsigned long long retryAttemptsLeft; // @synthesize retryAttemptsLeft=_retryAttemptsLeft;
@property(nonatomic) _Bool requiresResponse; // @synthesize requiresResponse=_requiresResponse;
@property(retain, nonatomic) id emptyResponse; // @synthesize emptyResponse=_emptyResponse;
@property(copy, nonatomic) NSString *backupEndpoint; // @synthesize backupEndpoint=_backupEndpoint;
@property(retain, nonatomic) NSDictionary *body; // @synthesize body=_body;
@property(retain, nonatomic) NSDictionary *HTTPHeaders; // @synthesize HTTPHeaders=_HTTPHeaders;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *HTTPMethod; // @synthesize HTTPMethod=_HTTPMethod;
@property(copy, nonatomic) NSString *endpoint; // @synthesize endpoint=_endpoint;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqualToRequest:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) unsigned long long currentRetryAttempt; // @dynamic currentRetryAttempt;
- (id)initWithTag:(id)arg1 builder:(id)arg2;

@end

