//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALAdRewardDelegate-Protocol.h"
#import "ALAdVideoPlaybackDelegate-Protocol.h"
#import "ALInternalAdDisplayDelegate-Protocol.h"

@class ALIncentivizedInterstitialAd, ALSdk, NSString;
@protocol ALAdDisplayDelegate, ALAdRewardDelegate, ALAdVideoPlaybackDelegate;

@interface ALIncentivizedDelegateProxy : NSObject <ALAdVideoPlaybackDelegate, ALAdRewardDelegate, ALInternalAdDisplayDelegate>
{
    ALSdk *_sdk;
    ALIncentivizedInterstitialAd *_incentController;
    id <ALAdDisplayDelegate> _displayDelegate;
    id <ALAdVideoPlaybackDelegate> _videoDelegate;
    id <ALAdRewardDelegate> _rewardDelegate;
}

@property(retain, nonatomic) id <ALAdRewardDelegate> rewardDelegate; // @synthesize rewardDelegate=_rewardDelegate;
@property(retain, nonatomic) id <ALAdVideoPlaybackDelegate> videoDelegate; // @synthesize videoDelegate=_videoDelegate;
@property(retain, nonatomic) id <ALAdDisplayDelegate> displayDelegate; // @synthesize displayDelegate=_displayDelegate;
@property(nonatomic) __weak ALIncentivizedInterstitialAd *incentController; // @synthesize incentController=_incentController;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)userDeclinedToViewAd:(id)arg1;
- (void)rewardValidationRequestForAd:(id)arg1 didFailWithError:(long long)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 wasRejectedWithResponse:(id)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 didExceedQuotaWithResponse:(id)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 didSucceedWithResponse:(id)arg2;
- (void)handleAdHiddenForDirectAd:(id)arg1 inView:(id)arg2;
- (void)ad:(id)arg1 wasHiddenIn:(id)arg2;
- (void)didFailToDisplayAdWithErrorMessage:(id)arg1;
- (void)ad:(id)arg1 wasClickedIn:(id)arg2;
- (void)ad:(id)arg1 wasDisplayedIn:(id)arg2;
- (void)videoPlaybackEndedInAd:(id)arg1 atPlaybackPercent:(id)arg2 fullyWatched:(_Bool)arg3;
- (void)videoPlaybackBeganInAd:(id)arg1;
- (id)initWithIncentivizedInterstitialAd:(id)arg1 displayDelegate:(id)arg2 videoPlaybackDelegate:(id)arg3 rewardDelegate:(id)arg4 sdk:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

