//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALSdkSettings.h"

@class NSMutableDictionary;

@interface ALInternalSdkSettings : ALSdkSettings
{
    NSMutableDictionary *overriddenSettings;
}

- (void).cxx_destruct;
- (id)overriddenSettings;
- (void)putBool:(_Bool)arg1 forKey:(id)arg2;
- (void)putLong:(long long)arg1 forKey:(id)arg2;
- (void)putInt:(int)arg1 forKey:(id)arg2;
- (void)putString:(id)arg1 forKey:(id)arg2;
- (id)init;

@end

