//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALAdLoadDelegate-Protocol.h"

@class ALAd, ALInterstitialAd, ALLogger, ALSdk, NSString;
@protocol ALAdDisplayDelegate, ALAdLoadDelegate, ALAdVideoPlaybackDelegate;

@interface ALIncentivizedInterstitialAd : NSObject <ALAdLoadDelegate>
{
    _Bool _wasFullyEngaged;
    id <ALAdDisplayDelegate> _adDisplayDelegate;
    id <ALAdVideoPlaybackDelegate> _adVideoPlaybackDelegate;
    NSString *_zoneIdentifier;
    ALSdk *_sdk;
    ALLogger *_logger;
    ALInterstitialAd *_interstitialAd;
    ALAd *_lastAd;
    id <ALAdLoadDelegate> _lastLoadDelegate;
    NSString *_rewardTaskResult;
}

+ (id)userIdentifier;
+ (void)setUserIdentifier:(id)arg1;
+ (_Bool)isReadyForDisplay;
+ (void)showOver:(id)arg1 placement:(id)arg2 andNotify:(id)arg3;
+ (void)showOver:(id)arg1 andNotify:(id)arg2;
+ (void)showOverPlacement:(id)arg1 andNotify:(id)arg2;
+ (void)showOverPlacement:(id)arg1;
+ (void)showAndNotify:(id)arg1;
+ (void)show;
+ (void)preloadAndNotify:(id)arg1;
+ (id)shared;
@property _Bool wasFullyEngaged; // @synthesize wasFullyEngaged=_wasFullyEngaged;
@property NSString *rewardTaskResult; // @synthesize rewardTaskResult=_rewardTaskResult;
@property __weak id <ALAdLoadDelegate> lastLoadDelegate; // @synthesize lastLoadDelegate=_lastLoadDelegate;
@property(retain) ALAd *lastAd; // @synthesize lastAd=_lastAd;
@property(retain, nonatomic) ALInterstitialAd *interstitialAd; // @synthesize interstitialAd=_interstitialAd;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(copy, nonatomic) NSString *zoneIdentifier; // @synthesize zoneIdentifier=_zoneIdentifier;
@property(retain, nonatomic) id <ALAdVideoPlaybackDelegate> adVideoPlaybackDelegate; // @synthesize adVideoPlaybackDelegate=_adVideoPlaybackDelegate;
@property(retain, nonatomic) id <ALAdDisplayDelegate> adDisplayDelegate; // @synthesize adDisplayDelegate=_adDisplayDelegate;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)adService:(id)arg1 didLoadAd:(id)arg2;
@property(readonly, getter=isReadyForDisplay) _Bool readyForDisplay; // @dynamic readyForDisplay;
- (void)clearRewardState;
- (void)dismiss;
- (void)launchRewardTaskForAd:(id)arg1 delegate:(id)arg2;
- (void)failDisplay:(id)arg1 inWindow:(id)arg2;
- (void)attemptShowOver:(id)arg1 renderAd:(id)arg2 andNotify:(id)arg3;
- (void)showOver:(id)arg1 placement:(id)arg2 renderAd:(id)arg3 andNotify:(id)arg4;
- (void)showOver:(id)arg1 renderAd:(id)arg2 andNotify:(id)arg3;
- (void)showAd:(id)arg1 andNotify:(id)arg2;
- (void)showOver:(id)arg1 placement:(id)arg2 andNotify:(id)arg3;
- (void)showOver:(id)arg1 andNotify:(id)arg2;
- (void)showAndNotify:(id)arg1;
- (void)show;
- (void)preloadAndNotify:(id)arg1;
- (id)initIncentivizedInterstitialWithSdk:(id)arg1;
- (id)initWithZoneIdentifier:(id)arg1 sdk:(id)arg2;
- (id)initWithSdk:(id)arg1;
- (id)initWithZoneIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

