//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALInterstitialControlProxy-Protocol.h"

@class ALLogger, ALSdk, NSString;
@protocol ALAdDisplayDelegate, ALAdLoadDelegate, ALAdVideoPlaybackDelegate, ALInterstitialControlProxy;

@interface ALInterstitialAd : NSObject <ALInterstitialControlProxy>
{
    _Bool _hidden;
    id <ALAdLoadDelegate> _adLoadDelegate;
    id <ALAdDisplayDelegate> _adDisplayDelegate;
    id <ALAdVideoPlaybackDelegate> _adVideoPlaybackDelegate;
    ALSdk *_sdk;
    ALLogger *_logger;
    id <ALInterstitialControlProxy> _currentInterstitialController;
    struct CGRect _frame;
}

+ (_Bool)isReadyForDisplay;
+ (id)showOver:(id)arg1 placement:(id)arg2;
+ (id)showOverPlacement:(id)arg1;
+ (id)showOver:(id)arg1;
+ (id)show;
+ (id)shared;
@property(retain) id <ALInterstitialControlProxy> currentInterstitialController; // @synthesize currentInterstitialController=_currentInterstitialController;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) id <ALAdVideoPlaybackDelegate> adVideoPlaybackDelegate; // @synthesize adVideoPlaybackDelegate=_adVideoPlaybackDelegate;
@property(retain, nonatomic) id <ALAdDisplayDelegate> adDisplayDelegate; // @synthesize adDisplayDelegate=_adDisplayDelegate;
@property(retain, nonatomic) id <ALAdLoadDelegate> adLoadDelegate; // @synthesize adLoadDelegate=_adLoadDelegate;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isReadyForDisplay;
- (void)failShow:(id)arg1 window:(id)arg2;
- (void)showInterstitialInViewController:(id)arg1 overWindow:(id)arg2;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)dismiss;
- (void)showOver:(id)arg1 placement:(id)arg2 andRender:(id)arg3;
- (void)showOver:(id)arg1 andRender:(id)arg2;
- (void)showAd:(id)arg1;
- (void)showOver:(id)arg1 placement:(id)arg2;
- (void)showOverPlacement:(id)arg1;
- (void)showOver:(id)arg1;
- (void)show;
- (id)initWithFrame:(struct CGRect)arg1 sdk:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initInterstitialAdWithSdk:(id)arg1;
- (id)initWithSdk:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property _Bool dismissesOnClick;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

