//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk;

@interface ALLogger : NSObject
{
    ALSdk *_sdk;
}

+ (void)logUserMessage:(id)arg1 fromSource:(id)arg2 atLevel:(id)arg3;
+ (void)userError:(id)arg1 message:(id)arg2;
+ (void)userWarning:(id)arg1 message:(id)arg2;
+ (void)userInfo:(id)arg1 message:(id)arg2;
+ (void)userDebug:(id)arg1 message:(id)arg2;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)logMessage:(id)arg1 fromSource:(id)arg2 atLevel:(id)arg3;
- (void)e:(id)arg1 reportError:(_Bool)arg2 message:(id)arg3;
- (void)e:(id)arg1 message:(id)arg2;
- (void)e:(id)arg1 reportError:(_Bool)arg2 message:(id)arg3 becauseOf:(id)arg4;
- (void)e:(id)arg1 message:(id)arg2 becauseOf:(id)arg3;
- (void)w:(id)arg1 message:(id)arg2;
- (void)i:(id)arg1 message:(id)arg2;
- (void)d:(id)arg1 message:(id)arg2;
- (id)initWithSdk:(id)arg1;

@end

