//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALAdDelegateProxy.h"

@class ALTaskProcessNextWaterfallAd;

@interface ALLoadAdapterAdAdDelegateProxy : ALAdDelegateProxy
{
    ALTaskProcessNextWaterfallAd *_parentTask;
}

@property(retain, nonatomic) ALTaskProcessNextWaterfallAd *parentTask; // @synthesize parentTask=_parentTask;
- (void).cxx_destruct;
- (void)didFailToLoadAdForAdUnitIdentifier:(id)arg1 withErrorCode:(long long)arg2;
- (void)didLoadAd:(id)arg1;
- (id)initWithParentTask:(id)arg1;

@end

