//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAAd.h"

@class NSDictionary, NSNumber, NSString;

@interface ALMediationAdapterSpec : MAAd
{
    NSString *_placement;
}

@property(copy) NSString *placement; // @synthesize placement=_placement;
- (void).cxx_destruct;
- (id)description;
- (id)macroValueForKey:(id)arg1;
- (id)macroReplacements;
- (id)postbackUrlsFromFullResponseForKey:(id)arg1;
- (id)postbackUrlsFromSpecObjectForKey:(id)arg1;
- (_Bool)shouldFirePostbackInSuccessionForKey:(id)arg1;
- (id)replacePostbackMacrosForPostbacks:(id)arg1 withUserInfo:(id)arg2;
- (id)postbackUrlsForKey:(id)arg1 userInfo:(id)arg2;
- (id)specLevelPostbackUrlsForKey:(id)arg1 userInfo:(id)arg2;
@property(readonly, nonatomic) double initializationCompletionDelaySeconds; // @dynamic initializationCompletionDelaySeconds;
@property(readonly, nonatomic) NSNumber *adHiddenCallbackDelayMilliseconds; // @dynamic adHiddenCallbackDelayMilliseconds;
@property(readonly, nonatomic) long long fullscreenDisplayDelayMilliseconds; // @dynamic fullscreenDisplayDelayMilliseconds;
@property(readonly, nonatomic) long long adRefreshMilliseconds; // @dynamic adRefreshMilliseconds;
@property(readonly, nonatomic, getter=isRefreshEnabled) _Bool refreshEnabled; // @dynamic refreshEnabled;
@property(readonly, nonatomic) double timeoutSeconds; // @dynamic timeoutSeconds;
@property(readonly, nonatomic) NSDictionary *serverParameters; // @dynamic serverParameters;
@property(readonly, nonatomic) _Bool runOnUIThread; // @dynamic runOnUIThread;
@property(readonly, nonatomic, getter=isAgeRestrictedUser) _Bool ageRestrictedUser; // @dynamic ageRestrictedUser;
@property(readonly, nonatomic, getter=hasUserConsent) _Bool userConsent; // @dynamic userConsent;
@property(readonly, nonatomic, getter=isTesting) _Bool testing; // @dynamic testing;
@property(readonly, copy, nonatomic) NSString *adapterName; // @dynamic adapterName;
@property(readonly, copy, nonatomic) NSString *adapterClass; // @dynamic adapterClass;
- (id)initWithSpecObject:(id)arg1 fullResponse:(id)arg2 sdk:(id)arg3;

@end

