//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALSetting.h"

@interface ALMediationSetting : ALSetting
{
}

+ (id)fallbackAdRetryDelaySeconds;
+ (id)fallbackAdEligibleSignalProviderClassNames;
+ (id)fallbackRewardedAdUnitIdentifier;
+ (id)fallbackInterstitialAdUnitIdentifier;
+ (id)pauseRefreshOnExpand;
+ (id)timeoutTaskUseTimer;
+ (id)validateAdFormat;
+ (id)adFormatsForAppLovinAdapterDirectDelegateSetting;
+ (id)adViewControllerObserverClassesToIgnore;
+ (id)adViewControllerObserverIntervalSeconds;
+ (id)adViewControllerObserverDelaySeconds;
+ (id)scheduleAdHiddenOnAdViewControllerDismissed;
+ (id)adHiddenTimeoutMilliseconds;
+ (id)formatDependentQueues;
+ (id)fetchMediatedAdHttpMethodName;
+ (id)fullscreenAdsBlockPublisherLoadIfAnotherShowing;
+ (id)adViewBlockPublisherLoadIfRefreshScheduled;
+ (id)scheduleAdExpirationWhileInBackground;
+ (id)adExpirationMilliseconds;
+ (id)adViewRefreshPrecacheRequestDelayMilliseconds;
+ (id)adViewRefreshPrecacheRequestViewabilityUndesiredFlags;
+ (id)adHiddenCallbackDelayMilliseconds;
+ (id)fullscreenDisplayDelayMilliseconds;
+ (id)adViewFadeOutAnimationMilliseconds;
+ (id)adViewFadeInAnimationMilliseconds;
+ (id)refreshAdViewTimerRespondsToFullscreenAds;
+ (id)refreshAdViewTimerRespondsToBackground;
+ (id)refreshAdViewOnAppResumeElapsedThresholdMilliseconds;
+ (id)adViewLoadFailureRefreshIgnoreErrorCodes;
+ (id)adViewLoadFailureRefreshMilliseconds;
+ (id)adViewRefreshMilliseconds;
+ (id)defaultAdViewHeight;
+ (id)defaultAdViewWidth;
+ (id)defaultAdapterTimeoutMilliseconds;
+ (id)maxAdapterSignalLength;
+ (id)maxAdapterSDKVersionLength;
+ (id)maxAdapterVersionLength;
+ (id)maxSignalProviderLatencyMilliseconds;
+ (id)persistentMediatedPostbacks;
+ (id)postbackMacros;
+ (id)processAdWaterfallImmediately;
+ (id)passExtraParameters;
+ (id)fetchMediationDebuggerInfoTimeoutMilliseconds;
+ (id)fetchNextAdTimeoutMilliseconds;
+ (id)fetchNextAdRetryDelayMilliseconds;
+ (id)mediationBackupEndpoint;
+ (id)mediationEndpoint;
+ (id)adaptersForInitializationTimeoutMilliseconds;
+ (id)adaptersForInitialization;
+ (void)initialize;

@end

