//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALLogger, ALMediationAdapterManager, ALSdk, NSMutableOrderedSet;

@interface ALMediationService : NSObject
{
    ALSdk *_sdk;
    ALLogger *_logger;
    ALAtomicBoolean *_isInitialized;
    ALMediationAdapterManager *_adapterManager;
    NSMutableOrderedSet *_initializedAdapterNames;
    NSObject *_initializedAdapterNamesLock;
}

@property(retain, nonatomic) NSObject *initializedAdapterNamesLock; // @synthesize initializedAdapterNamesLock=_initializedAdapterNamesLock;
@property(retain, nonatomic) NSMutableOrderedSet *initializedAdapterNames; // @synthesize initializedAdapterNames=_initializedAdapterNames;
@property(retain, nonatomic) ALMediationAdapterManager *adapterManager; // @synthesize adapterManager=_adapterManager;
@property(retain, nonatomic) ALAtomicBoolean *isInitialized; // @synthesize isInitialized=_isInitialized;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)scheduleMediationEventPostbackForEventType:(id)arg1 userInfo:(id)arg2 errorCode:(long long)arg3 errorMessage:(id)arg4 ad:(id)arg5;
- (void)scheduleMediationEventPostbackForEventType:(id)arg1 errorCode:(long long)arg2 errorString:(id)arg3 ad:(id)arg4;
- (void)scheduleMediationEventPostbackForEventType:(id)arg1 errorCode:(long long)arg2 ad:(id)arg3;
- (void)scheduleSignalErrorPostbackIfNeededForErrorMessage:(id)arg1 signalProviderSpec:(id)arg2;
- (void)scheduleAdDisplayErrorPostbackIfNeededForErrorCode:(long long)arg1 errorString:(id)arg2 ad:(id)arg3;
- (void)scheduleAdClickPostbackIfNeededForAd:(id)arg1;
- (void)scheduleCallbackAdImpressionPostbackIfNeededForAd:(id)arg1;
- (void)scheduleViewabilityAdImpressionPostbackIfNeededForAd:(id)arg1 flags:(unsigned long long)arg2;
- (void)scheduleRawAdImpressionPostbackIfNeededForAd:(id)arg1;
- (void)scheduleAdapterInitializationPostbackIfNeededForAdapter:(id)arg1 timeElapsedMilliseconds:(long long)arg2 initializationStatus:(long long)arg3 errorMessage:(id)arg4;
- (void)scheduleAdLoadErrorPostbackIfNeededForErrorCode:(long long)arg1 errorString:(id)arg2 ad:(id)arg3;
- (void)scheduleAdLoadPostbackIfNeededForAd:(id)arg1;
- (void)scheduleAdPreloadPostbackIfNeededForAd:(id)arg1;
- (void)notifyAdDisplayFailureForAd:(id)arg1 errorCode:(long long)arg2 errorString:(id)arg3 andNotify:(id)arg4;
- (void)notifyAdLoadFailureForAd:(id)arg1 errorCode:(long long)arg2 errorString:(id)arg3 andNotify:(id)arg4;
- (void)collectSignalForAdFormat:(id)arg1 signalProviderSpec:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)destroyAd:(id)arg1;
- (void)showFullscreenAd:(id)arg1 forPlacement:(id)arg2;
- (void)loadThirdPartyMediatedAdForAdUnitIdentifier:(id)arg1 mediatedAd:(id)arg2 andNotify:(id)arg3;
- (void)loadAdForAdUnitIdentifier:(id)arg1 format:(id)arg2 requestParameters:(id)arg3 isFallbackAd:(_Bool)arg4 andNotify:(id)arg5;
- (id)initWithSdk:(id)arg1;

@end

