//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALConnectionUtils.h"

@interface ALMediationConnectionUtils : ALConnectionUtils
{
}

+ (void)updateAutoInitAdaptersFromDict:(id)arg1 usingSdk:(id)arg2;
+ (void)updateSignalProvidersFromDict:(id)arg1 usingSdk:(id)arg2;
+ (id)fieldTestModeAutoInitAdapters;
+ (id)fieldAutoInitAdapters;
+ (id)fieldSignalProviders;
+ (id)mediationBackupAdServerUrl:(id)arg1 with:(id)arg2;
+ (id)mediationAdServerUrl:(id)arg1 with:(id)arg2;

@end

