//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, NSArray, NSMutableSet, NSString;

@interface ALMediationDebuggerTableViewDataSource : NSObject
{
    ALAtomicBoolean *_networksInitialized;
    NSArray *_completedNetworks;
    NSArray *_incompleteNetworks;
    NSArray *_missingNetworks;
    NSMutableSet *_dataSourceObservers;
    NSObject *_dataSourceObserversLock;
}

@property(retain, nonatomic) NSObject *dataSourceObserversLock; // @synthesize dataSourceObserversLock=_dataSourceObserversLock;
@property(retain, nonatomic) NSMutableSet *dataSourceObservers; // @synthesize dataSourceObservers=_dataSourceObservers;
@property(retain, nonatomic) NSArray *missingNetworks; // @synthesize missingNetworks=_missingNetworks;
@property(retain, nonatomic) NSArray *incompleteNetworks; // @synthesize incompleteNetworks=_incompleteNetworks;
@property(retain, nonatomic) NSArray *completedNetworks; // @synthesize completedNetworks=_completedNetworks;
@property(retain, nonatomic) ALAtomicBoolean *networksInitialized; // @synthesize networksInitialized=_networksInitialized;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)cellViewModelForRowAtIndexPath:(id)arg1;
- (void)unregisterDataSourceObserver:(id)arg1;
- (void)registerDataSourceObserver:(id)arg1;
- (void)registerReusableCellsForTableView:(id)arg1;
- (void)updateNetworkViewModels:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

