//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, NSMutableDictionary, NSMutableSet, NSString;

@interface ALMediationAdapterRouter : NSObject
{
    CDUnknownBlockType _completionHandler;
    NSString *_tag;
    ALSdk *_sdk;
    NSMutableDictionary *_delegates;
    NSObject *_delegatesLock;
    NSMutableSet *_loadedAdapters;
    NSObject *_loadedAdaptersLock;
    NSMutableSet *_showingAdapters;
    NSObject *_showingAdaptersLock;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject *showingAdaptersLock; // @synthesize showingAdaptersLock=_showingAdaptersLock;
@property(retain, nonatomic) NSMutableSet *showingAdapters; // @synthesize showingAdapters=_showingAdapters;
@property(retain, nonatomic) NSObject *loadedAdaptersLock; // @synthesize loadedAdaptersLock=_loadedAdaptersLock;
@property(retain, nonatomic) NSMutableSet *loadedAdapters; // @synthesize loadedAdapters=_loadedAdapters;
@property(retain, nonatomic) NSObject *delegatesLock; // @synthesize delegatesLock=_delegatesLock;
@property(retain, nonatomic) NSMutableDictionary *delegates; // @synthesize delegates=_delegates;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
- (void)log:(id)arg1 becauseOf:(id)arg2;
- (void)log:(id)arg1;
- (id)showingDelegateWrappersForPlacementIdentifier:(id)arg1;
- (id)loadingDelegateWrappersForPlacementIdentifier:(id)arg1;
- (id)delegateWrappersForPlacementIdentifier:(id)arg1;
- (_Bool)shouldAlwaysRewardUserForPlacementIdentifier:(id)arg1;
- (id)rewardForPlacementIdentifier:(id)arg1;
- (void)didCollapseAdForPlacementIdentifier:(id)arg1;
- (void)didExpandAdForPlacementIdentifier:(id)arg1;
- (void)didRewardUserForPlacementIdentifier:(id)arg1 withReward:(id)arg2;
- (void)didCompleteRewardedVideoForPlacementIdentifier:(id)arg1;
- (void)didStartRewardedVideoForPlacementIdentifier:(id)arg1;
- (void)didHideAdForPlacementIdentifier:(id)arg1;
- (void)didClickAdForPlacementIdentifier:(id)arg1;
- (void)didFailToDisplayAdForPlacementIdentifier:(id)arg1 error:(id)arg2;
- (void)didDisplayAdForPlacementIdentifier:(id)arg1;
- (void)didFailToLoadAdForPlacementIdentifier:(id)arg1 error:(id)arg2;
- (void)didLoadAdForPlacementIdentifier:(id)arg1;
- (_Bool)isAdShowingForAdapter:(id)arg1;
- (void)removeShowingAdapter:(id)arg1;
- (void)addShowingAdapter:(id)arg1;
- (_Bool)isAdLoadedForAdapter:(id)arg1;
- (void)removeLoadedAdapter:(id)arg1;
- (void)addLoadedAdapter:(id)arg1;
- (void)removeAdapter:(id)arg1 forPlacementIdentifier:(id)arg2;
- (void)updateAdView:(id)arg1 forPlacementIdentifier:(id)arg2;
- (void)addAdapter:(id)arg1 delegate:(id)arg2 placementIdentifier:(id)arg3 loadType:(unsigned long long)arg4 adView:(id)arg5;
- (void)addAdViewAdapter:(id)arg1 delegate:(id)arg2 forPlacementIdentifier:(id)arg3 adView:(id)arg4;
- (void)addRewardedAdapter:(id)arg1 delegate:(id)arg2 forPlacementIdentifier:(id)arg3;
- (void)addInterstitialAdapter:(id)arg1 delegate:(id)arg2 forPlacementIdentifier:(id)arg3;
- (void)initializeWithParameters:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

