//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALMediationUtils : NSObject
{
}

+ (id)createAdapterInstanceForClassName:(id)arg1 sdk:(id)arg2;
+ (_Bool)isValidAdFormat:(id)arg1 responseFormat:(id)arg2;
+ (unsigned long long)executionQueueForFormat:(id)arg1 defaultQueue:(unsigned long long)arg2 sdk:(id)arg3;
+ (unsigned long long)executionQueueForFormat:(id)arg1 sdk:(id)arg2;
+ (id)mediationAdapterAvailabilityForSDK:(id)arg1;
+ (void)initialize;

@end

