//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MAAdapter-Protocol.h"

@class ALSdk, MAReward, NSString;

@interface ALMediationAdapter : NSObject <MAAdapter>
{
    _Bool _alwaysRewardUser;
    ALSdk *_sdk;
    NSString *_tag;
    MAReward *_reward;
}

+ (id)mediationTag;
@property(nonatomic, getter=shouldAlwaysRewardUser) _Bool alwaysRewardUser; // @synthesize alwaysRewardUser=_alwaysRewardUser;
@property(retain, nonatomic) MAReward *reward; // @synthesize reward=_reward;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *mediationTag; // @dynamic mediationTag;
- (void)log:(id)arg1 becauseOf:(id)arg2;
- (void)log:(id)arg1;
- (void)destroy;
@property(readonly, copy, nonatomic) NSString *adapterVersion; // @dynamic adapterVersion;
@property(readonly, copy, nonatomic) NSString *SDKVersion; // @dynamic SDKVersion;
- (void)initializeWithParameters:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)initWithSdk:(id)arg1;
- (void)configureRewardForParameters:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

