//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;
@protocol MAAdapter, MAAdapterDelegate;

@interface ALMediationAdapterRouterDelegateWrapper : NSObject
{
    id <MAAdapter> _adapter;
    id <MAAdapterDelegate> _delegate;
    unsigned long long _loadType;
    UIView *_adView;
}

@property(retain, nonatomic) UIView *adView; // @synthesize adView=_adView;
@property(nonatomic) unsigned long long loadType; // @synthesize loadType=_loadType;
@property(retain, nonatomic) id <MAAdapterDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <MAAdapter> adapter; // @synthesize adapter=_adapter;
- (void).cxx_destruct;
- (id)initWithAdapter:(id)arg1 delegate:(id)arg2 loadType:(unsigned long long)arg3 adView:(id)arg4;

@end

