//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MAAdViewAdDelegate-Protocol.h"
#import "MAInternalAdDelegate-Protocol.h"
#import "MARewardedAdDelegate-Protocol.h"

@class ALMediatedAd, ALMediationService, NSString;
@protocol MAAdDelegate;

@interface ALMediationServiceAdDelegateProxy : NSObject <MAInternalAdDelegate, MARewardedAdDelegate, MAAdViewAdDelegate>
{
    ALMediationService *_mediationService;
    ALMediatedAd *_mediatedAd;
    id <MAAdDelegate> _delegate;
}

@property(retain, nonatomic) id <MAAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ALMediatedAd *mediatedAd; // @synthesize mediatedAd=_mediatedAd;
@property(nonatomic) __weak ALMediationService *mediationService; // @synthesize mediationService=_mediationService;
- (void).cxx_destruct;
- (void)didCollapseAd:(id)arg1;
- (void)didExpandAd:(id)arg1;
- (void)didRewardUserForAd:(id)arg1 withReward:(id)arg2;
- (void)didCompleteRewardedVideoForAd:(id)arg1;
- (void)didStartRewardedVideoForAd:(id)arg1;
- (void)didFailToDisplayAd:(id)arg1 withErrorCode:(long long)arg2 errorString:(id)arg3;
- (void)didFailToDisplayAd:(id)arg1 withErrorCode:(long long)arg2;
- (void)didClickAd:(id)arg1;
- (void)didHideAd:(id)arg1;
- (void)didDisplayAd:(id)arg1;
- (void)didFailToLoadAdForAdUnitIdentifier:(id)arg1 withErrorCode:(long long)arg2 errorString:(id)arg3;
- (void)didFailToLoadAdForAdUnitIdentifier:(id)arg1 withErrorCode:(long long)arg2;
- (void)didLoadAd:(id)arg1;
- (id)initWithMediatedAd:(id)arg1 mediationService:(id)arg2 andNotify:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

