//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALMediatedAd.h"

@class ALAtomicBoolean, ALPendingReward, NSObject, NSString;

@interface ALMediatedFullscreenAd : ALMediatedAd
{
    ALPendingReward *_pendingReward;
    NSString *_publisherAdUnitIdentifier;
    NSObject *_pendingRewardLock;
    ALAtomicBoolean *_cancelRewardTask;
}

@property(retain, nonatomic) ALAtomicBoolean *cancelRewardTask; // @synthesize cancelRewardTask=_cancelRewardTask;
@property(retain, nonatomic) NSObject *pendingRewardLock; // @synthesize pendingRewardLock=_pendingRewardLock;
@property(copy, nonatomic) NSString *publisherAdUnitIdentifier; // @synthesize publisherAdUnitIdentifier=_publisherAdUnitIdentifier;
- (void).cxx_destruct;
- (id)getAndRemovePendingReward;
@property(retain, nonatomic) ALPendingReward *pendingReward; // @synthesize pendingReward=_pendingReward;
- (void)cancelRewardValidationTask;
@property(readonly, nonatomic, getter=shouldCancelRewardValidationTask) _Bool cancelRewardValidationTask; // @dynamic cancelRewardValidationTask;
@property(readonly, copy, nonatomic) NSString *MCode; // @dynamic MCode;
@property(readonly, copy, nonatomic) NSString *BCode; // @dynamic BCode;
@property(readonly, nonatomic) double adViewControllerObserverIntervalSeconds; // @dynamic adViewControllerObserverIntervalSeconds;
@property(readonly, nonatomic) double adViewControllerObserverDelaySeconds; // @dynamic adViewControllerObserverDelaySeconds;
@property(readonly, nonatomic, getter=shouldScheduleAdHiddenOnAdViewControllerDismissed) _Bool scheduleAdHiddenOnAdViewControllerDismissed; // @dynamic scheduleAdHiddenOnAdViewControllerDismissed;
@property(readonly, nonatomic) long long adHiddenTimeoutMilliseconds; // @dynamic adHiddenTimeoutMilliseconds;
@property(readonly, nonatomic) long long adExpirationMilliseconds; // @dynamic adExpirationMilliseconds;
@property(readonly, nonatomic) double fallbackAdRefreshDelaySeconds; // @dynamic fallbackAdRefreshDelaySeconds;
@property(readonly, nonatomic) double immediateFallbackAdCallbackDelaySeconds; // @dynamic immediateFallbackAdCallbackDelaySeconds;
@property(readonly, nonatomic, getter=isFallbackAd) _Bool fallbackAd; // @dynamic fallbackAd;
- (id)mediatedAdWithAdapter:(id)arg1;
- (id)initWithParentAd:(id)arg1 adapterWrapper:(id)arg2;
- (id)initWithSpecObject:(id)arg1 fullResponse:(id)arg2 sdk:(id)arg3;

@end

