//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAdLoadManager;

@interface ALMediationFallbackAdManager : NSObject
{
    ALAdLoadManager *_interstitialAdLoadManager;
    ALAdLoadManager *_rewardedAdLoadManager;
}

@property(retain, nonatomic) ALAdLoadManager *rewardedAdLoadManager; // @synthesize rewardedAdLoadManager=_rewardedAdLoadManager;
@property(retain, nonatomic) ALAdLoadManager *interstitialAdLoadManager; // @synthesize interstitialAdLoadManager=_interstitialAdLoadManager;
- (void).cxx_destruct;
- (id)adManagerForAdFormat:(id)arg1;
- (void)attachDelegate:(id)arg1 forAdFormat:(id)arg2;
- (id)adForAdFormat:(id)arg1;
- (void)preloadAdsIfNeeded;
- (id)initWithSdk:(id)arg1;

@end

