//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALMediationAdapterSpec.h"

#import "ALMediatedAdSubclassing-Protocol.h"

@class ALAtomicBoolean, ALMediationAdapterWrapper, NSString;

@interface ALMediatedAd : ALMediationAdapterSpec <ALMediatedAdSubclassing>
{
    ALMediationAdapterWrapper *_adapterWrapper;
    ALAtomicBoolean *_adDisplayedCalled;
}

@property(retain, nonatomic) ALAtomicBoolean *adDisplayedCalled; // @synthesize adDisplayedCalled=_adDisplayedCalled;
@property(retain, nonatomic) ALMediationAdapterWrapper *adapterWrapper; // @synthesize adapterWrapper=_adapterWrapper;
- (void).cxx_destruct;
- (id)description;
- (void)setLoadStarted;
@property(readonly, nonatomic) long long loadStartedTimeMilliseconds; // @dynamic loadStartedTimeMilliseconds;
@property(readonly, nonatomic) long long elapsedLoadTimeMilliseconds; // @dynamic elapsedLoadTimeMilliseconds;
- (void)clearAdapter;
@property(readonly, copy, nonatomic) NSString *thirdPartyAdPlacementIdentifier; // @dynamic thirdPartyAdPlacementIdentifier;
@property(readonly, copy, nonatomic) NSString *bidResponse; // @dynamic bidResponse;
@property(readonly, copy, nonatomic) NSString *serveIdentifier; // @dynamic serveIdentifier;
- (_Bool)isReady;
- (id)mediatedAdWithAdapter:(id)arg1;
- (id)initWithSpecObject:(id)arg1 fullResponse:(id)arg2 adapterWrapper:(id)arg3 sdk:(id)arg4;

@end

