//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALConnectionManagerDelegate-Protocol.h"

@class ALAtomicBoolean, ALLogger, ALMediationDebuggerTableViewDataSource, ALSdk, NSString;

@interface ALMediationDebuggerService : NSObject <ALConnectionManagerDelegate>
{
    _Bool _showAfterSDKInitialization;
    ALSdk *_sdk;
    ALMediationDebuggerTableViewDataSource *_dataSource;
    ALAtomicBoolean *_isInitialized;
}

@property(retain, nonatomic) ALAtomicBoolean *isInitialized; // @synthesize isInitialized=_isInitialized;
@property(retain, nonatomic) ALMediationDebuggerTableViewDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic, getter=shouldShowAfterSDKInitialization) _Bool showAfterSDKInitialization; // @synthesize showAfterSDKInitialization=_showAfterSDKInitialization;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) __weak ALLogger *logger; // @dynamic logger;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (void)updateMediatedNetworks:(id)arg1;
- (void)initializeIfNeeded;
- (void)showDebugger;
- (id)initWithSdk:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

