//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALMediatedAd.h"

@class UIColor, UIView;

@interface ALMediatedAdViewAd : ALMediatedAd
{
}

+ (long long)span;
@property(readonly, nonatomic) UIColor *backgroundColor; // @dynamic backgroundColor;
@property(readonly, nonatomic, getter=shouldPauseRefreshOnAdExpand) _Bool pauseRefreshOnAdExpand; // @dynamic pauseRefreshOnAdExpand;
@property(readonly, nonatomic) double viewabilityTimerMinVisibleSeconds; // @dynamic viewabilityTimerMinVisibleSeconds;
@property(readonly, nonatomic, getter=shouldUseViewabilityTimer) _Bool useViewabilityTimer; // @dynamic useViewabilityTimer;
@property(readonly, nonatomic) double viewabilityMinPercentage; // @dynamic viewabilityMinPercentage;
@property(readonly, nonatomic) double viewabilityMinPixels; // @dynamic viewabilityMinPixels;
@property(readonly, nonatomic) double viewabilityMinAlpha; // @dynamic viewabilityMinAlpha;
@property(readonly, nonatomic) long long viewabilityMinHeight; // @dynamic viewabilityMinHeight;
@property(readonly, nonatomic) long long viewabilityMinWidth; // @dynamic viewabilityMinWidth;
@property(readonly, nonatomic) double viewabilityImpressionDelaySeconds; // @dynamic viewabilityImpressionDelaySeconds;
@property(readonly, nonatomic) UIView *adView; // @dynamic adView;
@property(readonly, nonatomic) double height; // @dynamic height;
@property(readonly, nonatomic) double width; // @dynamic width;
- (id)mediatedAdWithAdapter:(id)arg1;
- (id)initWithParentAd:(id)arg1 adapterWrapper:(id)arg2;

@end

