//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALLogger, ALSdk, NSMutableArray, NSMutableOrderedSet;

@interface ALMediationAdapterInitializationManager : NSObject
{
    NSMutableArray *_initializedAdapters;
    NSMutableOrderedSet *_initializedAdapterNames;
    ALSdk *_sdk;
    ALLogger *_logger;
    ALAtomicBoolean *_isInitialized;
    NSObject *_initializedAdaptersLock;
}

@property(retain, nonatomic) NSObject *initializedAdaptersLock; // @synthesize initializedAdaptersLock=_initializedAdaptersLock;
@property(retain, nonatomic) ALAtomicBoolean *isInitialized; // @synthesize isInitialized=_isInitialized;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(retain, nonatomic) NSMutableOrderedSet *initializedAdapterNames; // @synthesize initializedAdapterNames=_initializedAdapterNames;
@property(retain, nonatomic) NSMutableArray *initializedAdapters; // @synthesize initializedAdapters=_initializedAdapters;
- (void).cxx_destruct;
- (_Bool)isInitializedForSpec:(id)arg1;
- (void)addInitializedAdapter:(id)arg1 forTimeElapsedMilliseconds:(long long)arg2 initializationStatus:(long long)arg3 errorMessage:(id)arg4;
- (void)initializeAdapter:(id)arg1;
- (void)initializeAdapters;
- (id)initWithSdk:(id)arg1;

@end

