//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALNativeAdLoadDelegate-Protocol.h"
#import "ALNativeAdPrecacheDelegate-Protocol.h"

@class ALLogger, ALNativeAdService, ALSdk, NSArray, NSString;
@protocol ALNativeAdLoadDelegate;

@interface ALNativeAdLoadCoordinator : NSObject <ALNativeAdLoadDelegate, ALNativeAdPrecacheDelegate>
{
    _Bool _precacheFinished;
    ALSdk *_sdk;
    ALLogger *_logger;
    ALNativeAdService *_nativeAdService;
    id <ALNativeAdLoadDelegate> _loadDelegate;
    NSArray *_allAds;
    NSArray *_precachedAds;
    long long _loadCount;
    NSString *_zoneIdentifier;
    unsigned long long _pendingImagePrecachesCount;
    unsigned long long _pendingVideoPrecachesCount;
}

@property unsigned long long pendingVideoPrecachesCount; // @synthesize pendingVideoPrecachesCount=_pendingVideoPrecachesCount;
@property unsigned long long pendingImagePrecachesCount; // @synthesize pendingImagePrecachesCount=_pendingImagePrecachesCount;
@property _Bool precacheFinished; // @synthesize precacheFinished=_precacheFinished;
@property(copy, nonatomic) NSString *zoneIdentifier; // @synthesize zoneIdentifier=_zoneIdentifier;
@property(nonatomic) long long loadCount; // @synthesize loadCount=_loadCount;
@property(retain, nonatomic) NSArray *precachedAds; // @synthesize precachedAds=_precachedAds;
@property(retain, nonatomic) NSArray *allAds; // @synthesize allAds=_allAds;
@property(retain, nonatomic) id <ALNativeAdLoadDelegate> loadDelegate; // @synthesize loadDelegate=_loadDelegate;
@property(nonatomic) __weak ALNativeAdService *nativeAdService; // @synthesize nativeAdService=_nativeAdService;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)removeNativeAdsFromPendingPrecaches:(id)arg1;
- (void)handleFailureToLoadNativeAds:(id)arg1 error:(long long)arg2;
- (void)handleSuccessfulLoadForNativeAds:(id)arg1;
- (void)nativeAdService:(id)arg1 didFailToPrecacheVideoForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didFailToPrecacheImagesForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didPrecacheVideoForAd:(id)arg2;
- (void)nativeAdService:(id)arg1 didPrecacheImagesForAd:(id)arg2;
- (void)nativeAdService:(id)arg1 didFailToLoadAdsWithError:(long long)arg2;
- (void)nativeAdService:(id)arg1 didLoadAds:(id)arg2;
- (void)batchPrecacheVideoResourcesForNativeAds:(id)arg1;
- (void)batchPrecacheResourcesForNativeAds:(id)arg1;
- (void)executeNativeAdLoad;
- (id)initWithZoneIdentifier:(id)arg1 loadCount:(unsigned long long)arg2 nativeAdService:(id)arg3 sdk:(id)arg4 andNotify:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

