//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALNativeAdPrecacheDelegate-Protocol.h"

@class ALLogger, ALNativeAdService, ALSdk, NSString;
@protocol ALNativeAdPrecacheDelegate;

@interface ALNativeAdUserBasedPrecacheCoordinator : NSObject <ALNativeAdPrecacheDelegate>
{
    ALSdk *_sdk;
    ALLogger *_logger;
    ALNativeAdService *_nativeAdService;
    id <ALNativeAdPrecacheDelegate> _precacheDelegate;
}

@property(retain, nonatomic) id <ALNativeAdPrecacheDelegate> precacheDelegate; // @synthesize precacheDelegate=_precacheDelegate;
@property(nonatomic) __weak ALNativeAdService *nativeAdService; // @synthesize nativeAdService=_nativeAdService;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)removeFromPendingPrecaches:(id)arg1;
- (void)handleVideoPreloadingSucceededForNativeAd:(id)arg1;
- (void)handleImagePreloadingSucceededForNativeAd:(id)arg1;
- (void)nativeAdService:(id)arg1 didFailToPrecacheVideoForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didFailToPrecacheImagesForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didPrecacheVideoForAd:(id)arg2;
- (void)nativeAdService:(id)arg1 didPrecacheImagesForAd:(id)arg2;
- (void)precacheVideoIfNeededForNativeAd:(id)arg1;
- (void)executePrecacheForNativeAd:(id)arg1;
- (id)initWithNativeAdService:(id)arg1 sdk:(id)arg2 andNotify:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

