//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALLogger, ALSdk;

@interface ALNativeAdService : NSObject
{
    ALSdk *_sdk;
    ALLogger *_logger;
}

@property(retain, nonatomic) ALLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (id)description;
- (void)preloadAdsForZone:(id)arg1;
- (void)preloadAdForZoneIdentifier:(id)arg1;
- (_Bool)hasPreloadedAdForZoneIdentifier:(id)arg1;
- (void)precacheResourcesForNativeAd:(id)arg1 andNotify:(id)arg2;
- (void)loadNativeAdsForZoneIdentifier:(id)arg1 count:(unsigned long long)arg2 andNotify:(id)arg3;
- (void)loadNativeAdGroupOfCount:(unsigned long long)arg1 forZoneIdentifier:(id)arg2 andNotify:(id)arg3;
- (void)loadNativeAdGroupOfCount:(unsigned long long)arg1 andNotify:(id)arg2;
- (void)loadNextAdAndNotify:(id)arg1;
- (id)initWithSdk:(id)arg1;

@end

