//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALLoadableObject-Protocol.h"
#import "ALStoreKitAd-Protocol.h"

@class ALAdSize, ALAdZone, ALAtomicBoolean, ALLogger, ALSdk, ALStoreKitPoststitialConfiguration, NSArray, NSDictionary, NSNumber, NSString, NSURL;

@interface ALNativeAd : NSObject <ALLoadableObject, ALStoreKitAd>
{
    _Bool opensInStoreKit;
    _Bool storekitPoststitialEnabled;
    NSDictionary *storeKitParameters;
    unsigned long long iTunesIdentifier;
    unsigned long long supportedStoreKitOrientations;
    unsigned long long storekitPoststitialMode;
    ALStoreKitPoststitialConfiguration *storeKitPoststitialConfiguration;
    NSNumber *_adIdNumber;
    NSString *_zoneIdentifier;
    NSString *_title;
    NSString *_descriptionText;
    NSString *_captionText;
    NSString *_ctaText;
    NSURL *_iconURL;
    NSURL *_imageURL;
    NSNumber *_starRating;
    NSURL *_videoURL;
    NSURL *_videoStartTrackingURL;
    ALSdk *_parentSdk;
    ALAtomicBoolean *_impressionTracked;
    ALAdZone *_adZone;
    NSURL *_sourceIconURL;
    NSURL *_sourceImageURL;
    NSURL *_sourceVideoURL;
    NSURL *_clickURL;
    NSURL *_impressionTrackingURL;
    NSURL *_videoEndTrackingURL;
    NSArray *_impressionPostbacks;
    NSArray *_clickTrackingPostbacks;
    NSString *_clCode;
    NSArray *_resourcePrefixes;
}

@property(retain, nonatomic) NSArray *resourcePrefixes; // @synthesize resourcePrefixes=_resourcePrefixes;
@property(copy, nonatomic) NSString *clCode; // @synthesize clCode=_clCode;
@property(retain, nonatomic) NSArray *clickTrackingPostbacks; // @synthesize clickTrackingPostbacks=_clickTrackingPostbacks;
@property(retain, nonatomic) NSArray *impressionPostbacks; // @synthesize impressionPostbacks=_impressionPostbacks;
@property(retain, nonatomic) NSURL *videoEndTrackingURL; // @synthesize videoEndTrackingURL=_videoEndTrackingURL;
@property(retain, nonatomic) NSURL *impressionTrackingURL; // @synthesize impressionTrackingURL=_impressionTrackingURL;
@property(retain, nonatomic) NSURL *clickURL; // @synthesize clickURL=_clickURL;
@property(retain, nonatomic) NSURL *sourceVideoURL; // @synthesize sourceVideoURL=_sourceVideoURL;
@property(retain, nonatomic) NSURL *sourceImageURL; // @synthesize sourceImageURL=_sourceImageURL;
@property(retain, nonatomic) NSURL *sourceIconURL; // @synthesize sourceIconURL=_sourceIconURL;
@property(retain, nonatomic) ALAdZone *adZone; // @synthesize adZone=_adZone;
@property(retain) ALAtomicBoolean *impressionTracked; // @synthesize impressionTracked=_impressionTracked;
@property(nonatomic) __weak ALSdk *parentSdk; // @synthesize parentSdk=_parentSdk;
@property(retain, nonatomic) NSURL *videoStartTrackingURL; // @synthesize videoStartTrackingURL=_videoStartTrackingURL;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(retain, nonatomic) NSNumber *starRating; // @synthesize starRating=_starRating;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) NSURL *iconURL; // @synthesize iconURL=_iconURL;
@property(copy, nonatomic) NSString *ctaText; // @synthesize ctaText=_ctaText;
@property(copy, nonatomic) NSString *captionText; // @synthesize captionText=_captionText;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *zoneIdentifier; // @synthesize zoneIdentifier=_zoneIdentifier;
@property(retain, nonatomic) NSNumber *adIdNumber; // @synthesize adIdNumber=_adIdNumber;
@property(readonly, nonatomic) ALStoreKitPoststitialConfiguration *storeKitPoststitialConfiguration; // @synthesize storeKitPoststitialConfiguration;
@property(nonatomic) unsigned long long storekitPoststitialMode; // @synthesize storekitPoststitialMode;
@property(readonly, nonatomic) _Bool storekitPoststitialEnabled; // @synthesize storekitPoststitialEnabled;
@property(nonatomic) unsigned long long supportedStoreKitOrientations; // @synthesize supportedStoreKitOrientations;
@property(nonatomic) unsigned long long iTunesIdentifier; // @synthesize iTunesIdentifier;
@property(nonatomic) _Bool opensInStoreKit; // @synthesize opensInStoreKit;
@property(retain, nonatomic) NSDictionary *storeKitParameters; // @synthesize storeKitParameters;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) ALAdSize *size; // @dynamic size;
@property(readonly, nonatomic) ALLogger *logger; // @dynamic logger;
- (void)launchClickTarget;
- (void)trackImpressionAndNotify:(id)arg1;
- (void)trackImpression;
@property(readonly, getter=isVideoPrecached) _Bool videoPrecached;
@property(readonly, getter=isImagePrecached) _Bool imagePrecached;
- (id)videoEndTrackingURL:(unsigned long long)arg1 firstPlay:(_Bool)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

