//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALNetworkResponseCodeCounter : NSObject
{
}

+ (void)persistTopLevelDict:(id)arg1;
+ (id)retrieveTopLevelDictForURLKey:(id)arg1;
+ (id)retrieveMappings;
+ (void)clear;
+ (void)incrementForURL:(id)arg1 code:(long long)arg2;
+ (void)initialize;

@end

