//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ALOptOutButton;

@protocol ALOptOutButtonDelegate <NSObject>
- (void)didContractForOptOutButton:(ALOptOutButton *)arg1;
- (void)willExpandForOptOutButton:(ALOptOutButton *)arg1;
- (void)didDismissFullscreenForOptOutButton:(ALOptOutButton *)arg1;
- (void)willPresentFullscreenForOptOutButton:(ALOptOutButton *)arg1;
@end

