//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ALWebViewButtonDelegate-Protocol.h"
#import "SFSafariViewControllerDelegate-Protocol.h"

@class ALAdEventStatsManagerHelper, ALLogger, ALOptOutButtonConfiguration, ALSdk, NSString, UIButton, UIViewController;
@protocol ALOptOutButtonDelegate, ALWebViewButton;

@interface ALOptOutButton : UIView <SFSafariViewControllerDelegate, ALWebViewButtonDelegate>
{
    _Bool _expanded;
    ALSdk *_sdk;
    ALLogger *_logger;
    ALOptOutButtonConfiguration *_config;
    ALAdEventStatsManagerHelper *_adEventStatsManagerHelper;
    UIViewController<ALOptOutButtonDelegate> *_parentViewController;
    UIButton *_optoutButton;
    UIView<ALWebViewButton> *_expandedOptOutButton;
}

@property(retain, nonatomic) UIView<ALWebViewButton> *expandedOptOutButton; // @synthesize expandedOptOutButton=_expandedOptOutButton;
@property(retain, nonatomic) UIButton *optoutButton; // @synthesize optoutButton=_optoutButton;
@property(nonatomic) __weak UIViewController<ALOptOutButtonDelegate> *parentViewController; // @synthesize parentViewController=_parentViewController;
@property(retain, nonatomic) ALAdEventStatsManagerHelper *adEventStatsManagerHelper; // @synthesize adEventStatsManagerHelper=_adEventStatsManagerHelper;
@property(retain, nonatomic) ALOptOutButtonConfiguration *config; // @synthesize config=_config;
@property(nonatomic) __weak ALLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic, getter=isExpanded) _Bool expanded; // @synthesize expanded=_expanded;
- (void).cxx_destruct;
- (void)didReceiveCloseCommandOnWebViewButton:(id)arg1;
- (void)didReceiveClickCommandOnWebViewButton:(id)arg1;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)presentDestination;
- (void)contract;
- (void)expand;
- (void)handleTapForSmallOptOutButton;
- (id)initWithConfiguration:(id)arg1 adEventStatsManagerHelper:(id)arg2 parentViewController:(id)arg3 sdk:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

