//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALBaseOptOutButtonConfiguration.h"

@class ALOptOutButtonExpandedConfiguration, NSURL;

@interface ALOptOutButtonConfiguration : ALBaseOptOutButtonConfiguration
{
}

- (id)defaultVerticalConstraintValue;
- (id)defaultHorizontalConstraintValue;
@property(readonly, nonatomic) ALOptOutButtonExpandedConfiguration *expandedConfiguration; // @dynamic expandedConfiguration;
@property(readonly, nonatomic, getter=isExpandedOptOutButtonEnabled) _Bool expandedOptOutButtonEnabled; // @dynamic expandedOptOutButtonEnabled;
@property(readonly, nonatomic) unsigned long long supportedInterfaceOrientations; // @dynamic supportedInterfaceOrientations;
@property(readonly, nonatomic, getter=shouldUseForPoststitial) _Bool useForPoststitial; // @dynamic useForPoststitial;
@property(readonly, nonatomic) unsigned long long actionType; // @dynamic actionType;
@property(readonly, nonatomic) NSURL *destinationURL; // @dynamic destinationURL;
@property(readonly, nonatomic) NSURL *imageURL; // @dynamic imageURL;

@end

