//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface ALPendingReward : NSObject
{
    NSString *_result;
    NSDictionary *_parameters;
}

+ (id)createWithResult:(id)arg1 parameters:(id)arg2;
+ (id)createWithResult:(id)arg1;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) NSString *result; // @synthesize result=_result;
- (void).cxx_destruct;
- (id)initWithResult:(id)arg1 parameters:(id)arg2;

@end

