//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, NSMutableArray;

@interface ALPersistentPostbackManager : NSObject
{
    ALSdk *_sdk;
    NSObject *_queueLock;
    NSMutableArray *_postbackQueue;
    NSMutableArray *_stalledPostbacks;
}

@property(retain, nonatomic) NSMutableArray *stalledPostbacks; // @synthesize stalledPostbacks=_stalledPostbacks;
@property(retain, nonatomic) NSMutableArray *postbackQueue; // @synthesize postbackQueue=_postbackQueue;
@property(retain, nonatomic) NSObject *queueLock; // @synthesize queueLock=_queueLock;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)flushStalledPostbacks;
- (void)flushPostbackQueue;
- (void)writeQueue;
- (void)handleStalledPostback:(id)arg1;
- (void)dequeuePostback:(id)arg1;
- (void)dispatchPostback:(id)arg1 andNotify:(id)arg2;
- (void)dispatchPostback:(id)arg1;
- (void)enqueuePostback:(id)arg1;
- (void)submitPostback:(id)arg1 appendTimestamp:(_Bool)arg2 andNotify:(id)arg3;
- (void)submitPostback:(id)arg1 appendTimestamp:(_Bool)arg2;
- (void)submitPostback:(id)arg1;
- (id)loadQueue;
- (id)initWithSdk:(id)arg1;

@end

