//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALPostbackDelegate-Protocol.h"

@class ALPersistentPostback, ALPersistentPostbackManager, NSString;
@protocol ALPostbackDelegate;

@interface ALPersistentPostbackManagerDelegateProxy : NSObject <ALPostbackDelegate>
{
    ALPersistentPostbackManager *_postbackManager;
    ALPersistentPostback *_postback;
    id <ALPostbackDelegate> _delegate;
}

+ (id)delegateProxyWithPostbackRequest:(id)arg1 postbackManager:(id)arg2 andNotify:(id)arg3;
@property(retain, nonatomic) id <ALPostbackDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ALPersistentPostback *postback; // @synthesize postback=_postback;
@property(nonatomic) __weak ALPersistentPostbackManager *postbackManager; // @synthesize postbackManager=_postbackManager;
- (void).cxx_destruct;
- (void)postbackService:(id)arg1 didFailToExecutePostback:(id)arg2 errorCode:(long long)arg3;
- (void)postbackService:(id)arg1 didExecutePostback:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

