//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDictionary, NSURL;

@interface ALPersistentPostback : NSObject <NSCoding>
{
    _Bool _encodingEnabled;
    NSURL *_targetURL;
    NSURL *_backupURL;
    NSDictionary *_parameters;
    NSDictionary *_requestBody;
    NSDictionary *_HTTPHeaders;
    long long _attemptNumber;
}

+ (id)postbackWithBuilderBlock:(CDUnknownBlockType)arg1;
@property long long attemptNumber; // @synthesize attemptNumber=_attemptNumber;
@property _Bool encodingEnabled; // @synthesize encodingEnabled=_encodingEnabled;
@property(retain, nonatomic) NSDictionary *HTTPHeaders; // @synthesize HTTPHeaders=_HTTPHeaders;
@property(retain, nonatomic) NSDictionary *requestBody; // @synthesize requestBody=_requestBody;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) NSURL *backupURL; // @synthesize backupURL=_backupURL;
@property(retain, nonatomic) NSURL *targetURL; // @synthesize targetURL=_targetURL;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqualToRequest:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)incrementAttemptNumber;
- (void)appendTimestamp;
- (id)initWithBuilder:(id)arg1;

@end

