//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSURL;

@interface ALPersistentPostbackBuilder : NSObject
{
    _Bool _encodingEnabled;
    NSURL *_targetURL;
    NSURL *_backupURL;
    NSDictionary *_parameters;
    NSDictionary *_requestBody;
    NSDictionary *_HTTPHeaders;
}

@property(nonatomic) _Bool encodingEnabled; // @synthesize encodingEnabled=_encodingEnabled;
@property(retain, nonatomic) NSDictionary *HTTPHeaders; // @synthesize HTTPHeaders=_HTTPHeaders;
@property(retain, nonatomic) NSDictionary *requestBody; // @synthesize requestBody=_requestBody;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) NSURL *backupURL; // @synthesize backupURL=_backupURL;
@property(retain, nonatomic) NSURL *targetURL; // @synthesize targetURL=_targetURL;
- (void).cxx_destruct;

@end

