//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ALRequestMeasurement : NSObject
{
    long long _timestampMilliseconds;
    NSString *_URLHostAndPathString;
    unsigned long long _responseSize;
    long long _connectionTimeMilliseconds;
}

@property(nonatomic) long long connectionTimeMilliseconds; // @synthesize connectionTimeMilliseconds=_connectionTimeMilliseconds;
@property(nonatomic) unsigned long long responseSize; // @synthesize responseSize=_responseSize;
@property(copy, nonatomic) NSString *URLHostAndPathString; // @synthesize URLHostAndPathString=_URLHostAndPathString;
@property(nonatomic) long long timestampMilliseconds; // @synthesize timestampMilliseconds=_timestampMilliseconds;
- (void).cxx_destruct;
- (id)description;
- (id)initWithURL:(id)arg1 responseSize:(unsigned long long)arg2 connectionTimeMilliseconds:(long long)arg3;

@end

