//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALRequestEncodingUtils : NSObject
{
}

+ (id)safeBase64DecodeData:(id)arg1;
+ (id)safeBase64EncodeData:(id)arg1;
+ (id)createSignatureForSalt:(id)arg1;
+ (id)createEncodingKeyUsingPrivateSdkKey:(id)arg1 salt:(id)arg2;
+ (id)decodeDataIfNeeded:(id)arg1 usingSdkKey:(id)arg2 salt:(id)arg3;
+ (id)decodeDataIfNeeded:(id)arg1 usingSdkKey:(id)arg2;
+ (id)encodeData:(id)arg1 usingSdkKey:(id)arg2 timestampMilliseconds:(id)arg3 salt:(id)arg4;
+ (id)encodeData:(id)arg1 usingSdkKey:(id)arg2 timestampMilliseconds:(id)arg3;

@end

