//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface ALRequestParameters : NSObject
{
    NSDictionary *_extraParameters;
}

+ (id)requestWithBuilderBlock:(CDUnknownBlockType)arg1 sdk:(id)arg2;
@property(retain, nonatomic) NSDictionary *extraParameters; // @synthesize extraParameters=_extraParameters;
- (void).cxx_destruct;
- (id)description;
- (id)initWithBuilder:(id)arg1;
- (id)init;

@end

