//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ALSdkSettings : NSObject
{
    _Bool _isTestAdsEnabled;
    _Bool _muted;
    _Bool _verboseLoggingEnabled;
    _Bool _createdInternally;
    NSString *_autoPreloadAdSizes;
    NSString *_autoPreloadAdTypes;
}

+ (id)internalSettings;
+ (void)initialize;
@property(nonatomic, getter=isCreatedInternally) _Bool createdInternally; // @synthesize createdInternally=_createdInternally;
@property(copy) NSString *autoPreloadAdTypes; // @synthesize autoPreloadAdTypes=_autoPreloadAdTypes;
@property(copy) NSString *autoPreloadAdSizes; // @synthesize autoPreloadAdSizes=_autoPreloadAdSizes;
@property _Bool verboseLoggingEnabled; // @synthesize verboseLoggingEnabled=_verboseLoggingEnabled;
@property _Bool muted; // @synthesize muted=_muted;
@property _Bool isTestAdsEnabled; // @synthesize isTestAdsEnabled=_isTestAdsEnabled;
- (void).cxx_destruct;
- (id)description;
@property _Bool isVerboseLogging; // @dynamic isVerboseLogging;
- (id)init;

@end

