//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALSdk, NSDate;

@interface ALSessionTracker : NSObject
{
    _Bool _appPausedBefore;
    ALSdk *_sdk;
    ALAtomicBoolean *_enabled;
    ALAtomicBoolean *_appPausedAndResumed;
    ALAtomicBoolean *_pausedForClick;
    NSDate *_lastAppPausedDate;
    NSDate *_lastAppResumedDate;
}

@property(retain) NSDate *lastAppResumedDate; // @synthesize lastAppResumedDate=_lastAppResumedDate;
@property(retain) NSDate *lastAppPausedDate; // @synthesize lastAppPausedDate=_lastAppPausedDate;
@property _Bool appPausedBefore; // @synthesize appPausedBefore=_appPausedBefore;
@property(retain) ALAtomicBoolean *pausedForClick; // @synthesize pausedForClick=_pausedForClick;
@property(retain) ALAtomicBoolean *appPausedAndResumed; // @synthesize appPausedAndResumed=_appPausedAndResumed;
@property(retain) ALAtomicBoolean *enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)appResumed:(id)arg1;
- (void)appPaused:(id)arg1;
- (_Bool)getAndResetDidPauseAndResume;
@property(readonly, nonatomic, getter=isSessionTrackingEnabled) _Bool sessionTrackingEnabled; // @dynamic sessionTrackingEnabled;
- (void)resumeForClick;
- (void)pauseForClick;
- (void)enableSessionTrackingIfNeeded;
- (id)initWithSdk:(id)arg1;

@end

