//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALSignalProviderSpec;
@protocol MASignalCollectionDelegate;

@interface ALSignalCollectionState : NSObject
{
    ALSignalProviderSpec *_signalProviderSpec;
    id <MASignalCollectionDelegate> _delegate;
    ALAtomicBoolean *_collectionCompleted;
}

@property(retain, nonatomic) ALAtomicBoolean *collectionCompleted; // @synthesize collectionCompleted=_collectionCompleted;
@property(retain, nonatomic) id <MASignalCollectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ALSignalProviderSpec *signalProviderSpec; // @synthesize signalProviderSpec=_signalProviderSpec;
- (void).cxx_destruct;
- (id)initWithSignalProviderSpec:(id)arg1 delegate:(id)arg2;

@end

