//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSignalProviderSpec, NSString;

@interface ALSignalCollectionResult : NSObject
{
    ALSignalProviderSpec *_signalProviderSpec;
    NSString *_SDKVersion;
    NSString *_adapterVersion;
    NSString *_signalData;
    NSString *_errorMessage;
}

+ (id)createErrorWithSignalProviderSpec:(id)arg1 adapterWrapper:(id)arg2 errorMessage:(id)arg3;
+ (id)createErrorWithSignalProviderSpec:(id)arg1 errorMessage:(id)arg2;
+ (id)createSuccessWithSignalProviderSpec:(id)arg1 adapterWrapper:(id)arg2 signalData:(id)arg3;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(copy, nonatomic) NSString *signalData; // @synthesize signalData=_signalData;
@property(copy, nonatomic) NSString *adapterVersion; // @synthesize adapterVersion=_adapterVersion;
@property(copy, nonatomic) NSString *SDKVersion; // @synthesize SDKVersion=_SDKVersion;
@property(retain, nonatomic) ALSignalProviderSpec *signalProviderSpec; // @synthesize signalProviderSpec=_signalProviderSpec;
- (void).cxx_destruct;
- (id)description;
- (id)initWithSignalProviderSpec:(id)arg1 adapterWrapper:(id)arg2 signalData:(id)arg3 errorMessage:(id)arg4;

@end

