//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALMediationAdapterSpec.h"

@interface ALSignalProviderSpec : ALMediationAdapterSpec
{
}

- (id)description;
@property(readonly, nonatomic, getter=shouldOnlyCollectSignalWhenInitialized) _Bool onlyCollectSignalWhenInitialized; // @dynamic onlyCollectSignalWhenInitialized;
@property(readonly, nonatomic) long long maxSignalLength; // @dynamic maxSignalLength;

@end

