//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ALStoreKitProductViewControllerDelegate-Protocol.h"

@class ALAdView, ALLogger, ALSdk, ALStoreKitWindow, NSMutableDictionary;

@interface ALStoreKitService : NSObject <ALStoreKitProductViewControllerDelegate>
{
    ALSdk *_sdk;
    NSMutableDictionary *_storeKitViewControllers;
    NSMutableDictionary *_storeKitShownCount;
    ALStoreKitWindow *_storeKitWindow;
    ALAdView *_currentPausedAdView;
}

@property(nonatomic) __weak ALAdView *currentPausedAdView; // @synthesize currentPausedAdView=_currentPausedAdView;
@property(retain, nonatomic) ALStoreKitWindow *storeKitWindow; // @synthesize storeKitWindow=_storeKitWindow;
@property(retain, nonatomic) NSMutableDictionary *storeKitShownCount; // @synthesize storeKitShownCount=_storeKitShownCount;
@property(retain, nonatomic) NSMutableDictionary *storeKitViewControllers; // @synthesize storeKitViewControllers=_storeKitViewControllers;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (id)initWithSdk:(id)arg1;
@property(readonly, nonatomic) ALLogger *logger; // @dynamic logger;
@property(readonly, nonatomic, getter=isStoreKitShowing) _Bool storeKitShowing; // @dynamic storeKitShowing;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)presentStoreKitForAd:(id)arg1 fromAdView:(id)arg2 onViewController:(id)arg3;
- (void)didReturnFromAppStore:(id)arg1;
- (id)clickDestinationForAd:(id)arg1 webViewURL:(id)arg2;
- (void)redirectStoreKitForAd:(id)arg1 fromAdView:(id)arg2;
- (_Bool)shouldSkipPreloadForAd:(id)arg1;
- (void)preloadStoreKitIfNeededForAd:(id)arg1 adView:(id)arg2 interstitialViewController:(id)arg3;
- (void)openClickDestinationIfNeededForAd:(id)arg1 webViewURL:(id)arg2 fromAdView:(id)arg3;
- (void)showStoreKitControllerForNativeAd:(id)arg1;
- (void)showStoreKitControllerForAd:(id)arg1 inAdView:(id)arg2;
- (void)showStoreKitControllerForAd:(id)arg1 fromViewController:(id)arg2 asPoststitial:(_Bool)arg3;
- (void)preloadStoreKitIfNeededForAd:(id)arg1 adView:(id)arg2 interstitialViewController:(id)arg3 delayMs:(long long)arg4;
- (void)preloadStoreKitIfNeededForAd:(id)arg1 delayMs:(long long)arg2;

@end

