//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface ALStack : NSObject <NSCopying, NSCoding>
{
    NSMutableArray *_backingArray;
    NSObject *_lock;
}

+ (id)stackWithCapacity:(unsigned long long)arg1;
+ (id)stack;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableArray *backingArray; // @synthesize backingArray=_backingArray;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty; // @dynamic empty;
@property(readonly, nonatomic) unsigned long long count; // @dynamic count;
- (id)objectAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) id lastObject; // @dynamic lastObject;
@property(readonly, nonatomic) id firstObject; // @dynamic firstObject;
- (void)push:(id)arg1;
- (id)pop;
- (id)peek;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)init;

@end

