//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALSdk;

@interface ALStoreKitVisibilityTracker : NSObject
{
    ALSdk *_sdk;
    ALAtomicBoolean *_showing;
    double _storeKitDisplayedTimestamp;
}

@property(nonatomic) double storeKitDisplayedTimestamp; // @synthesize storeKitDisplayedTimestamp=_storeKitDisplayedTimestamp;
@property(retain, nonatomic) ALAtomicBoolean *showing; // @synthesize showing=_showing;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)setStoreKitHidden;
- (void)setStoreKitDisplayed;
@property(readonly, nonatomic, getter=isStoreKitShowing) _Bool storeKitShowing; // @dynamic storeKitShowing;
- (id)initWithSdk:(id)arg1;

@end

