//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKit/SKStoreProductViewController.h>

#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class ALAdView, ALBaseVideoViewController, ALSdk, NSString;
@protocol ALStoreKitAd, ALStoreKitProductViewControllerDelegate;

@interface ALStoreKitProductViewController : SKStoreProductViewController <SKStoreProductViewControllerDelegate>
{
    _Bool _loadError;
    _Bool _asPoststitial;
    id <ALStoreKitProductViewControllerDelegate> _storeViewControllerDelegate;
    id <ALStoreKitAd> _ad;
    ALAdView *_adView;
    ALBaseVideoViewController *_interstitialViewController;
    ALSdk *_sdk;
    long long _originalStatusBarStyle;
    long long _startLoadTimestampMillis;
}

@property(nonatomic) long long startLoadTimestampMillis; // @synthesize startLoadTimestampMillis=_startLoadTimestampMillis;
@property(nonatomic) long long originalStatusBarStyle; // @synthesize originalStatusBarStyle=_originalStatusBarStyle;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) _Bool asPoststitial; // @synthesize asPoststitial=_asPoststitial;
@property(nonatomic, getter=hasLoadError) _Bool loadError; // @synthesize loadError=_loadError;
@property(retain, nonatomic) ALBaseVideoViewController *interstitialViewController; // @synthesize interstitialViewController=_interstitialViewController;
@property(retain, nonatomic) ALAdView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) id <ALStoreKitAd> ad; // @synthesize ad=_ad;
@property(nonatomic) __weak id <ALStoreKitProductViewControllerDelegate> storeViewControllerDelegate; // @synthesize storeViewControllerDelegate=_storeViewControllerDelegate;
- (void).cxx_destruct;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillAppear:(_Bool)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)loadProductWithParameters:(id)arg1;
@property(readonly, nonatomic, getter=isReady) _Bool ready; // @dynamic ready;
- (id)initWithAd:(id)arg1 inAdView:(id)arg2 interstitialViewController:(id)arg3 sdk:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

