//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class ALMediationAdapterWrapper, ALSignalCollectionState;

@interface ALTaskTimeoutSignalCollection : ALTask
{
    ALMediationAdapterWrapper *_parentAdapterWrapper;
    ALSignalCollectionState *_collectionState;
}

@property(retain, nonatomic) ALSignalCollectionState *collectionState; // @synthesize collectionState=_collectionState;
@property(nonatomic) __weak ALMediationAdapterWrapper *parentAdapterWrapper; // @synthesize parentAdapterWrapper=_parentAdapterWrapper;
- (void).cxx_destruct;
- (id)key;
- (void)run;
- (id)initWithCollectionState:(id)arg1 parentAdapterWrapper:(id)arg2 sdk:(id)arg3;

@end

