//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

#import "ALConnectionManagerDelegate-Protocol.h"

@class ALAtomicBoolean, NSString;

@interface ALTaskFetchBasicSettings : ALTask <ALConnectionManagerDelegate>
{
    ALAtomicBoolean *_isSdkInitializationStarted;
}

@property(retain, nonatomic) ALAtomicBoolean *isSdkInitializationStarted; // @synthesize isSdkInitializationStarted=_isSdkInitializationStarted;
- (void).cxx_destruct;
- (id)key;
- (void)maybeStartSdkInitializationWithResponse:(id)arg1;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (double)defaultTimeout;
- (id)body;
- (id)parameters;
@property(readonly, copy, nonatomic) NSString *fetchBackupDomain; // @dynamic fetchBackupDomain;
@property(readonly, copy, nonatomic) NSString *fetchDomain; // @dynamic fetchDomain;
- (void)run;
- (id)initWithSdk:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

