//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class NSArray;
@protocol ALNativeAdPrecacheDelegate;

@interface ALTaskCacheNativeAdBase : ALTask
{
    id <ALNativeAdPrecacheDelegate> _precacheDelegate;
    NSArray *_nativeAds;
}

@property(retain, nonatomic) NSArray *nativeAds; // @synthesize nativeAds=_nativeAds;
@property(retain, nonatomic) id <ALNativeAdPrecacheDelegate> precacheDelegate; // @synthesize precacheDelegate=_precacheDelegate;
- (void).cxx_destruct;
- (id)cacheFile:(id)arg1 withFileManager:(id)arg2 resourcePrefixes:(id)arg3;
- (void)run;
- (id)initWithNativeAds:(id)arg1 tag:(id)arg2 sdk:(id)arg3 andNotify:(id)arg4;

@end

