//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class MAAdFormat;

@interface ALTaskCollectSignals : ALTask
{
    _Bool _isFallbackAd;
    MAAdFormat *_adFormat;
    CDUnknownBlockType _completion;
}

+ (id)createSignalProviderWithName:(id)arg1 class:(id)arg2;
+ (id)createDefaultSignalProviders;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool isFallbackAd; // @synthesize isFallbackAd=_isFallbackAd;
@property(nonatomic) __weak MAAdFormat *adFormat; // @synthesize adFormat=_adFormat;
- (void).cxx_destruct;
- (id)key;
- (id)truncateString:(id)arg1 withMaxLengthSetting:(id)arg2;
- (void)notifySignalsCollected:(id)arg1;
- (void)notifySignalCollectionFailedForErrorMessage:(id)arg1 exception:(id)arg2;
- (void)collectSignalForSpec:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)collectSignalsForSignalProviders:(id)arg1 fullResponse:(id)arg2;
- (void)run;
- (id)initWithAdFormat:(id)arg1 isFallbackAd:(_Bool)arg2 sdk:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

