//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskValidateReward.h"

@class ALDirectAd, ALIncentivizedDelegateProxy;

@interface ALTaskValidateAppLovinReward : ALTaskValidateReward
{
    ALDirectAd *_ad;
    ALIncentivizedDelegateProxy *_rewardDelegate;
}

@property(retain, nonatomic) ALIncentivizedDelegateProxy *rewardDelegate; // @synthesize rewardDelegate=_rewardDelegate;
@property(retain, nonatomic) ALDirectAd *ad; // @synthesize ad=_ad;
- (void).cxx_destruct;
- (_Bool)isTaskCancelled;
- (void)handleRequestFailedWithResponseCode:(long long)arg1;
- (void)handlePendingReward:(id)arg1;
- (void)updateRequestWithTaskSpecificParameters:(id)arg1;
- (id)endpoint;
- (id)key;
- (id)initWithAd:(id)arg1 sdk:(id)arg2 andNotify:(id)arg3;

@end

