//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

#import "ALConnectionManagerDelegate-Protocol.h"

@class ALVASTContext, NSString;
@protocol ALAdLoadDelegate;

@interface ALTaskResolveVASTWrapper : ALTask <ALConnectionManagerDelegate>
{
    ALVASTContext *_context;
    id <ALAdLoadDelegate> _adLoadDelegate;
}

@property(retain, nonatomic) id <ALAdLoadDelegate> adLoadDelegate; // @synthesize adLoadDelegate=_adLoadDelegate;
@property(retain, nonatomic) ALVASTContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)key;
@property(readonly, nonatomic) double defaultTimeout; // @dynamic defaultTimeout;
- (void)failResponseProcessingWithConnectionErrorCode:(long long)arg1;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (void)run;
- (id)initWithContext:(id)arg1 adLoadDelegate:(id)arg2 SDK:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

