//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class NSDictionary;
@protocol ALAdLoadDelegate;

@interface ALTaskRenderAd : ALTask
{
    NSDictionary *_adObject;
    NSDictionary *_fullAdResponse;
    unsigned long long _source;
    id <ALAdLoadDelegate> _adLoadDelegate;
}

@property(retain, nonatomic) id <ALAdLoadDelegate> adLoadDelegate; // @synthesize adLoadDelegate=_adLoadDelegate;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(retain, nonatomic) NSDictionary *fullAdResponse; // @synthesize fullAdResponse=_fullAdResponse;
@property(retain, nonatomic) NSDictionary *adObject; // @synthesize adObject=_adObject;
- (void).cxx_destruct;
- (void)processAd:(id)arg1;
- (void)run;
- (id)initWithAdObject:(id)arg1 fullAdResponse:(id)arg2 source:(unsigned long long)arg3 adLoadDelegate:(id)arg4 tag:(id)arg5 sdk:(id)arg6;

@end

