//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

#import "ALConnectionManagerDelegate-Protocol.h"

@class ALConnectionStatsTracker, ALHTTPRequest, ALSetting, NSString;
@protocol ALConnectionManagerDelegate;

@interface ALTaskRepeatRequest : ALTask <ALConnectionManagerDelegate>
{
    ALHTTPRequest *_request;
    id <ALConnectionManagerDelegate> _delegate;
    unsigned long long _retryQueue;
    ALSetting *_endpointTypeToClear;
    ALSetting *_backupEndpointTypeToClear;
    ALConnectionStatsTracker *_statsTracker;
}

@property(retain, nonatomic) ALConnectionStatsTracker *statsTracker; // @synthesize statsTracker=_statsTracker;
@property(nonatomic) ALSetting *backupEndpointTypeToClear; // @synthesize backupEndpointTypeToClear=_backupEndpointTypeToClear;
@property(nonatomic) ALSetting *endpointTypeToClear; // @synthesize endpointTypeToClear=_endpointTypeToClear;
@property(nonatomic) unsigned long long retryQueue; // @synthesize retryQueue=_retryQueue;
@property(retain, nonatomic) id <ALConnectionManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ALHTTPRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (id)key;
- (void)clearSettingTypeIfNeeded:(id)arg1;
- (_Bool)connectionVia:(id)arg1 requiresResponseForRequest:(id)arg2;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (void)run;
- (id)initWithRequest:(id)arg1 delegate:(id)arg2 sdk:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

