//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskProcessVASTResponse.h"

@class ALXMLNode;

@interface ALTaskProcessVASTWrapperResponse : ALTaskProcessVASTResponse
{
    ALXMLNode *_vastWrapperResponse;
}

@property(retain, nonatomic) ALXMLNode *vastWrapperResponse; // @synthesize vastWrapperResponse=_vastWrapperResponse;
- (void).cxx_destruct;
- (id)key;
- (void)run;
- (id)initWithVASTWrapperResponse:(id)arg1 context:(id)arg2 adLoadDelegate:(id)arg3 sdk:(id)arg4;

@end

