//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class ALLogger, ALSdk, ALTaskKey, NSString;

@interface ALTask : NSOperation
{
    _Bool _runWhileInitializing;
    ALSdk *_sdk;
    NSString *_tag;
}

@property(nonatomic) _Bool runWhileInitializing; // @synthesize runWhileInitializing=_runWhileInitializing;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
@property(readonly, nonatomic) ALTaskKey *key; // @dynamic key;
@property(readonly, nonatomic) ALLogger *logger; // @dynamic logger;
- (void)e:(id)arg1 becauseOf:(id)arg2;
- (void)e:(id)arg1;
- (void)w:(id)arg1;
- (void)i:(id)arg1;
- (void)d:(id)arg1;
- (void)main;
- (void)run;
- (id)initWithTag:(id)arg1 sdk:(id)arg2;

@end

