//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSNumber, NSString;

@interface ALTaskStats : NSObject <NSCoding>
{
    NSString *_key;
    long long _count;
    long long _exceptionCount;
    double _mean;
    double _variance;
    NSNumber *_high;
    NSNumber *_low;
}

@property(retain, nonatomic) NSNumber *low; // @synthesize low=_low;
@property(retain, nonatomic) NSNumber *high; // @synthesize high=_high;
@property(nonatomic) double variance; // @synthesize variance=_variance;
@property(nonatomic) double mean; // @synthesize mean=_mean;
@property(nonatomic) long long exceptionCount; // @synthesize exceptionCount=_exceptionCount;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)description;
- (id)toJson;
- (void)incrementExceptionCount;
- (void)collectDuration:(long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithKey:(id)arg1;

@end

