//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class ALMutableVASTContext;
@protocol ALAdLoadDelegate;

@interface ALTaskProcessVASTResponse : ALTask
{
    id <ALAdLoadDelegate> _adLoadDelegate;
    ALMutableVASTContext *_context;
}

+ (id)taskWithVASTWrapperResponse:(id)arg1 context:(id)arg2 adLoadDelegate:(id)arg3 sdk:(id)arg4;
+ (id)taskWithAdObject:(id)arg1 fullAdResponse:(id)arg2 source:(unsigned long long)arg3 adLoadDelegate:(id)arg4 sdk:(id)arg5;
@property(retain, nonatomic) ALMutableVASTContext *context; // @synthesize context=_context;
@property(retain, nonatomic) id <ALAdLoadDelegate> adLoadDelegate; // @synthesize adLoadDelegate=_adLoadDelegate;
- (void).cxx_destruct;
- (void)failProcessingWithErrorCode:(long long)arg1;
- (void)processResponse:(id)arg1;
- (id)initWithContext:(id)arg1 adLoadDelegate:(id)arg2 tag:(id)arg3 sdk:(id)arg4;

@end

