//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskProcessVASTResponse.h"

@class NSDictionary;

@interface ALTaskProcessSDKVASTResponse : ALTaskProcessVASTResponse
{
    NSDictionary *_sdkVASTResponse;
}

@property(retain, nonatomic) NSDictionary *sdkVASTResponse; // @synthesize sdkVASTResponse=_sdkVASTResponse;
- (void).cxx_destruct;
- (id)key;
- (void)run;
- (id)initWithContext:(id)arg1 adLoadDelegate:(id)arg2 sdk:(id)arg3;

@end

