//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class NSDictionary, NSString;
@protocol MAAdDelegate;

@interface ALTaskLoadAdapterAd : ALTask
{
    NSString *_adUnitIdentifier;
    NSDictionary *_adObject;
    NSDictionary *_fullAdResponse;
    id <MAAdDelegate> _delegate;
}

@property(retain, nonatomic) id <MAAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *fullAdResponse; // @synthesize fullAdResponse=_fullAdResponse;
@property(retain, nonatomic) NSDictionary *adObject; // @synthesize adObject=_adObject;
@property(copy, nonatomic) NSString *adUnitIdentifier; // @synthesize adUnitIdentifier=_adUnitIdentifier;
- (void).cxx_destruct;
- (id)key;
- (id)createMediatedAd;
- (void)run;
- (id)initWithAdUnitIdentifier:(id)arg1 adObject:(id)arg2 fullAdResponse:(id)arg3 sdk:(id)arg4 andNotify:(id)arg5;

@end

