//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskValidateReward.h"

@class ALMediatedFullscreenAd;

@interface ALTaskValidateMAXReward : ALTaskValidateReward
{
    ALMediatedFullscreenAd *_fullscreenAd;
}

@property(retain, nonatomic) ALMediatedFullscreenAd *fullscreenAd; // @synthesize fullscreenAd=_fullscreenAd;
- (void).cxx_destruct;
- (_Bool)isTaskCancelled;
- (void)handleRequestFailedWithResponseCode:(long long)arg1;
- (void)handlePendingReward:(id)arg1;
- (void)updateRequestWithTaskSpecificParameters:(id)arg1;
- (id)endpoint;
- (id)key;
- (id)initWithFullScreenAd:(id)arg1 sdk:(id)arg2;

@end

