//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskReportReward.h"

@class ALMediatedFullscreenAd;

@interface ALTaskReportMAXReward : ALTaskReportReward
{
    ALMediatedFullscreenAd *_ad;
}

@property(retain, nonatomic) ALMediatedFullscreenAd *ad; // @synthesize ad=_ad;
- (void).cxx_destruct;
- (void)handlePendingRewardNotFound;
- (void)handleRequestFailedWithResponseCode:(long long)arg1;
- (void)handleRequestSuccessfulWithResponse:(id)arg1;
- (id)getAndRemovePendingReward;
- (void)updateRequestWithTaskSpecificParameters:(id)arg1;
- (id)endpoint;
- (id)key;
- (id)initWithFullScreenAd:(id)arg1 sdk:(id)arg2;

@end

