//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

#import "ALConnectionManagerDelegate-Protocol.h"

@class ALPostbackHTTPRequest, NSString;
@protocol ALPostbackDelegate;

@interface ALTaskDispatchPostback : ALTask <ALConnectionManagerDelegate>
{
    ALPostbackHTTPRequest *_request;
    unsigned long long _executionQueue;
    id <ALPostbackDelegate> _delegate;
}

@property(retain, nonatomic) id <ALPostbackDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long executionQueue; // @synthesize executionQueue=_executionQueue;
@property(retain, nonatomic) ALPostbackHTTPRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (id)key;
- (_Bool)connectionVia:(id)arg1 requiresResponseForRequest:(id)arg2;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (void)run;
- (id)initWithRequest:(id)arg1 executionQueue:(unsigned long long)arg2 delegate:(id)arg3 sdk:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

