//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@protocol ALConnectionManagerDelegate;

@interface ALTaskFetchMediationDebuggerInfo : ALTask
{
    id <ALConnectionManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <ALConnectionManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)key;
- (double)defaultTimeout;
- (id)fetchParameters;
- (id)fetchBackupDomain;
- (id)fetchDomain;
- (void)run;
- (id)initWithDelegate:(id)arg1 sdk:(id)arg2;

@end

