//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskCacheAd.h"

@class ALAdServerAd;

@interface ALTaskCacheAppLovinAd : ALTaskCacheAd
{
    _Bool _loadVideoStreamingAdImmediately;
    _Bool _loadGraphicStreamingAdImmediately;
}

@property(nonatomic) _Bool loadGraphicStreamingAdImmediately; // @synthesize loadGraphicStreamingAdImmediately=_loadGraphicStreamingAdImmediately;
@property(nonatomic) _Bool loadVideoStreamingAdImmediately; // @synthesize loadVideoStreamingAdImmediately=_loadVideoStreamingAdImmediately;
- (id)key;
@property(readonly, nonatomic) ALAdServerAd *adServerAd; // @dynamic adServerAd;
- (void)cacheVideoIfNeeded;
- (void)cacheHTMLResources;
- (void)run;
- (id)initWithAd:(id)arg1 sdk:(id)arg2 andNotify:(id)arg3;

@end

