//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class ALTaskProcessMediationWaterfall, NSArray;

@interface ALTaskProcessNextWaterfallAd : ALTask
{
    long long _currentAdIndex;
    NSArray *_adObjects;
    ALTaskProcessMediationWaterfall *_parentTask;
}

@property(retain, nonatomic) ALTaskProcessMediationWaterfall *parentTask; // @synthesize parentTask=_parentTask;
@property(retain, nonatomic) NSArray *adObjects; // @synthesize adObjects=_adObjects;
@property(nonatomic) long long currentAdIndex; // @synthesize currentAdIndex=_currentAdIndex;
- (void).cxx_destruct;
- (id)key;
- (id)parseAdTypeAtIndex:(long long)arg1;
- (void)tryRenderingNextAd;
- (void)run;
- (id)initWithCurrentAdIndex:(long long)arg1 ads:(id)arg2 parentTask:(id)arg3 sdk:(id)arg4;

@end

