//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskRenderAd.h"

@interface ALTaskRenderAppLovinAd : ALTaskRenderAd
{
}

- (id)key;
- (void)processAd:(id)arg1;
- (id)initWithAdObject:(id)arg1 fullAdResponse:(id)arg2 source:(unsigned long long)arg3 adLoadDelegate:(id)arg4 sdk:(id)arg5;

@end

