//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTaskFetchNextAd.h"

@protocol ALNativeAdLoadDelegate;

@interface ALTaskFetchNextNativeAd : ALTaskFetchNextAd
{
    unsigned long long _count;
    id <ALNativeAdLoadDelegate> _nativeAdLoadDelegate;
}

@property(retain, nonatomic) id <ALNativeAdLoadDelegate> nativeAdLoadDelegate; // @synthesize nativeAdLoadDelegate=_nativeAdLoadDelegate;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
- (void).cxx_destruct;
- (id)key;
- (id)createRenderTaskWithResponse:(id)arg1;
- (void)notifyLoadDelegateOfFailureWithResponseCode:(long long)arg1;
- (id)adBackupEndpointDomain;
- (id)adEndpointDomain;
- (id)fetchTaskSpecificParameters;
- (id)initWithZoneIdentifier:(id)arg1 count:(unsigned long long)arg2 sdk:(id)arg3 andNotify:(id)arg4;

@end

