//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@interface ALTaskAutoInitAdapters : ALTask
{
}

- (id)key;
- (id)mediationAdapterSpecsFromRawSpecs:(id)arg1 fullResponse:(id)arg2;
- (id)testModeMediationAdapterSpecsFromFullResponse:(id)arg1;
- (id)mergedAutoInitSpecsFromRawSpecs:(id)arg1 fullResponse:(id)arg2;
- (void)run;
- (id)initWithSdk:(id)arg1;

@end

