//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

@class ALCacheStatsTracker, ALDirectAd, ALFileManager;
@protocol ALAdLoadDelegate;

@interface ALTaskCacheAd : ALTask
{
    _Bool _stopCaching;
    ALDirectAd *_ad;
    id <ALAdLoadDelegate> _adLoadDelegate;
    ALCacheStatsTracker *_cacheStatsTracker;
    CDUnknownBlockType _endBackgroundTaskBlock;
}

@property(copy, nonatomic) CDUnknownBlockType endBackgroundTaskBlock; // @synthesize endBackgroundTaskBlock=_endBackgroundTaskBlock;
@property(nonatomic, getter=shouldStopCaching) _Bool stopCaching; // @synthesize stopCaching=_stopCaching;
@property(retain, nonatomic) ALCacheStatsTracker *cacheStatsTracker; // @synthesize cacheStatsTracker=_cacheStatsTracker;
@property(retain, nonatomic) id <ALAdLoadDelegate> adLoadDelegate; // @synthesize adLoadDelegate=_adLoadDelegate;
@property(retain, nonatomic) ALDirectAd *ad; // @synthesize ad=_ad;
- (void).cxx_destruct;
- (void)trackCachedStatsForAd:(id)arg1;
- (void)callbackAdLoadSuccessIfNeeded;
- (void)callbackAdLoadFailed;
@property(readonly, nonatomic) ALFileManager *fileManager; // @dynamic fileManager;
- (_Bool)isResponseSuccess:(id)arg1;
- (_Bool)cacheData:(id)arg1 forResourceName:(id)arg2 useTemporaryDirectory:(_Bool)arg3;
- (id)loadResourceAtPath:(id)arg1 resourcePrefixes:(id)arg2 respectWhitelist:(_Bool)arg3;
- (_Bool)loadAndCacheResource:(id)arg1 forName:(id)arg2 resourcePrefixes:(id)arg3 respectWhitelist:(_Bool)arg4 statsTracker:(id)arg5 useTemporaryDirectory:(_Bool)arg6;
- (_Bool)loadAndCacheResource:(id)arg1 forName:(id)arg2 resourcePrefixes:(id)arg3;
- (id)cacheResourceAtPath:(id)arg1 resourcePrefixes:(id)arg2 respectWhitelist:(_Bool)arg3 statsTracker:(id)arg4 useTemporaryDirectory:(_Bool)arg5;
- (id)cacheResourceAtPath:(id)arg1;
- (id)cacheStringResourceAtPath:(id)arg1 resourcePrefixes:(id)arg2 respectWhitelist:(_Bool)arg3 statsTracker:(id)arg4;
- (id)cacheStringResourceAtPath:(id)arg1 resourcePrefixes:(id)arg2;
- (id)cacheHTMLResource:(id)arg1 forPrefix:(id)arg2 useTemporaryDirectory:(_Bool)arg3;
- (id)cacheHTMLResources:(id)arg1 resourcePrefixes:(id)arg2 useTemporaryDirectory:(_Bool)arg3 forAd:(id)arg4;
- (id)cacheVideoIfNeeded:(id)arg1 resourcePrefixes:(id)arg2 respectWhitelist:(_Bool)arg3;
- (id)cacheVideoIfNeeded:(id)arg1;
- (void)cacheMuteImages;
- (void)mediatedAdTimedOut:(id)arg1;
- (void)setCachingFinished;
- (void)run;
- (id)initWithAd:(id)arg1 tag:(id)arg2 sdk:(id)arg3 andNotify:(id)arg4;

@end

