//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTask.h"

#import "ALAdFetching-Protocol.h"

@class ALAdZone, ALConnectionStatsTracker, NSMutableDictionary, NSString;

@interface ALTaskFetchNextAd : ALTask <ALAdFetching>
{
    _Bool _isPreloading;
    id _delegate;
    ALAdZone *_requiredZone;
    ALConnectionStatsTracker *_statsTracker;
}

@property(retain, nonatomic) ALConnectionStatsTracker *statsTracker; // @synthesize statsTracker=_statsTracker;
@property(retain, nonatomic) ALAdZone *requiredZone; // @synthesize requiredZone=_requiredZone;
@property(retain, nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isPreloading; // @synthesize isPreloading=_isPreloading;
- (void).cxx_destruct;
- (id)key;
- (double)defaultTimeout;
- (void)updateSessionStats;
@property(readonly, nonatomic) unsigned long long source; // @dynamic source;
@property(readonly, copy, nonatomic) NSString *adBackupEndpointDomain; // @dynamic adBackupEndpointDomain;
@property(readonly, copy, nonatomic) NSString *adEndpointDomain; // @dynamic adEndpointDomain;
@property(readonly, nonatomic) NSMutableDictionary *fetchTaskSpecificParameters; // @dynamic fetchTaskSpecificParameters;
- (void)notifyLoadDelegateOfFailureWithResponseCode:(long long)arg1;
- (id)createRenderTaskWithResponse:(id)arg1;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (void)run;
- (id)initWithZone:(id)arg1 tag:(id)arg2 sdk:(id)arg3;
- (id)initWithZone:(id)arg1 sdk:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

