//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALTimeUnit : NSObject
{
}

+ (id)days;
+ (id)hours;
+ (id)minutes;
+ (id)seconds;
+ (id)milliseconds;
+ (void)initialize;
- (double)divide:(unsigned long long)arg1 b:(double)arg2;
- (double)multiply:(unsigned long long)arg1 b:(unsigned long long)arg2;

@end

