//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;

@interface ALTimer : NSObject
{
    NSTimer *_currentTimer;
    double _startTime;
    double _fireTime;
    CDUnknownBlockType _wrappedTimerBlock;
    double _elapsedTime;
    NSObject *_stateLock;
}

+ (id)scheduledTimerWithTimeInterval:(double)arg1 sdk:(id)arg2 repeats:(_Bool)arg3 block:(CDUnknownBlockType)arg4;
+ (id)scheduledTimerWithTimeInterval:(double)arg1 sdk:(id)arg2 block:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSObject *stateLock; // @synthesize stateLock=_stateLock;
@property(nonatomic) double elapsedTime; // @synthesize elapsedTime=_elapsedTime;
@property(copy, nonatomic) CDUnknownBlockType wrappedTimerBlock; // @synthesize wrappedTimerBlock=_wrappedTimerBlock;
@property(nonatomic) double fireTime; // @synthesize fireTime=_fireTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSTimer *currentTimer; // @synthesize currentTimer=_currentTimer;
- (void).cxx_destruct;
- (void)invokeWrappedTimerBlock;
- (void)cancel;
- (void)resume;
- (void)pause;
@property(readonly, nonatomic) double remainingTime; // @dynamic remainingTime;
- (id)init;

@end

