//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALTimeUnit.h"

@interface ALTimeUnitMinutes : ALTimeUnit
{
}

- (double)toDays:(unsigned long long)arg1;
- (double)toHours:(unsigned long long)arg1;
- (double)toMinutes:(unsigned long long)arg1;
- (double)toSeconds:(unsigned long long)arg1;
- (double)toMilliseconds:(unsigned long long)arg1;

@end

