//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWebView.h>

#import "ALWebView-Protocol.h"

@class NSString, UIScrollView;
@protocol UIWebViewDelegate><WKNavigationDelegate;

@interface ALUIWebView : UIWebView <ALWebView>
{
}

@property(readonly, copy) NSString *description;
- (void)setScrollsToTop:(_Bool)arg1;
- (void)evaluateJavaScript:(id)arg1;
@property(nonatomic) __weak id <UIWebViewDelegate><WKNavigationDelegate> bridgingDelegate; // @dynamic bridgingDelegate;
- (void)loadURL:(id)arg1;
- (void)loadHTMLString:(id)arg1;
- (void)clear;
- (void)prepareToLoadAd:(id)arg1;
- (void)baseInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(readonly) Class superclass;

@end

