//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALUserDefaultsKey : NSObject
{
}

+ (id)dynamicKeyWithSdk:(id)arg1;
+ (id)mediationProvider;
+ (id)persistedData;
+ (id)autoInitializeAdapters;
+ (id)signalProviders;
+ (id)adEventStatsKeyForSdk:(id)arg1;
+ (id)globalStatsKeyForSdk:(id)arg1;
+ (id)settingsKeyForSdk:(id)arg1;
+ (id)requestTrackerCounter;
+ (id)eventTrackingSuperProperties;
+ (id)networkResponseCodeMapping;
+ (id)taskStats;
+ (id)errors;
+ (id)isAgeRestrictedUser;
+ (id)hasUserConsent;
+ (id)adaptersToLoadNextInit;
+ (id)applovinRandomToken;
+ (id)compassRandomToken;
+ (id)compassRandomTokenOld;
+ (id)userIdentifier;
+ (id)variablesKey;
+ (id)deviceTestGroup;
+ (id)launchedBefore;
+ (id)isFirstRun;

@end

