//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, NSString;

@interface ALUserTokenManager : NSObject
{
    NSString *_userIdentifier;
    NSString *_compassRandomToken;
    NSString *_applovinRandomToken;
    ALSdk *_sdk;
}

@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(copy, nonatomic) NSString *applovinRandomToken; // @synthesize applovinRandomToken=_applovinRandomToken;
@property(copy, nonatomic) NSString *compassRandomToken; // @synthesize compassRandomToken=_compassRandomToken;
@property(copy, nonatomic) NSString *userIdentifier; // @synthesize userIdentifier=_userIdentifier;
- (void).cxx_destruct;
- (id)retrieveTokenWithUserDefaultsKey:(id)arg1 oldToken:(id)arg2;
- (id)retrieveUserIdentifier;
- (id)initWithSdk:(id)arg1;

@end

