//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALUtils : NSObject
{
}

+ (_Bool)hasInfoPlistValueForKey:(id)arg1;
+ (_Bool)checkExistenceForClass:(id)arg1;
+ (id)sanitizeSuperProperty:(id)arg1 sdk:(id)arg2;
+ (_Bool)object:(id)arg1 isOfType:(id)arg2 sdk:(id)arg3;
+ (CDUnknownBlockType)beginBackgroundTaskExecution;
+ (void)beginBackgroundTaskExecutionWithLimitSeconds:(double)arg1;
+ (id)URLSafeDictionaryFromDictionary:(id)arg1;
+ (void)validateSDKKeyForAd:(id)arg1 sdk:(id)arg2;
+ (id)postbacksForKey:(id)arg1 adObject:(id)arg2 clCode:(id)arg3 eventIdentifier:(id)arg4 additionalPostbackURL:(id)arg5;
+ (id)postbacksForKey:(id)arg1 adObject:(id)arg2 clCode:(id)arg3 additionalPostbackURL:(id)arg4;
+ (id)zoneFromFullAdResponse:(id)arg1 withSDK:(id)arg2;
+ (id)constraintsForVisualFormatStrings:(id)arg1 variableBindings:(id)arg2;
+ (id)constraintsForVisualFormatString:(id)arg1 variableBindings:(id)arg2;
+ (id)queryStringFromDictionary:(id)arg1 sdk:(id)arg2;
+ (id)queryDictFromURL:(id)arg1;
+ (unsigned long long)videoCompletionPercentFromAdObject:(id)arg1;
+ (id)retrieveNonDummyAdIfNeededForAd:(id)arg1 usingSDK:(id)arg2;
+ (_Bool)shouldDisplayAd:(id)arg1 usingSDK:(id)arg2;
+ (unsigned long long)currentOrientationMask;
+ (unsigned long long)intersectOfApplicationOrientationsAndProvidedOrientations:(unsigned long long)arg1;
+ (_Bool)supportedOrientationsIntersectWithTargetOrientations:(unsigned long long)arg1 using:(id)arg2;
+ (void)handleFailedAdRenderForAdLoadDelegate:(id)arg1 adService:(id)arg2 zone:(id)arg3 withErrorCode:(long long)arg4 usingSDK:(id)arg5;
+ (void)handleNoFillResponseForPublisherIfNeededForIdentifier:(id)arg1 noFillResponse:(id)arg2 usingSDK:(id)arg3;
+ (id)replaceEventIdentifierMacroInString:(id)arg1 withEventIdentifier:(id)arg2;
+ (id)replaceURLString:(id)arg1 withCLCode:(id)arg2;
+ (id)replacePlacementMacroInURL:(id)arg1;
+ (id)replacePlacementMacroInString:(id)arg1;
+ (_Bool)isDomain:(id)arg1 inWhitelist:(id)arg2;
+ (void)openURL:(id)arg1 usingSDK:(id)arg2;
+ (id)coerceString:(id)arg1;
+ (_Bool)assertValidAd:(id)arg1;
+ (_Bool)string:(id)arg1 al_containsSubstring:(id)arg2;
+ (id)serverAdjustedUnixTimestampInMilliseconds:(id)arg1;
+ (id)timeInMillisecondsFromSeconds:(id)arg1;
+ (id)timeInSecondsFromMilliseconds:(id)arg1;
+ (double)timeIntervalFromMilliseconds:(id)arg1;
+ (_Bool)isView:(id)arg1 inSubview:(id)arg2;
+ (_Bool)parentWindowIntersectsView:(id)arg1 withPercentVisible:(double)arg2;
+ (_Bool)parentWindowIntersectsView:(id)arg1;
+ (id)parentWindowForView:(id)arg1;
+ (_Bool)viewHasHiddenAncestors:(id)arg1;
+ (_Bool)isViewVisible:(id)arg1;
+ (_Bool)isViewInTopViewController:(id)arg1;
+ (id)topViewControllerFromViewController:(id)arg1;
+ (id)topViewControllerFromWindow:(id)arg1;
+ (id)topViewControllerFromKeyWindow;
+ (id)hashOf:(id)arg1 using:(id)arg2 andTrimTo:(unsigned long long)arg3;
+ (id)shortHashOf:(id)arg1 using:(id)arg2;
+ (id)fullHashOf:(id)arg1 using:(id)arg2;
+ (_Bool)isTimeFor:(id)arg1 usingManager:(id)arg2;
+ (_Bool)isTimeFor:(id)arg1 using:(id)arg2;
+ (id)systemVersion;
+ (_Bool)testAdsEnabled;
+ (_Bool)verboseLoggingOn;
+ (_Bool)verboseLoggingConfiguredByPublisher;
+ (id)sdkKey;

@end

