//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALVASTUtils : NSObject
{
}

+ (struct NSMutableSet *)addToTrackersIfNeeded:(struct NSMutableSet *)arg1 forNodes:(id)arg2 context:(id)arg3 usingSDK:(id)arg4;
+ (struct NSMutableSet *)topLevelErrorTrackersFromContext:(id)arg1 usingSDK:(id)arg2;
+ (id)extractTextFromXMLNode:(id)arg1 withChildName:(id)arg2 defaultValue:(id)arg3;
+ (id)lastWrapperResolutionURLFromContext:(id)arg1;
+ (void)renderTrackersFromXMLNodes:(id)arg1 into:(inout struct NSMutableSet *)arg2 context:(id)arg3 usingSDK:(id)arg4;
+ (void)renderEventTrackersFromXMLNode:(id)arg1 into:(inout struct NSMutableDictionary *)arg2 context:(id)arg3 usingSDK:(id)arg4;
+ (void)fireTrackers:(struct NSMutableSet *)arg1 withVideoTimeOffset:(double)arg2 videoAssetURL:(id)arg3 vastErrorCode:(long long)arg4 usingSDK:(id)arg5;
+ (void)fireTrackers:(struct NSMutableSet *)arg1 withVideoTimeOffset:(double)arg2 videoAssetURL:(id)arg3 usingSDK:(id)arg4;
+ (void)fireTrackers:(struct NSMutableSet *)arg1 withVASTErrorCode:(long long)arg2 usingSDK:(id)arg3;
+ (void)fireTrackers:(struct NSMutableSet *)arg1 usingSDK:(id)arg2;
+ (id)currentTimestamp;
+ (id)cacheBuster;
+ (id)formattedTimeForContentPlayhead:(long long)arg1;
+ (id)replaceMacrosInTrackerDestination:(id)arg1 videoTimeOffset:(double)arg2 videoAssetURL:(id)arg3 errorCode:(long long)arg4 usingSDK:(id)arg5;
+ (void)handleFailedAdProcessingForVASTContext:(id)arg1 adLoadDelegate:(id)arg2 withVASTErrorCode:(long long)arg3 appLovinCode:(long long)arg4 usingSDK:(id)arg5;
+ (_Bool)hasValidCompanionAd:(id)arg1;
+ (_Bool)hasValidVideoCreative:(id)arg1;
+ (long long)isValidVASTAd:(id)arg1;

@end

