//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAtomicBoolean, ALSdk, NSDictionary;
@protocol ALVariableServiceDelegate;

@interface ALVariableService : NSObject
{
    id <ALVariableServiceDelegate> _delegate;
    ALSdk *_sdk;
    NSDictionary *_variables;
    NSObject *_variablesLock;
    ALAtomicBoolean *_delegateHasBeenSetAndCalledBefore;
    ALAtomicBoolean *_isFetching;
}

@property(retain, nonatomic) ALAtomicBoolean *isFetching; // @synthesize isFetching=_isFetching;
@property(retain, nonatomic) ALAtomicBoolean *delegateHasBeenSetAndCalledBefore; // @synthesize delegateHasBeenSetAndCalledBefore=_delegateHasBeenSetAndCalledBefore;
@property(retain, nonatomic) NSObject *variablesLock; // @synthesize variablesLock=_variablesLock;
@property(retain, nonatomic) NSDictionary *variables; // @synthesize variables=_variables;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) __weak id <ALVariableServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)description;
- (void)callbackDelegateWithLatestVariablesIfNeeded;
- (void)updateVariables:(id)arg1;
- (id)valueForKey:(id)arg1 defaultValue:(id)arg2 class:(Class)arg3;
- (id)stringForKey:(id)arg1 defaultValue:(id)arg2;
- (id)stringForKey:(id)arg1;
- (_Bool)boolForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)boolForKey:(id)arg1;
- (void)loadVariables;
- (id)initWithSdk:(id)arg1;

@end

