//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALBaseVideoViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class ALVASTAd, NSArray, NSMutableSet, NSString, UITapGestureRecognizer;

@interface ALVASTVideoViewController : ALBaseVideoViewController <UIGestureRecognizerDelegate>
{
    UITapGestureRecognizer *_closeRecognizer;
    NSArray *_currentSkipAndCloseButtonConstraints;
    NSArray *_currentOptOutButtonConstraints;
    id _videoQuartileTimeObserver;
    struct NSMutableSet *_videoProgressTrackers;
}

@property(retain, nonatomic) NSMutableSet *videoProgressTrackers; // @synthesize videoProgressTrackers=_videoProgressTrackers;
@property(retain, nonatomic) id videoQuartileTimeObserver; // @synthesize videoQuartileTimeObserver=_videoQuartileTimeObserver;
@property(retain, nonatomic) NSArray *currentOptOutButtonConstraints; // @synthesize currentOptOutButtonConstraints=_currentOptOutButtonConstraints;
@property(retain, nonatomic) NSArray *currentSkipAndCloseButtonConstraints; // @synthesize currentSkipAndCloseButtonConstraints=_currentSkipAndCloseButtonConstraints;
@property(retain, nonatomic) UITapGestureRecognizer *closeRecognizer; // @synthesize closeRecognizer=_closeRecognizer;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleExtendedCloseAreaTouch:(id)arg1;
- (void)prepareAdditionalTouchAreaIfNeeded;
- (void)prepareBufferIndicatorIfNeeded;
- (void)prepareVideoButtonIfNeeded;
- (void)prepareVideoProgressBar;
- (void)prepareCountdownClock;
- (void)updateConstraintsForSkipAndCloseButtons;
- (void)updateConstraintsForOptOutButton;
- (void)prepareInterface;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)fireTrackers:(struct NSMutableSet *)arg1 errorCode:(long long)arg2;
- (void)fireTrackersOfType:(long long)arg1 forEvent:(id)arg2 errorCode:(long long)arg3;
- (void)fireTrackersOfType:(long long)arg1 forErrorCode:(long long)arg2;
- (void)fireTrackersOfType:(long long)arg1 forEvent:(id)arg2;
- (void)fireTrackersOfType:(long long)arg1;
- (void)fireTrackers:(struct NSMutableSet *)arg1;
- (id)createQuartileObserver;
- (void)fireRemainingCompletionTrackersIfNeeded;
- (void)showPoststitial;
- (void)handleVideoPlayerError;
- (void)itemDidFailToPlayToEnd:(id)arg1;
- (void)toggleMute;
- (void)skipVideo;
- (void)clickThroughFromVideo;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)appResumed:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithSdk:(id)arg1 currentAd:(id)arg2 wrapper:(id)arg3;

// Remaining properties
@property(readonly) ALVASTAd *currentAd; // @dynamic currentAd;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

