//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, ALVASTCompanionAd, ALVASTSystemInfo, ALVASTVideoCreative, NSDictionary, NSMutableSet, NSString;

@interface ALVASTAdBuilder : NSObject
{
    ALSdk *_sdk;
    NSDictionary *_adObject;
    NSDictionary *_fullResponse;
    unsigned long long _source;
    long long _createdAtMillis;
    NSString *_title;
    NSString *_adDescription;
    ALVASTSystemInfo *_systemInfo;
    ALVASTVideoCreative *_videoCreative;
    ALVASTCompanionAd *_companionAd;
    struct NSMutableSet *_impressionTrackers;
    struct NSMutableSet *_errorTrackers;
}

@property(retain, nonatomic) NSMutableSet *errorTrackers; // @synthesize errorTrackers=_errorTrackers;
@property(retain, nonatomic) NSMutableSet *impressionTrackers; // @synthesize impressionTrackers=_impressionTrackers;
@property(retain, nonatomic) ALVASTCompanionAd *companionAd; // @synthesize companionAd=_companionAd;
@property(retain, nonatomic) ALVASTVideoCreative *videoCreative; // @synthesize videoCreative=_videoCreative;
@property(retain, nonatomic) ALVASTSystemInfo *systemInfo; // @synthesize systemInfo=_systemInfo;
@property(copy, nonatomic) NSString *adDescription; // @synthesize adDescription=_adDescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long createdAtMillis; // @synthesize createdAtMillis=_createdAtMillis;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(retain, nonatomic) NSDictionary *fullResponse; // @synthesize fullResponse=_fullResponse;
@property(retain, nonatomic) NSDictionary *adObject; // @synthesize adObject=_adObject;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;

@end

