//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface ALVASTVideoFile : NSObject
{
    NSURL *_sourceVideoURL;
    NSURL *_videoURL;
    unsigned long long _deliveryType;
    NSString *_fileType;
    double _width;
    double _height;
    unsigned long long _bitrate;
}

+ (id)stringFromDeliveryType:(unsigned long long)arg1;
+ (unsigned long long)deliveryTypeFromString:(id)arg1;
+ (id)videoFileFromXMLNode:(id)arg1 usingSDK:(id)arg2;
@property(nonatomic) unsigned long long bitrate; // @synthesize bitrate=_bitrate;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *fileType; // @synthesize fileType=_fileType;
@property(nonatomic) unsigned long long deliveryType; // @synthesize deliveryType=_deliveryType;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(retain, nonatomic) NSURL *sourceVideoURL; // @synthesize sourceVideoURL=_sourceVideoURL;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic, getter=isVideoStream) _Bool videoStream; // @dynamic videoStream;

@end

