//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALDirectAd.h"

@class ALVASTCompanionAd, ALVASTSystemInfo, ALVASTVideoCreative, ALVASTVideoFile, NSArray, NSMutableSet, NSString, NSURL;

@interface ALVASTAd : ALDirectAd
{
    NSString *_title;
    NSString *_adDescription;
    ALVASTSystemInfo *_systemInfo;
    ALVASTVideoCreative *_videoCreative;
    ALVASTCompanionAd *_companionAd;
    struct NSMutableSet *_impressionTrackers;
    struct NSMutableSet *_errorTrackers;
}

+ (id)vastAdWithBuilderBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableSet *errorTrackers; // @synthesize errorTrackers=_errorTrackers;
@property(retain, nonatomic) NSMutableSet *impressionTrackers; // @synthesize impressionTrackers=_impressionTrackers;
@property(retain, nonatomic) ALVASTCompanionAd *companionAd; // @synthesize companionAd=_companionAd;
@property(retain, nonatomic) ALVASTVideoCreative *videoCreative; // @synthesize videoCreative=_videoCreative;
@property(retain, nonatomic) ALVASTSystemInfo *systemInfo; // @synthesize systemInfo=_systemInfo;
@property(copy, nonatomic) NSString *adDescription; // @synthesize adDescription=_adDescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqualToAd:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)stringFromVASTTrackerType:(long long)arg1;
@property(readonly, nonatomic, getter=shouldFireClickTrackersOnHTMLClicks) _Bool fireClickTrackersOnHTMLClicks; // @dynamic fireClickTrackersOnHTMLClicks;
@property(readonly, nonatomic, getter=shouldCacheVideoCreative) _Bool cacheVideoCreative; // @dynamic cacheVideoCreative;
@property(readonly, nonatomic, getter=shouldCacheCompanionAd) _Bool cacheCompanionAd; // @dynamic cacheCompanionAd;
- (struct NSMutableSet *)retrieveEventTrackersForCreativeType:(unsigned long long)arg1 events:(id)arg2;
- (struct NSMutableSet *)companionAdClickTrackers;
- (struct NSMutableSet *)videoClickTrackers;
- (struct NSMutableSet *)retrieveTrackersForType:(long long)arg1 events:(id)arg2;
- (struct NSMutableSet *)retrieveTrackersForType:(long long)arg1 event:(id)arg2;
- (id)videoClickDestinationURL;
@property(readonly, nonatomic) NSURL *clickDestinationURL;
@property(readonly, nonatomic) _Bool videoClickableDuringPlayback;
@property(readonly, nonatomic, getter=isVideoStream) _Bool videoStream;
@property(retain) NSURL *videoURL; // @dynamic videoURL;
@property(readonly, nonatomic) NSArray *impressionPostbacks; // @dynamic impressionPostbacks;
- (id)impressionURL;
@property(retain, nonatomic) NSURL *companionHTMLTemplateURL; // @dynamic companionHTMLTemplateURL;
@property(copy, nonatomic) NSString *companionHTMLTemplate; // @dynamic companionHTMLTemplate;
@property(readonly, nonatomic) unsigned long long videoSelectionPolicy; // @dynamic videoSelectionPolicy;
@property(readonly, nonatomic) ALVASTVideoFile *videoFileToUse; // @dynamic videoFileToUse;
@property(readonly, nonatomic, getter=isImmediateAdLoad) _Bool immediateAdLoad; // @dynamic immediateAdLoad;
@property(readonly, nonatomic) unsigned long long firstCachingOperation; // @dynamic firstCachingOperation;
@property(readonly, nonatomic, getter=isStreaming) _Bool streaming; // @dynamic streaming;
- (id)initWithBuilder:(id)arg1;

@end

