//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALVASTNonVideoResource, NSMutableDictionary, NSMutableSet, NSURL;

@interface ALVASTCompanionAd : NSObject
{
    double _width;
    double _height;
    NSURL *_destinationURL;
    ALVASTNonVideoResource *_nonVideoResouce;
    struct NSMutableSet *_clickTrackers;
    struct NSMutableDictionary *_eventTrackers;
}

+ (id)companionAdFromXMLNode:(id)arg1 existingCompanionAd:(id)arg2 context:(id)arg3 usingSDK:(id)arg4;
@property(retain, nonatomic) NSMutableDictionary *eventTrackers; // @synthesize eventTrackers=_eventTrackers;
@property(retain, nonatomic) NSMutableSet *clickTrackers; // @synthesize clickTrackers=_clickTrackers;
@property(retain, nonatomic) ALVASTNonVideoResource *nonVideoResouce; // @synthesize nonVideoResouce=_nonVideoResouce;
@property(retain, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

