//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSMutableSet, NSURL;

@interface ALVASTVideoCreative : NSObject
{
    double _duration;
    NSArray *_videoFiles;
    NSURL *_destinationURL;
    struct NSMutableSet *_clickTrackers;
    struct NSMutableDictionary *_eventTrackers;
}

+ (_Bool)validateVideoFileExtension:(id)arg1 withSupportedMimeTypes:(id)arg2 context:(id)arg3 sdk:(id)arg4;
+ (id)videoFilesFromXMLNode:(id)arg1 context:(id)arg2 usingSDK:(id)arg3;
+ (double)timeIntervalDurationFromDurationString:(id)arg1;
+ (id)videoCreativeFromXMLNode:(id)arg1 withExistingVideoCreative:(id)arg2 context:(id)arg3 usingSDK:(id)arg4;
@property(retain, nonatomic) NSMutableDictionary *eventTrackers; // @synthesize eventTrackers=_eventTrackers;
@property(retain, nonatomic) NSMutableSet *clickTrackers; // @synthesize clickTrackers=_clickTrackers;
@property(retain, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
@property(retain, nonatomic) NSArray *videoFiles; // @synthesize videoFiles=_videoFiles;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)videoFileToUseForPolicy:(unsigned long long)arg1;
- (id)init;

@end

