//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface ALVASTNonVideoResource : NSObject
{
    unsigned long long _type;
    NSURL *_resourceURL;
    NSURL *_backupResourceURL;
    NSString *_resourceContents;
}

+ (id)stringFromType:(unsigned long long)arg1;
+ (id)URLOrStringFromNode:(id)arg1 withKey:(id)arg2;
+ (id)nonVideoResourceForXMLNode:(id)arg1 existingNonVideoResource:(id)arg2 usingSDK:(id)arg3;
@property(copy, nonatomic) NSString *resourceContents; // @synthesize resourceContents=_resourceContents;
@property(retain, nonatomic) NSURL *backupResourceURL; // @synthesize backupResourceURL=_backupResourceURL;
@property(retain, nonatomic) NSURL *resourceURL; // @synthesize resourceURL=_resourceURL;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

