//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ALVASTTracker : NSObject
{
    NSString *_identifier;
    NSString *_event;
    NSString *_destination;
    long long _offsetSeconds;
    long long _offsetPercent;
}

+ (long long)percentOffsetForEvent:(id)arg1 withContext:(id)arg2;
+ (id)trackerFromXMLNode:(id)arg1 context:(id)arg2 usingSDK:(id)arg3;
@property(nonatomic) long long offsetPercent; // @synthesize offsetPercent=_offsetPercent;
@property(nonatomic) long long offsetSeconds; // @synthesize offsetSeconds=_offsetSeconds;
@property(retain, nonatomic) NSString *destination; // @synthesize destination=_destination;
@property(copy, nonatomic) NSString *event; // @synthesize event=_event;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEligibleToTrackWithCurrentTimeSeconds:(long long)arg1 currentTimePercent:(long long)arg2;
- (id)init;

@end

