//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAdZone, ALSdk, NSArray, NSDictionary, NSMutableArray;

@interface ALVASTContext : NSObject
{
    NSMutableArray *_aggregatedVASTResponses;
    NSDictionary *_appLovinAdResponse;
    NSDictionary *_fullAdResponse;
    long long _createdAtMillis;
    unsigned long long _source;
    ALSdk *_sdk;
}

@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(nonatomic) long long createdAtMillis; // @synthesize createdAtMillis=_createdAtMillis;
@property(retain, nonatomic) NSDictionary *fullAdResponse; // @synthesize fullAdResponse=_fullAdResponse;
@property(retain, nonatomic) NSDictionary *appLovinAdResponse; // @synthesize appLovinAdResponse=_appLovinAdResponse;
@property(retain, nonatomic) NSMutableArray *aggregatedVASTResponses; // @synthesize aggregatedVASTResponses=_aggregatedVASTResponses;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long videoCompletionPercent; // @dynamic videoCompletionPercent;
@property(readonly, nonatomic, getter=shouldValidateWithExtensionIfNoType) _Bool validateWithExtensionIfNoType; // @dynamic validateWithExtensionIfNoType;
@property(readonly, nonatomic) NSArray *streamingExtensions; // @dynamic streamingExtensions;
@property(readonly, nonatomic) NSArray *sdkSupportedVideoTypes; // @dynamic sdkSupportedVideoTypes;
@property(readonly, nonatomic, getter=shouldValidateVideoTypeWithOS) _Bool validateVideoTypeWithOS; // @dynamic validateVideoTypeWithOS;
@property(readonly, nonatomic) unsigned long long currentWrapperDepth; // @dynamic currentWrapperDepth;
@property(readonly, nonatomic) ALAdZone *adZone; // @dynamic adZone;
- (id)initWithAppLovinAdResponse:(id)arg1 fullAdResponse:(id)arg2 source:(unsigned long long)arg3 sdk:(id)arg4;

@end

