//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, ALTimer, MAAdView;
@protocol ALViewabilityTimerDelegate;

@interface ALViewabilityTimer : NSObject
{
    ALSdk *_sdk;
    MAAdView *_adView;
    id <ALViewabilityTimerDelegate> _delegate;
    double _firstVisibleTimestamp;
    ALTimer *_timer;
    NSObject *_timerLock;
    double _viewabilityMinPercentage;
    double _viewabilityMinPixels;
    double _requiredSecondsForImpression;
}

@property(nonatomic) double requiredSecondsForImpression; // @synthesize requiredSecondsForImpression=_requiredSecondsForImpression;
@property(nonatomic) double viewabilityMinPixels; // @synthesize viewabilityMinPixels=_viewabilityMinPixels;
@property(nonatomic) double viewabilityMinPercentage; // @synthesize viewabilityMinPercentage=_viewabilityMinPercentage;
@property(retain, nonatomic) NSObject *timerLock; // @synthesize timerLock=_timerLock;
@property(retain, nonatomic) ALTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) double firstVisibleTimestamp; // @synthesize firstVisibleTimestamp=_firstVisibleTimestamp;
@property(nonatomic) __weak id <ALViewabilityTimerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak MAAdView *adView; // @synthesize adView=_adView;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)checkIfAdViewable;
- (void)stopTracking;
- (void)trackAdViewForAd:(id)arg1;
- (id)initWithAdView:(id)arg1 sdk:(id)arg2 andNotify:(id)arg3;

@end

