//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class ALSdk, NSDictionary, NSString;

@interface ALVideoButtonProperties : NSObject <NSCopying>
{
    _Bool _tapToFade;
    NSString *_horizontalConstraint;
    NSString *_verticalConstraint;
    double _tapToFadeDuration;
    double _fadeInDuration;
    double _fadeOutDuration;
    double _fadeInDelay;
    double _fadeOutDelay;
    ALSdk *_sdk;
}

@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) double fadeOutDelay; // @synthesize fadeOutDelay=_fadeOutDelay;
@property(nonatomic) double fadeInDelay; // @synthesize fadeInDelay=_fadeInDelay;
@property(nonatomic) double fadeOutDuration; // @synthesize fadeOutDuration=_fadeOutDuration;
@property(nonatomic) double fadeInDuration; // @synthesize fadeInDuration=_fadeInDuration;
@property(nonatomic) double tapToFadeDuration; // @synthesize tapToFadeDuration=_tapToFadeDuration;
@property(nonatomic) _Bool tapToFade; // @synthesize tapToFade=_tapToFade;
@property(copy, nonatomic) NSString *verticalConstraint; // @synthesize verticalConstraint=_verticalConstraint;
@property(copy, nonatomic) NSString *horizontalConstraint; // @synthesize horizontalConstraint=_horizontalConstraint;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqualToVideoButtonProperties:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSDictionary *defaultProperties; // @dynamic defaultProperties;
- (id)initWithSdk:(id)arg1 properties:(id)arg2;

@end

