//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNotification;

@protocol ALVideoEventProtocol <NSObject>
- (void)toggleMute;
- (void)skipVideo;
- (void)clickThroughFromVideo;

@optional
- (void)performBrokenVideoFailsafeIfNeeded;
- (void)handleVideoPlayerError;
- (void)itemDidFailToPlayToEnd:(NSNotification *)arg1;
@end

