//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ALDirectAd, NSString, NSURL, NSURLRequest, UIScrollView;
@protocol UIWebViewDelegate><WKNavigationDelegate;

@protocol ALWebView <NSObject>
@property(nonatomic) __weak id <UIWebViewDelegate><WKNavigationDelegate> bridgingDelegate;
- (void)evaluateJavaScript:(NSString *)arg1;
- (void)loadURL:(NSURL *)arg1;
- (void)loadRequest:(NSURLRequest *)arg1;
- (void)loadHTMLString:(NSString *)arg1;
- (void)prepareToLoadAd:(ALDirectAd *)arg1;

@optional
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)stopLoading;
@end

