//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALWebViewBridgeUtils : NSObject
{
}

+ (void)loadURLFromQueryInURL:(id)arg1 forAd:(id)arg2 inContainer:(id)arg3 usingSDK:(id)arg4;
+ (void)contractAd:(id)arg1 inWebView:(id)arg2 container:(id)arg3 expandedAdView:(id)arg4 usingSDK:(id)arg5;
+ (void)clickOnURL:(id)arg1 forAd:(id)arg2 inContainer:(id)arg3 statsHelper:(id)arg4 usingSDK:(id)arg5;
+ (void)clickOnVASTAd:(id)arg1 inContainer:(id)arg2 statsHelper:(id)arg3 usingSDK:(id)arg4;
+ (void)loadNextAdForAdView:(id)arg1;
+ (_Bool)processRequest:(id)arg1 clicked:(_Bool)arg2 forAd:(id)arg3 inWebView:(id)arg4 container:(id)arg5 expandedAdView:(id)arg6 statsHelper:(id)arg7 usingSDK:(id)arg8;

@end

