//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIWebViewDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"

@class ALSdk, ALWKWebView, NSString;
@protocol ALWebViewViewControllerDelegate;

@interface ALWebViewViewController : UIViewController <UIWebViewDelegate, WKNavigationDelegate>
{
    _Bool _statusBarOriginallyHidden;
    id <ALWebViewViewControllerDelegate> _delegate;
    ALSdk *_sdk;
    ALWKWebView *_webView;
    CDUnknownBlockType _dismissBlock;
}

@property(nonatomic) _Bool statusBarOriginallyHidden; // @synthesize statusBarOriginallyHidden=_statusBarOriginallyHidden;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(retain, nonatomic) ALWKWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) __weak id <ALWebViewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)dismiss;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)initWithURL:(id)arg1 hideStatusBar:(_Bool)arg2 sdk:(id)arg3 dismissBlock:(CDUnknownBlockType)arg4;
- (id)initWithURL:(id)arg1 sdk:(id)arg2 dismissBlock:(CDUnknownBlockType)arg3;
- (id)initWithURL:(id)arg1 sdk:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

