//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ALWebView-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSString, UIScrollView, WKWebView;
@protocol UIWebViewDelegate><WKNavigationDelegate;

@interface ALWKWebView : UIView <WKUIDelegate, ALWebView>
{
    WKWebView *_webView;
}

@property(nonatomic) __weak WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)setAlpha:(double)arg1;
- (void)setOpaque:(_Bool)arg1;
- (void)setBackgroundColor:(id)arg1;
@property(nonatomic, getter=isScrollEnabled) _Bool scrollEnabled; // @dynamic scrollEnabled;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)loadRequest:(id)arg1;
- (void)stopLoading;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)evaluateJavaScript:(id)arg1;
@property(nonatomic) __weak id <UIWebViewDelegate><WKNavigationDelegate> bridgingDelegate; // @dynamic bridgingDelegate;
- (void)loadURL:(id)arg1;
- (void)loadHTMLString:(id)arg1;
- (void)prepareToLoadAd:(id)arg1;
- (void)layoutSubviews;
- (id)configurationFromAd:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 ad:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

