//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXMLParserDelegate-Protocol.h"

@class ALLogger, ALMutableXMLNode, ALSdk, ALStack, NSDate, NSError, NSMutableString, NSString;

@interface ALXMLParser : NSObject <NSXMLParserDelegate>
{
    ALSdk *_sdk;
    ALStack *_nodeStack;
    NSMutableString *_currentText;
    ALMutableXMLNode *_lastParsedNode;
    NSError *_error;
    NSDate *_startTime;
}

+ (id)parseData:(id)arg1 error:(id *)arg2 withSDK:(id)arg3;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) ALMutableXMLNode *lastParsedNode; // @synthesize lastParsedNode=_lastParsedNode;
@property(retain, nonatomic) NSMutableString *currentText; // @synthesize currentText=_currentText;
@property(retain, nonatomic) ALStack *nodeStack; // @synthesize nodeStack=_nodeStack;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
@property(readonly, nonatomic) ALLogger *logger; // @dynamic logger;
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;
- (void)parser:(id)arg1 foundCDATA:(id)arg2;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parserDidEndDocument:(id)arg1;
- (void)parserDidStartDocument:(id)arg1;
- (id)parseData:(id)arg1 error:(id *)arg2;
- (void)setupParser;
- (id)initWithSdk:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

