//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface ALXMLNode : NSObject
{
    ALXMLNode *_parent;
    NSString *_elementName;
    NSDictionary *_attributes;
    NSString *_text;
    NSArray *_children;
}

+ (id)emptyNode;
@property(retain, nonatomic) NSArray *children; // @synthesize children=_children;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSDictionary *attributes; // @synthesize attributes=_attributes;
@property(copy, nonatomic) NSString *elementName; // @synthesize elementName=_elementName;
@property(nonatomic) __weak ALXMLNode *parent; // @synthesize parent=_parent;
- (void).cxx_destruct;
- (id)description;
- (id)firstChildNodeNamed:(id)arg1;
- (id)firstDirectChildNodeNamed:(id)arg1;
- (id)allDirectChildrenNodeNamed:(id)arg1;
- (id)initWithName:(id)arg1 attributes:(id)arg2 parent:(id)arg3;
@property(readonly, nonatomic, getter=isInLine) _Bool inLine; // @dynamic inLine;
@property(readonly, nonatomic, getter=isWrapper) _Bool wrapper; // @dynamic wrapper;

@end

