//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, GPUImagePicture, NSDictionary, NSString, NSURL, SPHue, UIActivityIndicatorView, UIImage, UIImageView, UIView;

@interface Animate : NSObject
{
    double startTime;
    UIImage *original_picture;
    int pixel_width;
    int pixel_height;
    int prob;
    int line_j_r;
    unsigned long long width;
    unsigned long long height;
    long long iterations;
    int starting_j;
    int watermark_margin_j;
    int watermark_margin_i;
    int update_count;
    unsigned int *hue_pixels;
    SPHue *gpu_hue;
    GPUImagePicture *pic1;
    float global_scale;
    struct CGSize size2;
    unsigned long long fps;
    AVAssetWriterInputPixelBufferAdaptor *adaptor;
    struct __CVBuffer *buffer;
    int frameCount;
    double frameDuration;
    AVAssetWriter *videoWriter;
    AVAssetWriterInput *videoWriterInput;
    NSString *videoOutputPath;
    struct CGSize imageSize;
    int gif_n_frames;
    int gif_fading_frames;
    struct CGImageDestination *destination;
    NSDictionary *frameProperties;
    NSURL *fileURL;
    int gif_frame_count;
    _Bool _save_mode;
    _Bool _did_cancel;
    _Bool _is_recording;
    float _global_progress;
    UIImageView *_img_view;
    UIImage *_Canvas;
    UIImage *_original_img;
    UIActivityIndicatorView *_spinner;
    CDUnknownBlockType _OnFinish;
    CDUnknownBlockType _OnUpdate;
    UIView *_progress_bar;
    UIView *_cancel_button_layer;
    struct CGSize _frame_size;
}

@property(nonatomic) _Bool is_recording; // @synthesize is_recording=_is_recording;
@property(nonatomic) _Bool did_cancel; // @synthesize did_cancel=_did_cancel;
@property(nonatomic) _Bool save_mode; // @synthesize save_mode=_save_mode;
@property(nonatomic) float global_progress; // @synthesize global_progress=_global_progress;
@property(retain, nonatomic) UIView *cancel_button_layer; // @synthesize cancel_button_layer=_cancel_button_layer;
@property(retain, nonatomic) UIView *progress_bar; // @synthesize progress_bar=_progress_bar;
@property(copy) CDUnknownBlockType OnUpdate; // @synthesize OnUpdate=_OnUpdate;
@property(copy) CDUnknownBlockType OnFinish; // @synthesize OnFinish=_OnFinish;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UIImage *original_img; // @synthesize original_img=_original_img;
@property(nonatomic) struct CGSize frame_size; // @synthesize frame_size=_frame_size;
@property(retain, nonatomic) UIImage *Canvas; // @synthesize Canvas=_Canvas;
@property(retain, nonatomic) UIImageView *img_view; // @synthesize img_view=_img_view;
- (void).cxx_destruct;
- (struct __CVBuffer *)pixelBufferFromCGImage:(struct CGImage *)arg1 size:(struct CGSize)arg2 size2:(struct CGSize)arg3;
- (void)CreateHuePixels:(id)arg1;
- (id)ProcessImage:(id)arg1;
- (void)StopGIF;
- (void)AddGIFFrame;
- (void)StartGIFRecording;
- (void)StopRecordingAnimation;
- (void)AddAnimationFrame;
- (void)StartRecordingAnimation;
- (void)UpdateImage:(id)arg1;
- (void)LoadPixelParams;
- (void)Draw;
- (void)EndPaintingContext;
- (void)BeginPaintingContext;
- (id)initWith:(id)arg1 frame_size:(struct CGSize)arg2;

@end

