//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ChoiceItem, NSString, UIImageView, UILabel;

@interface BarItem : UIView
{
    ChoiceItem *choice;
    _Bool _clickable;
    _Bool _pro_only;
    short _option_type;
    short _option_number;
    short _icon_size_w;
    short _icon_size_h;
    UIImageView *_iconView;
    UILabel *_titleLabel;
    CDUnknownBlockType _OnClick;
    NSString *_option_string;
}

@property(nonatomic) short icon_size_h; // @synthesize icon_size_h=_icon_size_h;
@property(nonatomic) short icon_size_w; // @synthesize icon_size_w=_icon_size_w;
@property(nonatomic) _Bool pro_only; // @synthesize pro_only=_pro_only;
@property(nonatomic) _Bool clickable; // @synthesize clickable=_clickable;
@property(retain, nonatomic) NSString *option_string; // @synthesize option_string=_option_string;
@property(nonatomic) short option_number; // @synthesize option_number=_option_number;
@property(nonatomic) short option_type; // @synthesize option_type=_option_type;
@property(copy) CDUnknownBlockType OnClick; // @synthesize OnClick=_OnClick;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void).cxx_destruct;
- (void)drawItem;
- (void)UnselectItem;
- (void)SelectItem;
- (id)initWithFrame:(struct CGRect)arg1 choice_item:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 choice_item:(id)arg2 draw_later:(_Bool)arg3;
- (id)initWithFrame:(struct CGRect)arg1 choice_item:(id)arg2 icon_size_w:(double)arg3 icon_size_h:(double)arg4;
- (id)initWithFrame:(struct CGRect)arg1 choice_item:(id)arg2 icon_size_w:(double)arg3 icon_size_h:(double)arg4 draw_later:(_Bool)arg5;

@end

