//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageTwoInputFilter.h"

@interface BF : GPUImageTwoInputFilter
{
    int gl_sigma_d;
    int gl_sigma_r;
    int gl_pass;
    int gl_img_width;
    int gl_img_height;
    float _img_width;
    float _img_height;
    float _sigma_d;
    float _sigma_r;
    int _pass;
}

@property(nonatomic) int pass; // @synthesize pass=_pass;
@property(nonatomic) float sigma_r; // @synthesize sigma_r=_sigma_r;
@property(nonatomic) float sigma_d; // @synthesize sigma_d=_sigma_d;
@property(nonatomic) float img_height; // @synthesize img_height=_img_height;
@property(nonatomic) float img_width; // @synthesize img_width=_img_width;
- (void)setupFilterForSize:(struct CGSize)arg1;
- (id)init;

@end

