//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface BlankWindow : NSObject
{
    UIImage *_Canvas;
    double _line_mult;
    NSString *_window_title;
    double _title_bar_height;
    struct CGSize _frame_size;
}

@property(nonatomic) double title_bar_height; // @synthesize title_bar_height=_title_bar_height;
@property(retain, nonatomic) NSString *window_title; // @synthesize window_title=_window_title;
@property(nonatomic) double line_mult; // @synthesize line_mult=_line_mult;
@property(nonatomic) struct CGSize frame_size; // @synthesize frame_size=_frame_size;
@property(retain, nonatomic) UIImage *Canvas; // @synthesize Canvas=_Canvas;
- (void).cxx_destruct;
- (void)EndPaintingContext;
- (void)BeginPaintingContext;
- (void)Draw;
- (id)initWith:(struct CGSize)arg1 text:(id)arg2;

@end

