//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface BottomExtraView : UIView
{
    double original_y;
    _Bool _is_bar_visible;
    double _final_y;
}

@property(nonatomic) double final_y; // @synthesize final_y=_final_y;
@property(nonatomic) _Bool is_bar_visible; // @synthesize is_bar_visible=_is_bar_visible;
- (void)CloseExtraBar:(id)arg1;
- (void)ShowBarInternal:(id)arg1;
- (void)ShowBar:(id)arg1;
- (void)HideBar;
- (void)HideBarInternal;
- (void)drawBar;
- (id)initWithFrame:(struct CGRect)arg1;

@end

