//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface BottomBar : UIView
{
    UIView *button1;
    UIView *button2;
    UIView *button3;
    UILabel *titleLabel1;
    UILabel *titleLabel2;
    UILabel *titleLabel3;
    _Bool moved;
    short _selected_option;
}

@property(nonatomic) short selected_option; // @synthesize selected_option=_selected_option;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)SelectChoice:(short)arg1;
- (void)SaveBarOffset;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)UnSelectAllChoices;
- (void)drawBar;
- (id)initWithFrame:(struct CGRect)arg1;

@end

