//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface ChoiceItem : NSObject
{
    NSString *_ChoiceName;
    NSString *_ChoiceIcon;
    UIImage *_ChoiceIconImage;
    UIImage *_ChoiceIconImage_Selected;
    CDUnknownBlockType _OnClick;
}

+ (id)initwithName:(id)arg1 Choice_IconImage:(id)arg2 Choice_IconImageSelected:(id)arg3;
+ (id)initwithName:(id)arg1 Choice_Icon:(id)arg2;
@property(copy) CDUnknownBlockType OnClick; // @synthesize OnClick=_OnClick;
@property(retain, nonatomic) UIImage *ChoiceIconImage_Selected; // @synthesize ChoiceIconImage_Selected=_ChoiceIconImage_Selected;
@property(retain, nonatomic) UIImage *ChoiceIconImage; // @synthesize ChoiceIconImage=_ChoiceIconImage;
@property(retain, nonatomic) NSString *ChoiceIcon; // @synthesize ChoiceIcon=_ChoiceIcon;
@property(retain, nonatomic) NSString *ChoiceName; // @synthesize ChoiceName=_ChoiceName;
- (void).cxx_destruct;

@end

