//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class NSMutableArray;

@interface ChoiceBarGeneric : UIScrollView
{
    NSMutableArray *choices;
    NSMutableArray *bar_items;
    _Bool moved;
    short selected_item;
}

- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)UnSelectAllChoices;
- (void)RefreshBar;
- (void)drawBar;
- (id)initWithFrame:(struct CGRect)arg1 bar_items:(id)arg2 selected_option:(short)arg3;

@end

