//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface CrossAppPromotion : UIViewController
{
    double temp_button_width;
    double temp_font_size;
    struct CGSize boundingSize;
}

- (void)itemDidFinishPlaying:(id)arg1;
- (void)removeVideoPlayer;
- (void)StartVideoPlayback;
- (_Bool)prefersStatusBarHidden;
- (void)CheckOutBtnClick:(id)arg1;
- (void)CloseClick:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)AddTopBar;
- (void)viewDidLoad;

@end

