//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilter.h"

@interface DG : GPUImageFilter
{
    int gl_sigma_e;
    int gl_sigma_r;
    int gl_tau;
    int gl_phi;
    int gl_img_width;
    int gl_img_height;
    float _img_width;
    float _img_height;
    float _sigma_e;
    float _sigma_r;
    float _tau;
    float _phi;
}

@property(nonatomic) float phi; // @synthesize phi=_phi;
@property(nonatomic) float tau; // @synthesize tau=_tau;
@property(nonatomic) float sigma_r; // @synthesize sigma_r=_sigma_r;
@property(nonatomic) float sigma_e; // @synthesize sigma_e=_sigma_e;
@property(nonatomic) float img_height; // @synthesize img_height=_img_height;
@property(nonatomic) float img_width; // @synthesize img_width=_img_width;
- (void)setupFilterForSize:(struct CGSize)arg1;
- (id)init;

@end

