//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilter.h"

@interface DitherFilter2 : GPUImageFilter
{
    int gl_img_width;
    int gl_img_height;
    int gl_dither_style;
    int gl_offset_x;
    int gl_offset_y;
    float _img_width;
    float _img_height;
    int _dither_style;
    float _offset_x;
    float _offset_y;
}

@property(nonatomic) float offset_y; // @synthesize offset_y=_offset_y;
@property(nonatomic) float offset_x; // @synthesize offset_x=_offset_x;
@property(nonatomic) int dither_style; // @synthesize dither_style=_dither_style;
@property(nonatomic) float img_height; // @synthesize img_height=_img_height;
@property(nonatomic) float img_width; // @synthesize img_width=_img_width;
- (void)setupFilterForSize:(struct CGSize)arg1;
- (id)init;

@end

