//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage;

@interface EmptyBackground : NSObject
{
    UIImage *_Canvas;
    struct CGSize _frame_size;
}

@property(nonatomic) struct CGSize frame_size; // @synthesize frame_size=_frame_size;
@property(retain, nonatomic) UIImage *Canvas; // @synthesize Canvas=_Canvas;
- (void).cxx_destruct;
- (void)EndPaintingContext;
- (void)BeginPaintingContext;
- (void)Draw;
- (id)initWith:(struct CGSize)arg1;

@end

