//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilter.h"

@interface Experimental2 : GPUImageFilter
{
    int gl_img_width;
    int gl_img_height;
    int gl_frame;
    int gl_e_mode;
    int frame_counter;
    float _img_width;
    float _img_height;
    int _exp_mode;
}

@property(nonatomic) int exp_mode; // @synthesize exp_mode=_exp_mode;
@property(nonatomic) float img_height; // @synthesize img_height=_img_height;
@property(nonatomic) float img_width; // @synthesize img_width=_img_width;
- (void)renderToTextureWithVertices:(const float *)arg1 textureCoordinates:(const float *)arg2;
- (void)setupFilterForSize:(struct CGSize)arg1;
- (id)init;

@end

