//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageTwoInputFilter.h"

@interface FD2 : GPUImageTwoInputFilter
{
    int gl_sigma_m;
    int gl_phi;
    int gl_epsilon;
    int gl_img_width;
    int gl_img_height;
    float _img_width;
    float _img_height;
    float _sigma_m;
    float _phi;
    float _epsilon;
}

@property(nonatomic) float epsilon; // @synthesize epsilon=_epsilon;
@property(nonatomic) float phi; // @synthesize phi=_phi;
@property(nonatomic) float sigma_m; // @synthesize sigma_m=_sigma_m;
@property(nonatomic) float img_height; // @synthesize img_height=_img_height;
@property(nonatomic) float img_width; // @synthesize img_width=_img_width;
- (void)setupFilterForSize:(struct CGSize)arg1;
- (id)init;

@end

