//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImagePixellateFilter.h"

@interface GPUImageHalftoneFilter : GPUImagePixellateFilter
{
    int gl_ht_mode;
    int _ht_mode;
}

@property(nonatomic) int ht_mode; // @synthesize ht_mode=_ht_mode;
- (id)init;

@end

