//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ImageProcessing : NSObject
{
}

+ (id)rotatedImage:(id)arg1 rotation:(double)arg2;
+ (id)removeRotationForImage:(id)arg1;
+ (unsigned int *)PixelsOfImage:(id)arg1;
+ (id)UIImageFromRawData:(char *)arg1 width:(int)arg2 height:(int)arg3 bpr:(long long)arg4;
+ (id)Saturation:(id)arg1;
+ (id)changeLuminosityOfCIImage:(id)arg1 luminosity:(double)arg2;
+ (id)Brightness:(id)arg1;
+ (id)Contrast:(id)arg1;
+ (id)AutoCorrectImage:(id)arg1;
+ (id)CIImageToUIImage:(id)arg1;
+ (id)UIImageToCIImage:(id)arg1;
+ (id)imageWithImageRetina:(id)arg1 scaledToSize:(struct CGSize)arg2;
+ (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;

@end

