//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MAAd, NSString;

@protocol MAAdDelegate <NSObject>
- (void)didFailToDisplayAd:(MAAd *)arg1 withErrorCode:(long long)arg2;
- (void)didClickAd:(MAAd *)arg1;
- (void)didHideAd:(MAAd *)arg1;
- (void)didDisplayAd:(MAAd *)arg1;
- (void)didFailToLoadAdForAdUnitIdentifier:(NSString *)arg1 withErrorCode:(long long)arg2;
- (void)didLoadAd:(MAAd *)arg1;
@end

