//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MAAdapterError : NSObject
{
    long long _code;
    NSString *_errorString;
}

+ (id)rewardError;
+ (long long)errorCodeRewardError;
+ (id)adFrequencyCappedError;
+ (long long)errorCodeAdFrequencyCapped;
+ (id)adExpiredError;
+ (long long)errorCodeAdExpired;
+ (id)webViewError;
+ (long long)errorCodeWebViewError;
+ (id)signalCollectionNotSupported;
+ (long long)errorCodeSignalCollectionNotSupported;
+ (id)signalCollectionTimeout;
+ (long long)errorCodeSignalCollectionTimeout;
+ (id)internalError;
+ (long long)errorCodeInternalError;
+ (id)serverError;
+ (long long)errorCodeServerError;
+ (id)noConnection;
+ (long long)errorCodeNoConnection;
+ (id)timeout;
+ (long long)errorCodeTimeout;
+ (id)adNotReady;
+ (long long)errorCodeAdNotReady;
+ (id)notInitialized;
+ (long long)errorCodeNotInitialized;
+ (id)badRequest;
+ (long long)errorCodeBadRequest;
+ (id)invalidConfiguration;
+ (long long)errorCodeInvalidConfiguration;
+ (id)invalidLoadState;
+ (long long)errorCodeInvalidLoadState;
+ (id)unspecified;
+ (long long)errorCodeUnspecified;
+ (id)noFill;
+ (long long)errorCodeNoFill;
+ (id)errorWithCode:(long long)arg1 errorString:(id)arg2;
+ (id)errorWithNSError:(id)arg1;
+ (id)errorWithCode:(long long)arg1 adapterErrorCode:(long long)arg2;
+ (id)errorWithCode:(long long)arg1;
@property(copy, nonatomic) NSString *errorString; // @synthesize errorString=_errorString;
@property(nonatomic) long long code; // @synthesize code=_code;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)initWithCode:(long long)arg1 errorString:(id)arg2;

@end

