//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MAAdViewController, NSString, UIColor;
@protocol MAAdViewAdDelegate;

@interface MAAdView : UIView
{
    _Bool _autoload;
    MAAdViewController *_controller;
    UIView *_backgroundView;
    UIColor *_publisherBackgroundViewColor;
}

@property(retain, nonatomic) UIColor *publisherBackgroundViewColor; // @synthesize publisherBackgroundViewColor=_publisherBackgroundViewColor;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) _Bool autoload; // @synthesize autoload=_autoload;
@property(retain, nonatomic) MAAdViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)description;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setAlpha:(double)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)awakeFromNib;
- (void)startAutoRefresh;
- (void)stopAutoRefresh;
- (void)loadAd;
- (void)setExtraParameterForKey:(id)arg1 value:(id)arg2;
@property(nonatomic) __weak id <MAAdViewAdDelegate> delegate; // @dynamic delegate;
@property(copy, nonatomic) NSString *placement; // @dynamic placement;
- (void)baseInitFromInterfaceBuilder:(_Bool)arg1 withAdUnitIdentifier:(id)arg2 sdk:(id)arg3;
- (id)initWithAdUnitIdentifier:(id)arg1 sdk:(id)arg2;
- (id)initWithAdUnitIdentifier:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

