//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAAdController.h"

#import "ALAdRefreshManagerDelegate-Protocol.h"
#import "ALViewabilityTimerDelegate-Protocol.h"

@class ALAdRefreshManager, ALMediatedAdViewAd, ALViewabilityTimer, ALViewabilityTracker, MAAdView, MAAdViewAdLoadDelegate, MAAdViewPrecacheRequestLoadDelegate, NSObject, NSString;

@interface MAAdViewController : MAAdController <ALAdRefreshManagerDelegate, ALViewabilityTimerDelegate>
{
    _Bool _fireRequestOnRefresh;
    _Bool _renderPrecacheRequestAdImmediately;
    NSString *_placement;
    MAAdView *_containerAdView;
    ALMediatedAdViewAd *_cachedAd;
    MAAdViewAdLoadDelegate *_adLoadDelegate;
    MAAdViewPrecacheRequestLoadDelegate *_precacheRequestLoadDelegate;
    ALAdRefreshManager *_adRefreshManager;
    ALViewabilityTracker *_viewabilityTracker;
    ALViewabilityTimer *_viewabilityTimer;
    NSObject *_stateLock;
    ALMediatedAdViewAd *_visibleAd;
}

@property(nonatomic) _Bool renderPrecacheRequestAdImmediately; // @synthesize renderPrecacheRequestAdImmediately=_renderPrecacheRequestAdImmediately;
@property(nonatomic, getter=shouldFireRequestOnRefresh) _Bool fireRequestOnRefresh; // @synthesize fireRequestOnRefresh=_fireRequestOnRefresh;
@property(retain, nonatomic) ALMediatedAdViewAd *visibleAd; // @synthesize visibleAd=_visibleAd;
@property(retain, nonatomic) NSObject *stateLock; // @synthesize stateLock=_stateLock;
@property(retain, nonatomic) ALViewabilityTimer *viewabilityTimer; // @synthesize viewabilityTimer=_viewabilityTimer;
@property(retain, nonatomic) ALViewabilityTracker *viewabilityTracker; // @synthesize viewabilityTracker=_viewabilityTracker;
@property(retain, nonatomic) ALAdRefreshManager *adRefreshManager; // @synthesize adRefreshManager=_adRefreshManager;
@property(retain, nonatomic) MAAdViewPrecacheRequestLoadDelegate *precacheRequestLoadDelegate; // @synthesize precacheRequestLoadDelegate=_precacheRequestLoadDelegate;
@property(retain, nonatomic) MAAdViewAdLoadDelegate *adLoadDelegate; // @synthesize adLoadDelegate=_adLoadDelegate;
@property(retain, nonatomic) ALMediatedAdViewAd *cachedAd; // @synthesize cachedAd=_cachedAd;
@property(nonatomic) __weak MAAdView *containerAdView; // @synthesize containerAdView=_containerAdView;
@property(copy) NSString *placement; // @synthesize placement=_placement;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isRefreshPrecacheRequestEnabled) _Bool refreshPrecacheRequestEnabled; // @dynamic refreshPrecacheRequestEnabled;
- (void)handlePrecacheRequestAdLoaded:(id)arg1;
- (void)scheduleRefreshPrecacheForViewabilityFlag:(unsigned long long)arg1;
- (void)handleViewabilityImpressionForAd:(id)arg1 withViewabilityFlag:(unsigned long long)arg2;
- (void)didLogViewabilityImpression;
- (void)didRefreshAd;
- (void)applyConstraintsForAdView:(id)arg1 parentView:(id)arg2 ad:(id)arg3;
- (void)fadeInNewAd:(id)arg1 withParentView:(id)arg2;
- (void)fadeOutOldAdWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)handleAdLoadFailureForErrorCode:(long long)arg1;
- (void)scheduleRefreshPrecacheRequestIfNeeded;
- (void)removeCurrentAd;
- (void)startAutoRefresh;
- (void)stopAutoRefresh;
- (void)loadAdAndNotify:(id)arg1;
- (void)loadAd;
- (id)initWithAdUnitIdentifier:(id)arg1 containerAdView:(id)arg2 sdk:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

