//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary;

@protocol MAAdapterParameters <NSObject>
@property(readonly, nonatomic, getter=isTesting) _Bool testing;
@property(readonly, nonatomic, getter=isAgeRestrictedUser) _Bool ageRestrictedUser;
@property(readonly, nonatomic, getter=hasUserConsent) _Bool userConsent;
@property(readonly, nonatomic) NSDictionary *serverParameters;
@end

