//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MAAdViewAdDelegate-Protocol.h"

@class MAAdViewController, NSString;

@interface MAAdViewDelegateWrapper : NSObject <MAAdViewAdDelegate>
{
    MAAdViewController *_parentController;
}

@property(nonatomic) __weak MAAdViewController *parentController; // @synthesize parentController=_parentController;
- (void).cxx_destruct;
- (void)didCollapseAd:(id)arg1;
- (void)didExpandAd:(id)arg1;
- (void)didFailToDisplayAd:(id)arg1 withErrorCode:(long long)arg2;
- (void)didClickAd:(id)arg1;
- (void)didHideAd:(id)arg1;
- (void)didDisplayAd:(id)arg1;
- (void)didFailToLoadAdForAdUnitIdentifier:(id)arg1 withErrorCode:(long long)arg2;
- (void)didLoadAd:(id)arg1;
- (id)initWithParentController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

