//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MAAdapterInitializationParameters-Protocol.h"
#import "MAAdapterParameters-Protocol.h"
#import "MAAdapterResponseParameters-Protocol.h"
#import "MASignalCollectionParameters-Protocol.h"

@class MAAdFormat, NSDictionary, NSString;

@interface MAAdapterParametersObject : NSObject <MAAdapterParameters, MAAdapterResponseParameters, MAAdapterInitializationParameters, MASignalCollectionParameters>
{
    _Bool userConsent;
    _Bool ageRestrictedUser;
    _Bool testing;
    NSDictionary *serverParameters;
    NSString *thirdPartyAdPlacementIdentifier;
    NSString *bidResponse;
    MAAdFormat *adFormat;
}

+ (id)parametersFromAdapterSpec:(id)arg1;
+ (id)parametersFromSignalProviderSpec:(id)arg1 forAdFormat:(id)arg2;
+ (id)parametersFromMediatedAd:(id)arg1;
@property(retain, nonatomic) MAAdFormat *adFormat; // @synthesize adFormat;
@property(copy, nonatomic) NSString *bidResponse; // @synthesize bidResponse;
@property(copy, nonatomic) NSString *thirdPartyAdPlacementIdentifier; // @synthesize thirdPartyAdPlacementIdentifier;
@property(nonatomic, getter=isTesting) _Bool testing; // @synthesize testing;
@property(nonatomic, getter=isAgeRestrictedUser) _Bool ageRestrictedUser; // @synthesize ageRestrictedUser;
@property(nonatomic, getter=hasUserConsent) _Bool userConsent; // @synthesize userConsent;
@property(retain, nonatomic) NSDictionary *serverParameters; // @synthesize serverParameters;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

