//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAAdapter-Protocol.h"

@class MAAdFormat;
@protocol MAAdViewAdapterDelegate, MAAdapterResponseParameters;

@protocol MAAdViewAdapter <MAAdapter>
- (void)loadAdViewAdForParameters:(id <MAAdapterResponseParameters>)arg1 adFormat:(MAAdFormat *)arg2 andNotify:(id <MAAdViewAdapterDelegate>)arg3;
@end

