//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MASignalCollectionDelegate-Protocol.h"

@class ALMediationAdapterWrapper, ALSignalCollectionState, NSString;

@interface MAAdapterSignalCollectionDelegateProxy : NSObject <MASignalCollectionDelegate>
{
    ALMediationAdapterWrapper *_parentAdapterWrapper;
    ALSignalCollectionState *_collectionState;
}

@property(retain, nonatomic) ALSignalCollectionState *collectionState; // @synthesize collectionState=_collectionState;
@property(nonatomic) __weak ALMediationAdapterWrapper *parentAdapterWrapper; // @synthesize parentAdapterWrapper=_parentAdapterWrapper;
- (void).cxx_destruct;
- (void)didFailToCollectSignalWithErrorMessage:(id)arg1;
- (void)didCollectSignal:(id)arg1;
- (id)initWithCollectionState:(id)arg1 parentAdapterWrapper:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

