//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAAdapterDelegate-Protocol.h"

@class MAAdapterError, UIView;

@protocol MAAdViewAdapterDelegate <MAAdapterDelegate>
- (void)didCollapseAdViewAd;
- (void)didExpandAdViewAd;
- (void)didHideAdViewAd;
- (void)didClickAdViewAd;
- (void)didFailToDisplayAdViewAdWithError:(MAAdapterError *)arg1;
- (void)didDisplayAdViewAd;
- (void)didFailToLoadAdViewAdWithError:(MAAdapterError *)arg1;
- (void)didLoadAdForAdView:(UIView *)arg1;
@end

