//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALSdk, MAAdFormat, NSMutableDictionary, NSString;

@interface MAAd : NSObject
{
    ALSdk *_sdk;
    NSMutableDictionary *_specObject;
    NSMutableDictionary *_fullResponse;
    NSObject *_specLock;
    NSObject *_fullResponseLock;
}

@property(retain, nonatomic) NSObject *fullResponseLock; // @synthesize fullResponseLock=_fullResponseLock;
@property(retain, nonatomic) NSObject *specLock; // @synthesize specLock=_specLock;
@property(retain) NSMutableDictionary *fullResponse; // @synthesize fullResponse=_fullResponse;
@property(retain) NSMutableDictionary *specObject; // @synthesize specObject=_specObject;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (id)description;
- (void)setObjectToFullResponse:(id)arg1 forKey:(id)arg2;
- (id)objectFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)objectFromFullResponseForKey:(id)arg1;
- (id)dictionaryFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)dictionaryFromFullResponseForKey:(id)arg1;
- (id)arrayFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)arrayFromFullResponseForKey:(id)arg1;
- (id)stringFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)stringFromFullResponseForKey:(id)arg1;
- (id)numberFromFullResponseForKey:(id)arg1 defaultValue:(id)arg2;
- (id)numberFromFullResponseForKey:(id)arg1;
- (long long)integerFromFullResponseForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)integerFromFullResponseForKey:(id)arg1;
- (_Bool)boolFromFullResponseForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)boolFromFullResponseForKey:(id)arg1;
- (_Bool)fullResponseContainsKey:(id)arg1;
- (void)setObjectToSpecObject:(id)arg1 forKey:(id)arg2;
- (id)objectFromSpecObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)objectFromSpecObjectForKey:(id)arg1;
- (id)dictionaryFromSpecObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)dictionaryFromSpecObjectForKey:(id)arg1;
- (id)arrayFromSpecObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)arrayFromSpecObjectForKey:(id)arg1;
- (id)stringFromSpecObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)stringFromSpecObjectForKey:(id)arg1;
- (id)numberFromSpecObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (id)numberFromSpecObjectForKey:(id)arg1;
- (long long)integerFromSpecObjectForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)integerFromSpecObjectForKey:(id)arg1;
- (_Bool)boolFromSpecObjectForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)boolFromSpecObjectForKey:(id)arg1;
- (_Bool)specObjectContainsKey:(id)arg1;
@property(readonly, copy, nonatomic) NSString *adUnitIdentifier; // @dynamic adUnitIdentifier;
@property(readonly, nonatomic) MAAdFormat *format; // @dynamic format;
- (_Bool)isReady;
- (void)dealloc;
- (id)initWithSpecObject:(id)arg1 fullResponse:(id)arg2 sdk:(id)arg3;

@end

