//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MAAdDelegate-Protocol.h"
#import "MARewardedAdDelegate-Protocol.h"

@class MAFullscreenAdController, NSString;

@interface MAFullscreenAdDelegateWrapper : NSObject <MAAdDelegate, MARewardedAdDelegate>
{
    MAFullscreenAdController *_parentAdController;
}

@property(nonatomic) __weak MAFullscreenAdController *parentAdController; // @synthesize parentAdController=_parentAdController;
- (void).cxx_destruct;
- (void)didRewardUserForAd:(id)arg1 withReward:(id)arg2;
- (void)didCompleteRewardedVideoForAd:(id)arg1;
- (void)didStartRewardedVideoForAd:(id)arg1;
- (void)didFailToDisplayAd:(id)arg1 withErrorCode:(long long)arg2;
- (void)didClickAd:(id)arg1;
- (void)didHideAd:(id)arg1;
- (void)didDisplayAd:(id)arg1;
- (void)didFailToLoadAdForAdUnitIdentifier:(id)arg1 withErrorCode:(long long)arg2;
- (void)didLoadAd:(id)arg1;
- (void)didReceiveFallbackAdNotification:(id)arg1;
- (void)detachFallbackAdObserver;
- (void)attachFallbackAdObserver;
- (void)dealloc;
- (id)initWithParentAdController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

