//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAAdapterDelegate-Protocol.h"

@class MAAdapterError;

@protocol MAInterstitialAdapterDelegate <MAAdapterDelegate>
- (void)didFailToDisplayInterstitialAdWithError:(MAAdapterError *)arg1;
- (void)didHideInterstitialAd;
- (void)didClickInterstitialAd;
- (void)didDisplayInterstitialAd;
- (void)didFailToLoadInterstitialAdWithError:(MAAdapterError *)arg1;
- (void)didLoadInterstitialAd;
@end

