//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAAd.h"

@class MAAdFormat, NSString;

@interface MAMockAd : MAAd
{
    NSString *_backingAdUnitIdentifier;
    MAAdFormat *_backingAdFormat;
}

@property(nonatomic) __weak MAAdFormat *backingAdFormat; // @synthesize backingAdFormat=_backingAdFormat;
@property(copy, nonatomic) NSString *backingAdUnitIdentifier; // @synthesize backingAdUnitIdentifier=_backingAdUnitIdentifier;
- (void).cxx_destruct;
- (id)format;
- (id)adUnitIdentifier;
- (id)initWithAdUnitIdentifier:(id)arg1 adFormat:(id)arg2;

@end

