//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAAdDelegate-Protocol.h"

@class MAAd, MAReward;

@protocol MARewardedAdDelegate <MAAdDelegate>
- (void)didRewardUserForAd:(MAAd *)arg1 withReward:(MAReward *)arg2;
- (void)didCompleteRewardedVideoForAd:(MAAd *)arg1;
- (void)didStartRewardedVideoForAd:(MAAd *)arg1;
@end

