//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MAReward : NSObject
{
    NSString *_label;
    long long _amount;
}

+ (long long)defaultAmount;
+ (id)defaultLabel;
+ (id)rewardWithAmount:(long long)arg1 label:(id)arg2;
+ (id)reward;
@property(nonatomic) long long amount; // @synthesize amount=_amount;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (id)description;
- (id)initWithAmount:(long long)arg1 label:(id)arg2;

@end

