//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumber.h>

@class NSString;

@interface NSNumber (ALUtils)
+ (id)al_numberWithString:(id)arg1;
@property(readonly, copy, nonatomic) NSString *al_binaryStringValue; // @dynamic al_binaryStringValue;
@property(readonly, nonatomic) long long al_timeIntervalMillisValue; // @dynamic al_timeIntervalMillisValue;
@property(readonly, nonatomic) double al_timeIntervalValue; // @dynamic al_timeIntervalValue;
- (id)al_stringValueWithFormat:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSString *al_boolString; // @dynamic al_boolString;
@end

