//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OpenCV : NSObject
{
}

+ (id)ResizePic:(id)arg1 size:(struct CGSize)arg2;
+ (struct Mat)psf2otf:(struct Mat)arg1 size:(Size__dedc3bbb)arg2;
+ (struct Mat)C1_CV:(const struct Mat *)arg1 p1:(Size__dedc3bbb)arg2 L:(float)arg3 K1:(float)arg4 K2:(float)arg5;
+ (char *)C1_RawBytes:(char *)arg1 bpr:(int)arg2 size:(struct CGSize)arg3;
+ (struct Mat)T1_CV:(const struct Mat *)arg1 ws:(int)arg2 k:(double)arg3;
+ (id)T1:(id)arg1;
+ (struct Mat)C20_Mat:(const struct Mat *)arg1;
+ (char *)C20_Bytes:(char *)arg1 bpr:(int)arg2 size:(struct CGSize)arg3;
+ (id)C20:(id)arg1;
+ (struct Mat)C20_Mat2:(const struct Mat *)arg1;
+ (char *)C20_Bytes2:(char *)arg1 bpr:(int)arg2 size:(struct CGSize)arg3;
+ (id)C1:(id)arg1;
+ (struct Mat)C1_Mat:(const struct Mat *)arg1;
+ (struct Mat)D2_Mat2:(const struct Mat *)arg1;
+ (struct Mat)D2_Mat:(const struct Mat *)arg1;
+ (struct Mat)D1_Mat3:(const struct Mat *)arg1;
+ (struct Mat)D1_Mat2:(const struct Mat *)arg1;
+ (struct Mat)D1_Mat:(const struct Mat *)arg1;
+ (char *)C1_Bytes:(char *)arg1 bpr:(int)arg2 size:(struct CGSize)arg3;
+ (char *)D2_Bytes:(char *)arg1 bpr:(int)arg2 size:(struct CGSize)arg3;
+ (char *)D1_Bytes:(char *)arg1 bpr:(int)arg2 size:(struct CGSize)arg3;
+ (id)UIImageFromCVMat:(struct Mat)arg1;
+ (struct Mat)cvMatGrayFromUIImage:(id)arg1;
+ (struct Mat)cvMatFromUIImage:(id)arg1;

@end

