//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SKProduct, UIButton, UILabel, UIView;

@interface PurchaseProView : UIViewController
{
    UIButton *restore_button;
    UILabel *price_label;
    UIButton *buy_button;
    SKProduct *pro_product;
    UIView *temp_dialog;
    double temp_button_width;
    double temp_font_size;
    struct CGSize boundingSize;
    _Bool can_close;
}

- (void).cxx_destruct;
- (void)itemDidFinishPlaying:(id)arg1;
- (void)removeVideoPlayer;
- (void)StartVideoPlayback;
- (id)childViewControllerForStatusBarHidden;
- (_Bool)prefersStatusBarHidden;
- (void)logRestoredPurchaseEvent;
- (void)RestoreFailed;
- (void)RestoreSucceeded;
- (void)PurchaseSucceeded;
- (void)ErrorDialog;
- (void)handlePurchases:(id)arg1;
- (void)handleProductRequestNotification:(id)arg1;
- (void)fetchProductInformation;
- (void)didReceiveMemoryWarning;
- (void)CloseClick:(id)arg1;
- (void)RestoreBtnClick:(id)arg1;
- (void)BuyBtnClick:(id)arg1;
- (void)AddTopBar;
- (void)viewDidLoad;

@end

