//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SpecialSave : NSObject
{
}

+ (struct __CVBuffer *)pixelBufferFromCGImage:(struct CGImage *)arg1 size:(struct CGSize)arg2 size2:(struct CGSize)arg3;
+ (void)CreateVideo:(id)arg1 image2:(id)arg2;
+ (void)SaveAs:(id)arg1 image2:(id)arg2;

@end

