//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilter.h"

@class NSTimer;

@interface SPHue : GPUImageFilter
{
    int gl_counter;
    int gl_use_timer;
    int gl_time;
    NSTimer *e_time;
    double startTime;
    double time_counter;
    _Bool _use_timer;
    float _counter;
}

@property(nonatomic) _Bool use_timer; // @synthesize use_timer=_use_timer;
@property(nonatomic) float counter; // @synthesize counter=_counter;
- (void).cxx_destruct;
- (void)UpdateTime:(id)arg1;
- (id)init;

@end

