//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageTwoInputFilter.h"

@interface TFF : GPUImageTwoInputFilter
{
    int gl_line_intensity;
    int gl_bmode;
    int gl_s_intensity;
    float _line_intensity;
    int _bmode;
    float _s_intensity;
}

@property(nonatomic) float s_intensity; // @synthesize s_intensity=_s_intensity;
@property(nonatomic) int bmode; // @synthesize bmode=_bmode;
@property(nonatomic) float line_intensity; // @synthesize line_intensity=_line_intensity;
- (id)init;

@end

