//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UISlider.h>

@interface UIVideoSlider : UISlider
{
    _Bool _can_update;
    _Bool _being_touched;
}

@property(nonatomic) _Bool being_touched; // @synthesize being_touched=_being_touched;
@property(nonatomic) _Bool can_update; // @synthesize can_update=_can_update;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

