//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ALAdDisplayDelegate-Protocol.h"
#import "ALAdLoadDelegate-Protocol.h"
#import "GPUImageVideoCameraDelegate-Protocol.h"
#import "TOCropViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIVideoEditorControllerDelegate-Protocol.h"

@class ALAd, Animate, GPUImageFilter, GPUImagePicture, GPUImageSharpenFilter, GPUImageVideoCamera, GPUImageView, NSMutableArray, NSString, NSTimer, SKProduct, UIButton, UIImage, UIImageView, UIImpactFeedbackGenerator, UILabel, UIScrollView, UIVideoSlider, UIView, VideoSave;

@interface ViewController : UIViewController <ALAdLoadDelegate, ALAdDisplayDelegate, GPUImageVideoCameraDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIVideoEditorControllerDelegate, TOCropViewControllerDelegate>
{
    GPUImageVideoCamera *videoCamera;
    GPUImagePicture *stillPicture;
    _Bool exporting_video;
    _Bool finished_exporting;
    UIVideoSlider *video_slider;
    UIButton *play_button;
    UIButton *sound_button;
    NSTimer *slider_time;
    _Bool is_video_paused;
    _Bool is_video_muted;
    UIView *temp_dialog;
    UIView *control_bottom_bar;
    GPUImageView *filteredVideoView;
    UIImageView *stillImageView;
    UIScrollView *stillViewScroll;
    UIImpactFeedbackGenerator *feedbackGenerator;
    UIImage *filtered_image;
    UIImage *filtered_image_no_watermark;
    UIImage *original_image;
    UIImage *final_still_image;
    UIView *progress_window;
    UIView *notification_bar;
    UIView *notification_bar2;
    UIButton *progress_close_button;
    UILabel *progress_text;
    NSTimer *pTimer;
    NSTimer *globalTimer;
    NSTimer *notificationTimer;
    int seconds_counter;
    double camera_view_ratio;
    double camera_height;
    double camera_width;
    UIButton *Camera_Button;
    id Dith_obj;
    UIImage *temp_shoot_image;
    GPUImageFilter *temp_last_filter_buffer;
    GPUImageFilter *temp_last_filter_buffer_no_watermark;
    GPUImageSharpenFilter *temp_sharpness_filter;
    UIImage *watermark_overlay_picture;
    GPUImagePicture *watermark_overlay_gpuimage;
    UILabel *price_label;
    UIButton *buy_button;
    UIButton *shop_later_button;
    SKProduct *pro_product;
    UIButton *Basket_Button;
    UIImage *original_chosen_pic;
    _Bool add_watermark;
    UIImage *temp_test_image;
    Animate *anim;
    UIView *black_overlay;
    NSMutableArray *OldVideoViews;
    long long global_video_orientation;
    CDStruct_1b6d18a9 video_current_frame;
    float video_fps;
    VideoSave *save_vid;
    _Bool _is_ad_ready;
    UIImageView *_blank_background_view;
    UIView *_blank_background_container;
    ALAd *_ad;
}

@property(nonatomic) _Bool is_ad_ready; // @synthesize is_ad_ready=_is_ad_ready;
@property(retain, nonatomic) ALAd *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) UIView *blank_background_container; // @synthesize blank_background_container=_blank_background_container;
@property(retain, nonatomic) UIImageView *blank_background_view; // @synthesize blank_background_view=_blank_background_view;
- (void).cxx_destruct;
- (void)DisableIdleTimer:(_Bool)arg1;
- (void)logRestoredPurchaseEvent;
- (void)logLoadedPictureEvent;
- (void)logChangedFilterEvent:(long long)arg1;
- (void)HideLoadingAdScreen;
- (void)ShowLoadingAdScreen;
- (void)loadInterstitialAd;
- (void)ad:(id)arg1 wasClickedIn:(id)arg2;
- (void)ad:(id)arg1 wasDisplayedIn:(id)arg2;
- (void)ad:(id)arg1 wasHiddenIn:(id)arg2;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)adService:(id)arg1 didLoadAd:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)CheckStatusBar;
- (id)childViewControllerForStatusBarHidden;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)handlePurchases:(id)arg1;
- (void)handleProductRequestNotification:(id)arg1;
- (void)fetchProductInformation;
- (void)ShowThankYouDialog:(id)arg1;
- (void)ShowThankYouDialogWithMessage:(id)arg1;
- (void)ShowRateDialog;
- (void)ShowProOnlyDialog;
- (void)ShowShopDialogOld;
- (void)ShowShopDialog;
- (void)ShowCrossPromotionDialog;
- (void)ShowConnectingDialog;
- (void)ShowConnectingDialog2;
- (void)EnableShopButtons;
- (void)DisableShopButtons;
- (void)ErrorDialog;
- (void)EnableProVersion:(int)arg1;
- (void)handleHoldGesture:(id)arg1;
- (void)setupGesture;
- (void)outputAccelerationData:(CDStruct_39925896)arg1;
- (void)initializeMotionManager;
- (union _GLKVector3)lowPassWithVector:(union _GLKVector3)arg1;
- (void)calibrateMotionDetector;
- (void)stopMotionDetector;
- (union _GLKVector3)getMotionVector;
- (void)StartMotionDetector;
- (void)resumeCamera;
- (void)stopCamera;
- (void)CropViewLoadExternal:(id)arg1;
- (void)cropViewController:(id)arg1 didCropToImage:(id)arg2 withRect:(struct CGRect)arg3 angle:(long long)arg4;
- (void)SetPictureSize;
- (struct CGSize)MaxResolution:(double)arg1 height:(double)arg2;
- (void)videoEditorControllerDidCancel:(id)arg1;
- (void)videoEditorController:(id)arg1 didFailWithError:(id)arg2;
- (void)videoEditorController:(id)arg1 didSaveEditedVideoToPath:(id)arg2;
- (long long)orientationForTrack2:(id)arg1;
- (void)setRotationForFilter:(id)arg1;
- (void)ChooseVideo:(id)arg1;
- (long long)orientationForTrack:(id)arg1;
- (void)ExportVideo;
- (void)ExportVideo2;
- (struct __CVBuffer *)pixelBufferFromCGImage:(struct CGImage *)arg1 size:(struct CGSize)arg2 size2:(struct CGSize)arg3;
- (void)FinishedSpecialSaving:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)FinishedSpecialSaving;
- (void)FinishRecordingFromCamera;
- (void)StartRecordingFromCamera;
- (void)fusumaDismissedWithImage:(id)arg1;
- (void)fusumaWillClosed;
- (void)fusumaClosed;
- (id)fusumaCameraRollUnauthorized;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (id)fetchAssetCollectionWithAlbumName:(id)arg1;
- (void)insertImage:(id)arg1 intoAssetCollection:(id)arg2;
- (void)insertImage:(id)arg1 intoAlbumNamed:(id)arg2;
- (void)SavePictureSpecialDialog:(_Bool)arg1;
- (void)SpecialPictureSaveAs;
- (void)SaveSpecialEffect;
- (void)SaveToAlbum:(id)arg1;
- (void)TrippyModeClick:(id)arg1;
- (void)StopAnimationClick:(id)arg1;
- (void)ToggleCameraButton;
- (void)LaterBtnClick:(id)arg1;
- (void)LearnMoreClick:(id)arg1;
- (void)LaterBtn2Click:(id)arg1;
- (void)BuyBtnClick:(id)arg1;
- (void)RestoreBtnClick:(id)arg1;
- (void)ThanksBtnClick:(id)arg1;
- (void)HideTempDialog;
- (void)RateBtnClick:(id)arg1;
- (void)AllowCameraBtnClick:(id)arg1;
- (void)AllowMicrophoneBtnClick:(id)arg1;
- (void)AllowAlbumBtnClick:(id)arg1;
- (void)SharePictureClick:(id)arg1;
- (void)SaveLivePhotoBtnClick:(id)arg1;
- (void)SaveBeforeAfterVideoBtnClick:(id)arg1;
- (void)SaveNormalPicBlick:(id)arg1;
- (void)SaveVideoClick:(id)arg1;
- (void)SavePictureClick:(id)arg1;
- (void)SaveSpecialEffectGIF:(id)arg1;
- (void)SaveSpecialEffectLivePhoto:(id)arg1;
- (void)SaveSpecialEffectVideo:(id)arg1;
- (void)SaveSpecialEffectClick:(id)arg1;
- (void)ShootClick:(id)arg1;
- (void)RecordVideoClick:(id)arg1;
- (void)TurnCameraClick:(id)arg1;
- (void)CameraClick:(id)arg1;
- (void)CancelProcessClick:(id)arg1;
- (void)AboutClick:(id)arg1;
- (void)ShopClick:(id)arg1;
- (void)AlbumClick:(id)arg1;
- (void)SetVideoSliderToUpdate:(id)arg1;
- (void)UpdateVideoTime:(id)arg1;
- (void)UpdateVideoSlider:(id)arg1;
- (void)itemDidFinishPlaying:(id)arg1;
- (void)UpdateVideoPlayerSoundState;
- (void)SoundButtonClick:(id)arg1;
- (void)UpdateSoundButton;
- (void)PlayButtonClick:(id)arg1;
- (void)UpdatePlayButton;
- (void)ResumeVideoPlayer;
- (void)PauseVideoPlayer;
- (void)removeVideoPlayer;
- (void)StartVideoPlayback;
- (void)FinishedSavingVideo:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)FinishedSavingVideo;
- (void)ErrorSavingVideo;
- (void)FinishVideoExporting;
- (void)StartVideoExporting;
- (struct CGSize)MaxVideoResolution:(double)arg1 video_height:(double)arg2;
- (void)StartVideoExportingOld;
- (void)CancelVideoExporting;
- (void)CancelOperation;
- (void)StopProcessingVideo;
- (void)FinishedProgressBar;
- (void)HideProgressBar:(id)arg1;
- (void)RemoveProgressBar:(id)arg1;
- (void)UpdateProgress:(id)arg1;
- (void)ShowProgressBar;
- (void)ShowNotificationBarWithMessage:(id)arg1;
- (id)timeFormatted:(int)arg1;
- (void)HideRecordingBar:(_Bool)arg1;
- (void)HideRecordingBar;
- (void)ResetRecordingTimer;
- (void)UpdateRecording:(id)arg1;
- (void)ShowRecordingBar;
- (id)RedrawPictureForSharpness:(id)arg1;
- (id)AddWatermarkToPicture:(id)arg1;
- (id)GenerateWatermarkPicture;
- (void)DrawWatermarkPictureWithSize:(struct CGSize)arg1;
- (void)EndDrawingContext;
- (void)BeginDrawingContextWithSize:(struct CGSize)arg1;
- (void)AddStopAnimationButton;
- (void)CloseDialog;
- (void)CleanAllViews;
- (void)RemoveOldView:(id)arg1;
- (void)SetSmoothView;
- (void)SetSharpView;
- (void)SetScrollView;
- (void)AddBlankCanvas;
- (void)AddBottomArea;
- (void)AddTopBar;
- (void)AddControlBar;
- (void)AddVideoControlBar;
- (void)LoadInterface;
- (void)UpdateFilters;
- (void)SetupCamera;
- (void)SetupLibraryVideo;
- (void)SetupStillImage;
- (void)SetTrippyMode:(_Bool)arg1;
- (void)CheckNewFilter:(id)arg1;
- (id)NoPermission2:(int)arg1;
- (void)NoPermission:(int)arg1;
- (id)Process:(id)arg1;
- (id)RepMacro:(id)arg1;
- (void)InitApp;
- (void)Start;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

